### ISSUE TITLE
Print/Electronic ISSN are not distinguished in response

### ISSUE THREAD

**Issue by ldodds** [CrossRef/rest-api-doc#10]
E.g.: http://api.crossref.org/works/10.1787/22229566

includes:

```
"ISSN":["2222-9558","2222-9566"]
```

It would be helpful to be able to distinguish between the print and election ISSNs. This used to be separated out in the RDF versions but was dropped at some point.

**Comment by gbilder** [comment]
This is now in the API under the `issn-types` element
