### ISSUE TITLE
Query for invalid DOI returns non-relevant metadata

### ISSUE THREAD

**Issue by JorikBooij** [CrossRef/rest-api-doc#100]
A query for an invalid DOI (i.e. "10. 1016/0956-5221(95)00018-Q", mind the space after 10.) returns the metadata for a different (non-relevant) item. I.e. http://api.crossref.org/works/10.%201016/0956-5221(95)00018-Q returns the metadata for an item in "Plant physiology", while the DOI (without the space) is linked to an item in the "Scandinavian Journal of Management". All invalid DOIs return the metadata for the same item in "Plant physiology" (at this time).

I think that the API should return an error instead of the current behavior.

**Comment by sckott** [comment]
related #37

**Comment by kjw** [comment]
Now results in a 404.

**Comment by sckott** [comment]
thanks
