### ISSUE TITLE
Passing Accept headers

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#103]
Are accept headers not allowed?

This doesn't work: `curl -v -H 'Accept: application/unixref+xml' 'http://api.crossref.org/works?rows=2'` which throws a `406` - I do realize that passing in the URL works http://api.crossref.org/works/10.3897/zookeys.515.9459/transform/application/unixref+xml - but I was told that it should work with an accept header

And setting API version doesn't work either, as given at https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#how-to-manage-api-versions

**Comment by kjw** [comment]
Unixref does not support representation of more than one item. It also isn't a goal of the API to support more than its own JSON format.

However, we do provide transforms for single DOI metadata, mainly to support the content negotiation provided by data.crossref.org - see http://data.crossref.org . So for example, all of these work:

curl -H "Accept: application/unixref+xml" http://api.crossref.org/works/10.3897/zookeys.515.9459/transform

curl -L -H "Accept: application/unixref+xml" http://dx.doi.org/10.3897/zookeys.515.9459

curl -L -H "Accept: application/unixref+xml" http://data.crossref.org/10.3897/zookeys.515.9459

Also these, provided for convince of working without headers:

curl http://api.crossref.org/works/10.3897/zookeys.515.9459/transform/application/unixref+xml

curl http://api.crossref.org/works/10.3897/zookeys.515.9459.xml

**Comment by sckott** [comment]
Thanks for the clarification. What about API versions though?  What's an example curl request?  And do the versions correspond to these versions https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#version-history
