### ISSUE TITLE
Give back Solr stack errors as JSON?

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#104]
e.g., http://api.crossref.org/works?cursor=thing gives html response 

<img width="1673" alt="screen shot 2016-01-12 at 10 39 58 pm" src="https://cloud.githubusercontent.com/assets/577668/12286940/787e077a-b97d-11e5-9c38-79f4c0cd7efb.png">

Could the error message be given back as JSON instead?

**Comment by kjw** [comment]
Yes this should be a json error. Will be fixed.

**Comment by sckott** [comment]
thx

**Comment by gbilder** [comment]
this appear to have been fixed.

**Comment by sckott** [comment]
great, thanks
