### ISSUE TITLE
if a plus sign in the doi domain, something bad will happen.

### ISSUE THREAD

**Issue by wfgdx** [CrossRef/rest-api-doc#105]
If I type "http://api.crossref.org/works/10.1021/ja003055+", everything is ok. 
However, the address "http://api.crossref.org/works/10.1021/ja003055+/transform/application/x-research-info-systems" will return nothing. 
How can I fix this problem?

**Comment by hubgit** [comment]
This shouldn't be necessary, but if you double-encode the plus sign then it gets passed through as expected: 
http://api.crossref.org/works/10.1021/ja003055%252B/transform/application/x-research-info-systems

**Comment by wfgdx** [comment]
Thanks a lot. @hubgit
