### ISSUE TITLE
Exact search

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#106]
A user asked (https://github.com/ropensci/rcrossref/issues/7#issue-29024871) if there is a way to do exact searches. I realize that there are a few filters that allow exact searches for  `container-title`, `publisher-name`, `category-name`, and `type-name`, but not for general searching. Or did I miss something?  Or perhaps it's a member feature

**Comment by michael-newsrx** [comment]
Is there way to indicate "AND" for the dismax query= processing to accomplish this?

**Comment by gbilder** [comment]
I'm afraid we don't support phrase queries or dismax yet. We will investigate adding to a future version.

**Comment by sckott** [comment]
@afandian any progress on dismax?

**Comment by jenniferlin15** [comment]
Hi, @sckott. We are working on a migration to Elastic Search at the moment and will be gearing up for cayenne features once that's completed (by end of summer). Phrase queries/dismax is on the wish list so we will definitely investigate this.

**Comment by sckott** [comment]
thanks @jenniferlin15 - sounds good, i only pinged again because another user asked about it
