### ISSUE TITLE
Invalid DOI still returns a valid response to a publication

### ISSUE THREAD

**Issue by mbelmadani** [CrossRef/rest-api-doc#108]
When I request: http://api.crossref.org/works/THISISNOTAREALDOI

I get this:
{"status":"ok","message-type":"work","message-version":"1.0.0","message":{"indexed":{"date-parts":[[2016,1,13]],"date-time":"2016-01-13T10:08:54Z","timestamp":1452679734509},"reference-count":0,"publisher":"Elsevier BV","issue":"1","published-print":{"date-parts":[[2004,1,1]]},"DOI":"","type":"journal-article","created":{"date-parts":[[2004,1,27]],"date-time":"2004-01-27T22:38:15Z","timestamp":1075243095000},"page":"124-131","source":"CrossRef","title":["Liability in the Care of the Elderly"],"prefix":"http:\/\/id.crossref.org\/prefix\/10.1016","volume":"33","author":[{"affiliation":[],"family":"Iyer","given":"P."}],"member":"http:\/\/id.crossref.org\/member\/78","container-title":["Journal of Obstetric, Gynecologic, and Neonatal Nursing"],"deposited":{"date-parts":[[2016,1,10]],"date-time":"2016-01-10T20:08:34Z","timestamp":1452456514000},"score":1.0,"subtitle":[],"issued":{"date-parts":[[2004,1,1]]},"URL":"http:\/\/dx.doi.org\/","ISSN":["0884-2175"],"subject":["Critical Care","Maternity and Midwifery","Pediatrics"]}}

Seems like a bug to me.

**Comment by sckott** [comment]
duplicates in #37 #100
