### ISSUE TITLE
Error when use next cursor

### ISSUE THREAD

**Issue by platinhom** [CrossRef/rest-api-doc#109]
When get this [data](http://api.crossref.org/prefixes/10.1002/works?cursor=AoE/M2h0dHA6Ly9keC5kb2kub3JnLzEwLjEwMDIvKHNpY2kpMTA5Ni04NjI4KDE5OTgwMTEzKTc1OjI8MTkzOjphaWQtYWptZzE0PjMuMy5jbzsyLTg=), I get the next cursor: `AoE\/Mmh0dHA6Ly9keC5kb2kub3JnLzEwLjEwMDIvKHNpY2kpMTA5Ni04NjI4KDE5OTgwMTIzKTc1OjM8MjM1OjphaWQtYWptZzE+My4zLmNvOzItZA==`. But when I use this cursor for next page, it failed. [Next Cursor](http://api.crossref.org/prefixes/10.1002/works?cursor=AoE/Mmh0dHA6Ly9keC5kb2kub3JnLzEwLjEwMDIvKHNpY2kpMTA5Ni04NjI4KDE5OTgwMTIzKTc1OjM8MjM1OjphaWQtYWptZzE+My4zLmNvOzItZA==).

It return HTTP 500 error.

**Comment by nathanaelbosch** [comment]
I got to the same problem, and would be very interested in some advice!
Very similar looking cursor:
AoE/Mmh0dHA6Ly9keC5kb2kub3JnLzEwLjEwMDIvKHNpY2kpMTA5Ni04NjI4KDE5OTcwNzExKTcxOjE8ODc6OmFpZC1ham1nMTY+My4zLmNvOzItcA==

Is there any way to continue using the API at this point?

**Comment by kjw** [comment]
I think you need to URL encode the cursor due to the `==`. Can you try that?

**Comment by gbilder** [comment]
Verified that url-encoding the cursor is probably the issue. This does not work:

`http://api.crossref.org/prefixes/10.1002/works?cursor=AoE/Mmh0dHA6Ly9keC5kb2kub3JnLzEwLjEwMDIvKHNpY2kpMTA5Ni04NjI4KDE5OTgwMTIzKTc1OjM8MjM1OjphaWQtYWptZzE+My4zLmNvOzItZA==`

But same query, with url-encoded cursor does work:

`http://api.crossref.org/prefixes/10.1002/works?cursor=AoE%2FMmh0dHA6Ly9keC5kb2kub3JnLzEwLjEwMDIvKHNpY2kpMTA5Ni04NjI4KDE5OTgwMTIzKTc1OjM8MjM1OjphaWQtYWptZzE%2BMy4zLmNvOzItZA%3D%3D`
