### ISSUE TITLE
The container-title and container identifiers should be grouped together

### ISSUE THREAD

**Issue by ldodds** [CrossRef/rest-api-doc#11]
E.g:  http://api.crossref.org/works/10.1021/bk-2001-0791.ch020

Which is a chapter in a book in a series.

This lists 3 container titles:
- "Scientific and Regulatory Issues" -- this is the sub-title of the book, so possibly a metadata error?
- "Pharmaceuticals and Care Products in the Environment" -- this is the title of the book
- "ACS Symposium Series" -- this is the title of the series

The response also includes ISBN and ISSN identifiers, but its not clear to which container these apply.

It would be helpful if the responses listed the title and identifier for containers in a way that they can be easily distinguished. E.g. identify the book that this book-chapter is part of.

In the interim, is there an reliable ordering to the container-title field?

**Comment by anlausch** [comment]
Hi! Any ideas how the statistics on this issue look like? Maybe it is not reliable, but what's the majority case? Thanks in advance!

**Comment by jenniferlin15** [comment]
@pdavis can we get general stats on the frequency of book records a) associated with a book series and b) with subtitles?

**Comment by pdavis8** [comment]
I am not sure if I am able to get those stats I am afraid. The best that I can seem to return is total of book series we have: 
http://api.crossref.org/types/book-series/works?rows=0
and with subtitles I wasn't able to get a figure but you can see that there are not many from this:
http://api.crossref.org/types/book-series/works?select=subtitle&rows=1000
