### ISSUE TITLE
Query articles based on Authors and Title

### ISSUE THREAD

**Issue by nmehta** [CrossRef/rest-api-doc#111]
Hi -

Would it be possible to specify a query where we would like to return articles best matched against specific fields?  Specifically I would like to specify a query to search for articles that best match against a list of authors and the title of an article, where the authors would have a higher relevance or boost factor.

I'm thinking this might be possible using the DisMax parameters, but my initial tests have not worked successfully. 

Thanks for your help,
Neil

**Comment by sckott** [comment]
#3

**Comment by kjw** [comment]
Now available as field queries on `/works`:

https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#field-queries
