### ISSUE TITLE
Pingback URL feature doesn't work!

### ISSUE THREAD

**Issue by ismailbaskin** [CrossRef/rest-api-doc#113]
I created a depostit with `POST https://api.crossref.org/deposits?pingback=http%3A%2F%2Fmydomain.com%2Fpingback`. When I checked `https://api.crossref.org/deposits/57fabcbe-2def-4f21-9d05-6e10eaa7c95d` page shows me `status: "completed",` and `pingback-url : http://mydomain.com/pingback` as expected. Unfortunately there is no ping action to this URL

**Comment by ismailbaskin** [comment]
@afandian @andrewgilmartin @dataoverflow @kjw plz help

**Comment by andrewgilmartin** [comment]
Thank you for the bug report. We will look into fixing early in the week.

**Comment by ismailbaskin** [comment]
Is there any improvement?

**Comment by ismailbaskin** [comment]
Ping @kjw @gbilder

**Comment by jenniferlin15** [comment]
@andrewgilmartin please provide update on this ticket so we can consider it closed or prioritize it.

**Comment by ckoscher** [comment]
@andrewgilmartin has nothing to do with this system. This is part of the deprecated rest-api deposit code

**Comment by ppolischuk** [comment]
Filed this as CS-3833. Closing this issue as out of scope of this repo.
