### ISSUE TITLE
Is there a good reason why title is an array?

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#114]
and not a string

e.g., 

```
curl 'http://api.crossref.org/works?rows=1' | jq .message.items[].title
#> [
#>   "Photoluminescent ZnO Nanoparticles and Their Biological Applications"
#> ]
```

**Comment by sckott** [comment]
I guess same goes for `container-title` and `ISSN` 

I assume because these can have more than one value?  If so, nevermind, makes sense :)

**Comment by ioverka** [comment]
At least, container-title and ISSN can have various entries, see:

http://api.crossref.org/works/10.1007/s11956-008-1009-1:

`[...],"container-title":["Cytol. Genet.","Cytology and Genetics"],[...],"ISSN":["0095-4527","1934-9440"][...]`

**Comment by sckott** [comment]
yeah, i figured that they can have multiple entries while I was writing the issue, closing
