### ISSUE TITLE
Score doc

### ISSUE THREAD

**Issue by SteveViss** [CrossRef/rest-api-doc#116]
Hi CrossRef Team,

With @KevCaz, we're currently doing a meta-analysis on the scientific production of specific topics (Climate Change, species lost etc.) using the crossref API / rcrossref package. We would like to have some details on how the score is computed and which metadata are used: title, abstract, keywords etc. These informations will be helpful to take methodological decisions.

Thanks for your amazing work !
Best,
Steve

**Comment by kjw** [comment]
It's a term frequency, inverse document frequency score that comes straight out of the Solr backend, based on basic bibliographic metadata fields including title, publication title, authors, ISSN, publisher and date of publication.
