### ISSUE TITLE
Error returned by 'journals/{issn}/works' route: Resource not found

### ISSUE THREAD

**Issue by ioverka** [CrossRef/rest-api-doc#119]
Dear CrossRef team,

according to the ISSN register, the journal "Physial Review A" by APS uses following ISSNs since 2016:

```
ISSN    2469-9934
ISSN-L  2469-9926
Medium  Computer remote
Key Title   Physical review. A (Online)
[...]
Additional Physical Form Entry  Physical review. A [ISSN 2469-9926]
Additional Physical Form Entry  Physical review. A (CD-ROM) [ISSN 2469-9942]
Continues   Physical review. A, Atomic, molecular, and optical physics (Online) [ISSN 1094-1622]
```

The CrossRef records for the 2016 articles from PhysRevA already refer to these ISSNs, see http://api.crossref.org/works/10.1103/PhysRevA.93.053408:
`[...],"ISSN":["2469-9926","2469-9934"],"[...]`

However, requesting the corresponding 'journals/{issn}/works' routes return the error "Resource not found", see 
- http://api.crossref.org/journals/2469-9926/works
- http://api.crossref.org/journals/2469-9934/works

**Comment by hubgit** [comment]
I just encountered this for 2 new journals:

http://api.crossref.org/works/10.1139/facets-2016-0003 (work exists, with ISSN 2371-1671)
https://api.crossref.org/journals/2371-1671/works (journal not found)

http://api.crossref.org/works/10.1021/acsomega.6b00014 (work exists, with ISSN 2470-1343)
https://api.crossref.org/journals/2470-1343/works (journal not found)

**Comment by gbilder** [comment]
I suspect this issue has to do with journal name/ISSN changes. The info that we get from our title list does not include ISSN change histories- just current ISSNs. See this related issue for more background an implications.
 
https://github.com/CrossRef/rest-api-doc/issues/139

We  are considering what options we have to address this issue.
