### ISSUE TITLE
Overview document password protected

### ISSUE THREAD

**Issue by tfmorris** [CrossRef/rest-api-doc#120]
The link to the overview document in https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md:

http://api.crossref.org/docs/funder_kpi_metadata_best_practice.html

brings up an authentication dialog.

**Comment by ioverka** [comment]
see #88 

But I agree that the "CrossRef REST API" document should be updated...

**Comment by kjw** [comment]
Broken link fixed.
