### ISSUE TITLE
Where is info about what type of work an article is for a given DOI

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#122]
Some info here http://www.crossref.org/02publishers/glossary.html has status of the work as `Accepted Author Manuscript` or `Author version`, etc. 

where can one get this data? in the crossref API? content negotation possibly?

cc @afandian @kjw

**Comment by kjw** [comment]
As far as I know we don't have these in our metadata, yet. They are being added to our deposit schema in a coming release.

**Comment by sckott** [comment]
thanks
