### ISSUE TITLE
Is it possible to fetch list of journals for multiple ISSNs?

### ISSUE THREAD

**Issue by unoexperto** [CrossRef/rest-api-doc#123]
Sometime I need to do a lookup for a journal for an article I have. Often article have multiple ISSNs in its metadata. Ideally I'd prefer to do it in one call you CrossRef API.

Is it possible to fetch list of journals for list of IDs ? Something like

`http://api.crossref.org/journals?rows=10&filter=issn:0000-0000,0000-0001`

**Comment by kjw** [comment]
It isn't the best at the moment is to do two calls:

    https://api.crossref.org/journals/0000-0000

and

    https://api.crossref.org/journals/0000-0001

then combine the results. I could add in an `issn` filter to the `journals` route. Is it a problem to use two calls rather than one?

**Comment by cppexpert** [comment]
Yeah, that's what I do now. It's not a problem for me. But I thought it would be nice to hit your servers less.
