### ISSUE TITLE
How do you decide what object to return if you have multiple object matching ID ?

### ISSUE THREAD

**Issue by unoexperto** [CrossRef/rest-api-doc#125]
How do you decide what object to return if you have multiple objects matching ID ? For example you have 4 journals with ISSN `1522-2624`:
- 0372-9702
- 0044-3263
- 0372-851X
- 1436-8730

All these 4 journals seems to be the same journal. What criteria you use to decide what to return on `api.crossref.org/journals/1522-2624` ?

Same goes for `0000-0000` for which you have over 100 journals.

**Comment by gbilder** [comment]
The issue you are seeing here is probably related to the journal changing its name. When a journal changes its name, it is supposed to change its ISSN. In this case, you can see the history of name changes here:

http://onlinelibrary.wiley.com/journal/10.1002/(ISSN)1522-2624/issues

When you use the API to query ISSNs, we simply return records matching exactly what you provided. We do not have the history of name changes and so not not return records for the same journal under a previous name/issn.
