### ISSUE TITLE
update publisher for a journal

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#127]
this http://api.crossref.org/journals?query=african%20invertebrates has Bioone as the publisher, but Pensoft is the publisher http://africaninvertebrates.pensoft.net/ - is this just a case where the metadata hasn't been updated yet?  I imagine Bioone used to be the publisher

**Comment by sckott** [comment]
another eg http://api.crossref.org/journals?query=biodiscovery where the current publisher appears to be pensoft, not Dundee Science Press, I can't seem to find Dundee Science Press gogling either

**Comment by ioverka** [comment]
This issue seems to relate to my questions regarding the origin of the publisher information for a particular work or journal, see #85.

Regarding "African Invertebrates": The prefix of the included works (10.5733) is actually owned by a member with the name "BioOne (Natal Museum of South Africa)", see http://www.crossref.org/06members/50go-live.html

And guess which member name is associated to the prefix used for registering DOIs for works in "BioDiscovery" (10.7750)... yes, it's "Dundee Science Press" ;)

**Comment by sckott** [comment]
thx, hmmm

**Comment by ioverka** [comment]
yeahmmm... also, the requirements regarding "currentness" of the publisher information probably differ for bother routes. For "journals", most people probably expect the name of the recent publisher. For "works", I personally would like to receive the name of the publisher by the time of the publication...

**Comment by kjw** [comment]
So at the moment the publisher name for the work is taken at the time of deposit. But that's the name that Crossref has. It may then get updated at the time of each subsequent deposit.

I like the idea of recording this as the name at the time of publication but it is likely that the underlying system that the API takes its data from is not able to reproduce that information.

**Comment by ioverka** [comment]
Thanks a lot @kjw, for getting back on this issue. 

Just to understand the current situation: Which name is used as "publisher" for a specific work or a specific journal?

* for works: Is it the "primary name" of the associated member at time of deposit resp. last update of the work record? (Question: Why is it not the "name" of the corresponding prefix?)

* for journals: Is ith the "primary name" of the associated member at time of deposit/last update of the journal record? (Note: That would explain why the publisher of a journal record may differ from the publisher of a work record - the names may represent different snapshots of the CrossRef data).

I feel like it might be worth considering to remove the publisher element from the works route completely. That suggestion probably sounds a bit stupid, but it would fix the problem of misinterpretation. It's reasonable to think that the "publisher" element was part of the metadata record deposited by the publisher while DOI assignment and won't change over time. 

Additional question (sorry ;-): Are there other elements in the works response that have been "calculated" at time of deposit/last update, e.g. the "container-title"?

**Comment by kjw** [comment]
Publisher names on journals are now updating, and are correct for these journals.
