### ISSUE TITLE
Why do some Informa articles have links to full text from Elsevier API?

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#128]
e.g., see http://api.crossref.org/members/301/works?filter=has-full-text:true&rows=400

Perhaps there is some business arrangement I don't understand, or is there a mistake?

**Comment by kmeddings** [comment]
"The International Information & Library Review,
Formerly known as International Library Review; Title transferred to Taylor & Francis as of 2014;"

The journal moved in 2014, so articles before that date will have the original metadata but the new URL.

**Comment by sckott** [comment]
thanks
