### ISSUE TITLE
filter for has-references is not giving works with a list of references in the meta data

### ISSUE THREAD

**Issue by mbrunnen** [CrossRef/rest-api-doc#132]
The filter `filter=has-references:true` which should return

> metadata for works that have a list of references

is not giving me any list of references in the meta data. Does this filter just mean the work has a "printed" reference list in the document? If so, is there any possibility to get this list?
I am using this url:
[http://api.crossref.org/works?filter=has-references:true&rows=1](http://api.crossref.org/works?filter=has-references:true&rows=1)

I am new to this, so may be it's just me...

**Comment by mbrunnen** [comment]
Ok,I think I'll have to wait a bit... http://blog.crossref.org/2016/06/distributing-references-via-crossref.html

**Comment by kjw** [comment]
Yeah, unfortunately, we can only provide reference lists in some cases. Right now the API doesn't provide any at all, but it will do at some point where we are allowed to release them.

**Comment by gbilder** [comment]
You can start to see references now.

http://api.crossref.org/works?filter=has-references:true&rows=1

Note that not all of our members make their references public. You can see a list of those who do as follows:

http://api.crossref.org/members?filter=has-public-references:true
