### ISSUE TITLE
Possible to include publication history

### ISSUE THREAD

**Issue by matthewdavidlloyd** [CrossRef/rest-api-doc#133]
I'm currently working on a project where I need to know the received, accepted and online publication date of articles. Is there any way to include this into the API?

I'm mostly interested in things where I know the doi, and want the metadata. eg: http://api.crossref.org/works/10.1016/j.physletb.2016.01.032

**Comment by ckoscher** [comment]
We currently do not collect from publishers anything for received or accepted dates. We only have the print and/or on-line publication dates.

We will be adding manuscript accepted dates in the future (3-5 months), but of course it will take a long time for publishers to actually populate that field.

**Comment by gbilder** [comment]
Actually, some of our members already submit received/accepted dates in their CrossMark data. IUCR, for example, does this for all of their current content . See:

http://api.crossref.org/members/329/works

Probably not enough coverage for your project, but thought you should at least know.

**Comment by kjw** [comment]
For the few records with accepted assertions, or other timestamp assertions, you can filter them into results:

http://api.crossref.org/works?filter=assertion:accepted
