### ISSUE TITLE
DOI resolves but not found in works API

### ISSUE THREAD

**Issue by hubgit** [CrossRef/rest-api-doc#137]
I was researching a DOI ([10.4435/BSPI.2012.23](https://doi.org/10.4435/BSPI.2012.23)) that resolves to the publisher homepage rather than [the article](http://paleoitalia.org/media/u/archives/06_Lombardo_et_al_2012_BSPI_513.pdf), but it doesn't seem to be available in the API: https://api.crossref.org/works/10.4435/bspi.2012.23

Any idea what type of DOI this is, and why it's not appearing in the API?

**Comment by ckoscher** [comment]
This is a mEDRA DOI, which they have not deposited with Crossref (in fact the prefix is not registered in Crossref)
see https://doi.crossref.org/doiRA/10.4435/bspi.2012.23

**Comment by kjw** [comment]
@hubgit I recommend using the /agency route for checking on RA: //https://api.crossref.org/works/10.4435/bspi.2012.23/agency
