### ISSUE TITLE
Works route: Is there a filter for '<free-to-read>'?

### ISSUE THREAD

**Issue by ioverka** [CrossRef/rest-api-doc#138]
Is the element used at the API at all? I wasn't able to find an example...

Thanks,
inga

**Comment by kjw** [comment]
Unfortunately there is not at the moment, but I will add it in.

**Comment by kmeddings** [comment]
Picked this up and added to backlog.

**Comment by jenniferlin15** [comment]
Ticketed - GO-372

**Comment by jenniferlin15** [comment]
This is missing metadata in our REST API results. Categorizing as bug.

**Comment by ppolischuk** [comment]
I believe this should satisfy this request: https://www.crossref.org/blog/helping-researchers-identify-content-they-can-text-mine/
