### ISSUE TITLE
Is there a way to filter through country?

### ISSUE THREAD

**Issue by aadivar** [CrossRef/rest-api-doc#141]
Hey Crossref Team, We wanted to some analysis on the publications metadata by accessing country specific publications. I couldn't find any in  the API documentation. Can you please give me any reference to find it so!

Thanks
AADI

**Comment by kjw** [comment]
There isn't, sorry. We don't collect geographic location for individual DOIs. We do collect a string that represents a publisher's registered office, but 1) this data is messy and 2) this isn't always where people would think the publication is from.
