### ISSUE TITLE
Work has null in ISSN element

### ISSUE THREAD

**Issue by unoexperto** [CrossRef/rest-api-doc#142]
Following items

http://api.crossref.org/works/10.1017/s135246580000401x
http://api.crossref.org/works/10.1017/s135577189800911x

have null in ISSN element.

**Comment by kjw** [comment]
Blurgh, ok, will look.

**Comment by cppexpert** [comment]
Thanks, Karl! There are lots of items like that. These two are not the only ones.

**Comment by ckoscher** [comment]
FYI, the deposit of DOI 10.1017/s135246580000401x  has:
<full_title>Behavioural and Cognitive Psychotherapy</full_title><abbrev_title>Behav. Cognit. Psychother.</abbrev_title><issn media_type="print">1352–4658</issn>

**Comment by gbilder** [comment]
FTR- that record did not have and ISSN deposited. having said that, then we should simply not include the element.

To complicate matters, that DOI now seems to be missing entirely from the API index.

**Comment by unoexperto** [comment]
@gbilder Do you allow depositor to delete records via API ?

**Comment by gbilder** [comment]
Sorry- I should have been clearer- the metadata is still registered with us. The problem is that that record has not been added to our API index. This is justa bug on the part of our system.

An "no", depositors cannot delete records. Would kind of undermine the "persistent" part of PID, no? ;-)

**Comment by kjw** [comment]
Turns out this is because of unnormalised ISSN data in our deposit XML.

**Comment by kjw** [comment]
Our parser for this metadata is fixed, but now waiting on a re-index of our metadata.

**Comment by unoexperto** [comment]
@kjw What's the ETA for having metadata reindexed ?

I've got NULL item today in following query
http://api.crossref.org/works?rows=1000&filter=type:journal-article&order=asc&sort=deposited&cursor=AoN43IS53pACcILVqLPdAj8MaHR0cDovL2R4LmRvaS5vcmcvMTAuMTAxNy9zMDAzODAzODU5ODMwMDEzOQ%3D%3D

```
{
  "subtitle": [],
  "author": [
    {
      "given": "Rajmil",
      "family": "Fischman",
      "affiliation": []
    }
  ],
  "deposited": {
    "date-parts": [
      [
        2007,
        2,
        13
      ]
    ],
    "date-time": "2007-02-13T20:56:13Z",
    "timestamp": 1171400173000
  },
  "article-number": "S135577189800911X",
  "is-referenced-by-count": 0,
  "alternative-id": [
    "S135577189800911X",
    "10.1017/S135577189800911X"
  ],
  "original-title": [],
  "source": "Crossref",
  "subject": [
    "General Engineering",
    "General Earth and Planetary Sciences",
    "General Environmental Science"
  ],
  "relation": {},
  "prefix": "10.1017",
  "URL": "http://dx.doi.org/10.1017/s135577189800911x",
  "page": "1-2",
  "score": 1.0,
  "indexed": {
    "date-parts": [
      [
        2017,
        7,
        21
      ]
    ],
    "date-time": "2017-07-21T19:32:21Z",
    "timestamp": 1500665541323
  },
  "issn-type": [
    {
      "value": null,
      "type": "print"
    }
  ],
  "references-count": 0,
  "issue": "1",
  "issued": {
    "date-parts": [
      [
        1998,
        4
      ]
    ]
  },
  "content-domain": {
    "domain": [],
    "crossmark-restriction": false
  },
  "member": "56",
  "short-title": [],
  "publisher": "Cambridge University Press (CUP)",
  "container-title": [
    "Organised Sound"
  ],
  "title": [
    "Microstructure and macrostructure"
  ],
  "type": "journal-article",
  "published-print": {
    "date-parts": [
      [
        1998,
        4
      ]
    ]
  },
  "short-container-title": [
    "Org. Sound"
  ],
  "volume": "3",
  "ISSN": [
    null
  ],
  "created": {
    "date-parts": [
      [
        2002,
        7,
        27
      ]
    ],
    "date-time": "2002-07-27T13:40:17Z",
    "timestamp": 1027777217000
  },
  "DOI": "10.1017/s135577189800911x",
  "reference-count": 0
}
```
