### ISSUE TITLE
XML transform broken for SICIs

### ISSUE THREAD

**Issue by afandian** [CrossRef/rest-api-doc#145]
The semicolon is probably confusing it (it's designated as a query seprator)

http://api.crossref.org/works/10.1002/1521-4109(200103)13:4%3C313::AID-ELAN313%3E3.0.CO;2-Q/transform/application/vnd.crossref.unixsd+xml

**Comment by kjw** [comment]
Use content negotiation on the /works/doi route for now.

**Comment by gbilder** [comment]
added reminder on url-encoding in documentation
