### ISSUE TITLE
Prefix-only queries return an unusual record with no DOI

### ISSUE THREAD

**Issue by hubgit** [CrossRef/rest-api-doc#15]
I'm not sure what should be returned from a query that only contains the DOI prefix (perhaps a list of all the records with that DOI prefix?), but it's currently [returning an unrelated record that has no DOI](https://api.crossref.org/works/10.7717/), rather than an error message.

**Comment by kjw** [comment]
There's now additional checks such that invalid or unknown IDs in routes will always return 404s.
