### ISSUE TITLE
corporate authors not exposed in json

### ISSUE THREAD

**Issue by gbilder** [CrossRef/rest-api-doc#151]
See, for example:

http://api.crossref.org/works/10.1371/journal.pone.0006924

XML lists two corporate authors:

http://api.crossref.org/works/10.1371/journal.pone.0006924.xml

See a longer list of examples here:

https://www.wikidata.org/wiki/Wikidata:WikiProject_Source_MetaData/Source,_M.D./Tests#Consortia_.28corporate_authors.29

**Comment by kjw** [comment]
Corporate authors now listed.
