### ISSUE TITLE
Delays of more than a day

### ISSUE THREAD

**Issue by Daniel-Mietchen** [CrossRef/rest-api-doc#154]
I am getting more "Resource not found" responses these days than usual for items published more than 24h ago.
Some current examples:
https://api.crossref.org/v1/works/http://dx.doi.org/10.1016/j.chom.2016.09.006
https://api.crossref.org/v1/works/http://dx.doi.org/10.1177/0961203316671816
https://api.crossref.org/v1/works/http://dx.doi.org/10.1101/078923

Is this just a delay on the publishers' ends or is there an additional component at Crossref, or am I making this up?

**Comment by gbilder** [comment]
Sorry about delay in response. These all finally appeared. We have occasionally had large backlogs at the start of the month. Recent change in queue should alleviate this kind of thing. Change was made in November.
