### ISSUE TITLE
rest API not giving correct result for 'exact match'

### ISSUE THREAD

**Issue by kunjan21** [CrossRef/rest-api-doc#156]
Hi,
When I m searching a specific string like "The quest for determining the glamorous conditions of the human facial skin based on the texture, color, health perception, races, age and charm is never-ending. Manifestation of facial skin is subjected to the physical and physiological state of human emotions. "
this is the abstract of Journal 3D Research for issue June 2015. Its DOI is 10.1007/s13319-015-0044-9 Publisher is Springer.
When I pass this as string in the REST API by using Curlopt statement, the result I m getting is not the above DOI. Rather I m getting two DOI of Wiley Blackwell Publisher mentioned below:
http://dx.doi.org/10.1111/srt.12174 
and 
http://dx.doi.org/10.1111/j.1468-2494.2009.00535.x
 Kindly mention if there is something we need to add to find the exact match or may be  some code to be changed. Kindly assist.
Reply Awaited.
Regrds,
Ms. Kunjan

**Comment by ckoscher** [comment]
Abstracts are not indexed in the REST API. The search returns whatever DOI's have an article title that to some (small?) degree matches the query string.

**Comment by kunjan21** [comment]
Thank You ckoscher for replying,
Kindly assist from where we can get the abstract and TOC of journals. Which API do we have to include??

**Comment by gbilder** [comment]
Abstracts are in the API now for those publishers who provide them:

`http://api.crossref.org/works?filter=has-abstract:true`

But please note that only a few publishers provide them as they are not a required element for our members.

**Comment by monperrus** [comment]
FTR Crossref support says today:

> Our API doesn't support exact string matching for any field except for singleton fields (doi, issn, etc)
