### ISSUE TITLE
Exact match on Author Name

### ISSUE THREAD

**Issue by jbborre** [CrossRef/rest-api-doc#158]
Is it possible to query by exact match on Author or Editor?  The current search appears to match on first name and/or last name.

**Comment by zk3855** [comment]
I very much second that!

**Comment by kjw** [comment]
It entirely depends on what metadata Crossref has been provided, but there are now ways to search only on the author or editor field, using the new query parameters, `query.author` and `query.editor`.

**Comment by monperrus** [comment]
duplicate of #143 ?

**Comment by jbborre** [comment]
Kind of but it was more related to how crossref was matching across multiple words regardless of the exact phrase.  ex. John Smith using query.author used to match John Doe and Frank Smith...

**Comment by monperrus** [comment]
One option would be to be able to match given name and surname separately

query.author.givenname=john&query.author.surname=smith

but this does not seem to work.

**Comment by marquesarthur** [comment]
This issue was closed, but I don't see how it was addressed. Could you please detail?

**Comment by ppolischuk** [comment]
I'll add the same link as I just noted in #143 in case somebody else lands on this thread. Please see the discussion here: https://gitlab.com/crossref/rest_api/-/merge_requests/195#note_361972615

**Comment by monperrus** [comment]
FTR Crossref support says today:

> Our API doesn't support exact string matching for any field except for singleton fields (doi, issn, etc)
