### ISSUE TITLE
/licenses route does not work as expected

### ISSUE THREAD

**Issue by pietsch** [CrossRef/rest-api-doc#162]
According to https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md, since v15 (2014-02-27), a GET request to http://api.crossref.org/licenses?filter=member:78 should return all licenses linked to works published by Elsevier. Instead, I get the following error message:
```json
{
  "status": "failed",
  "message-type": "validation-failure",
  "message": [
    {
      "type": "parameter-not-allowed",
      "value": "filter",
      "message": "This route does not support filter"
    }
  ]
}
```

Other member IDs I tried do not work either.

**Comment by pietsch** [comment]
ping

**Comment by sckott** [comment]
last I heard, they no longer support filter on this route at all

**Comment by kjw** [comment]
Swap this around to a facet on `/works`. So:

    http://api.crossref.org/v1/works?facet=license:*&filter=member:78&rows=0

I'm not keen on the `/licenses` route because it is a special case of just one of the many facets available on `/works`. I am considering removing it.

**Comment by tporquet** [comment]
The examples provided on 
rest-api-doc/rest_api.md
rest_api_koans.md
rest_api_tour.md
for the /licenses route with filters don't work and should be updated (replaced with the facet on the /works route that @kjw mentionned)
Thanks

**Comment by gbilder** [comment]
updated examples in doc

**Comment by tporquet** [comment]
thanks!
