### ISSUE TITLE
Question: Documentation for api.wiley.com ?

### ISSUE THREAD

**Issue by behrica** [CrossRef/rest-api-doc#164]
Hi,

I am not sure, if this is the right place to ask, but as I saw some comment in this repoitory, I was wondering, if you know about any documentation regarding which methods are available for "api.wiley.com".

I managed to use the crossref API to query articles of Wiley for a given journal, and in the reponse they were indeed links to the full text PDF, which I got working as described in #96

**Comment by kjw** [comment]
I would recommend talking to Wiley and asking if they have any documentation on their API.
