### ISSUE TITLE
Problem with agency route for DOIs with non-word characters	

### ISSUE THREAD

**Issue by njahn82** [CrossRef/rest-api-doc#165]
Hi, 

I am having a problem to test the agency for DOIs that consist of non-word characters.

Take this DOI:

10.1002/(SICI)1521-3773(19990601)38:11<1598::AID-ANIE1598>3.0.CO;2-J

Calling for metadata works:

http://api.crossref.org/works/10.1002/(SICI)1521-3773(19990601)38:11%3C1598::AID-ANIE1598%3E3.0.CO;2-J

But not when using the agency route

http://api.crossref.org/works/10.1002/(SICI)1521-3773(19990601)38:11%3C1598::AID-ANIE1598%3E3.0.CO;2-J/agency

**Comment by afandian** [comment]
It looks like you are URL encoding the characters like `>` but not `;`. The `;` character is reserved (it has the same meaning as `?` I think). It's one of those annoying things about SICIs. Try encoding it to '%3B`?
