### ISSUE TITLE
Deposit API documentation does not match live API

### ISSUE THREAD

**Issue by chbrown** [CrossRef/rest-api-doc#166]
Is `rest-api-doc/deposit_api.md` auto-generated? Not sure if it's worth a PR to fix https://github.com/CrossRef/rest-api-doc/blob/master/deposit_api.md directly, or if it just missed an update when the API last changed, but, for example, the "CrossRef REST API documentation" link doesn't work, and the filters in that section don't match the current API. For example,

    curl -u honey:potluck https://api.crossref.org/deposits?filter=from-submitted-date:2016-11-01

Complains with an error. From the `.message[0].message` field (intriguing choice of names, btw):

> Filter from-submitted-date specified but there is no such filter for this route. Valid filters for this route are: from-submission-time, until-submission-time, status, owner, type, doi, test

**Comment by kjw** [comment]
The docs have been updated to match the live API.
