### ISSUE TITLE
Document with malformed DOI is in DB: 10.1001/jama.251.19.2504,2509

### ISSUE THREAD

**Issue by unoexperto** [CrossRef/rest-api-doc#167]
Found malformed DOI in DB. Query to get it is

http://api.crossref.org/works?rows=1&filter=type:journal-article&order=asc&sort=deposited&cursor=AoJ43IS53pACPwtodHRwOi8vZHguZG9pLm9yZy8xMC4xMDAxL2phbWEuMjUxLjE5LjI1MDM=

**Comment by unoexperto** [comment]
And I found more:

10.1001/jama.251.7.878,883
10.1001/jama.258.22.3217,3219

**Comment by ckoscher** [comment]
In the past a comma was a legal character in a Crossref DOI ( these DOIs were last touched in 2007). The restriction preventing commas was put in place after that.

So.... these are not malformed DOIs
Chuck

**Comment by afandian** [comment]
I should add that it's the Publisher site that doesn't recognised them. If the DOI wasn't well formed or didn't exist you would get this error page: http://doi.org/10.5555/XXXXX

We'll report these errors to the publisher, thanks for bringing these to our attention @unoexperto!
