### ISSUE TITLE
HttpSolrClient$RemoteSolrException: Unable to parse 'cursorMark' after totem: value must either be '*' or the 'nextCursorMark' 

### ISSUE THREAD

**Issue by unoexperto** [CrossRef/rest-api-doc#168]
Guys, sometimes I get following exception when using cursors

```
{
  "status": "error",
  "message-type": "exception",
  "message-version": "1.0.0",
  "message": {
    "name": "class org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException",
    "description": "org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http:\/\/mds4:8983\/solr\/crmds1: Unable to parse 'cursorMark' after totem: value must either be '*' or the 'nextCursorMark' returned by a previous search: AoJ43IS53pACPyBodHRwOi8vZHguZG9pLm9yZy8xMC4xMTMwLzAwMTYtNzYwNigxOTc0KTg1PDgzOTpjY3Nhc2k Mi4wLmNvOzI=",
    "message": "Error from server at http:\/\/mds4:8983\/solr\/crmds1: Unable to parse 'cursorMark' after totem: value must either be '*' or the 'nextCursorMark' returned by a previous search: AoJ43IS53pACPyBodHRwOi8vZHguZG9pLm9yZy8xMC4xMTMwLzAwMTYtNzYwNigxOTc0KTg1PDgzOTpjY3Nhc2k Mi4wLmNvOzI=",
    "cause": null
  }
}
```

Why does it happen and how do I recover ?

**Comment by unoexperto** [comment]
Guys, I'm stuck with this issue again. Last successful cursor is

http://api.crossref.org/works?rows=1000&filter=type:journal-article&order=asc&sort=deposited&cursor=AoJ43IS53pACPyBodHRwOi8vZHguZG9pLm9yZy8xMC4xMTMwLzAwMTYtNzYwNigxOTgwKTkxPDI0OTpyc2Fvb3A+Mi4wLmNvOzI=

then I get `AoJ43IS53pACPyBodHRwOi8vZHguZG9pLm9yZy8xMC4xMTMwLzAwMTYtNzYwNigxOTgwKTkxPDI0OTpyc2Fvb3A+Mi4wLmNvOzI=` which fails with 

```
{
  "status": "error",
  "message-type": "exception",
  "message-version": "1.0.0",
  "message": {
    "name": "class org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException",
    "description": "org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http:\/\/mds4:8983\/solr\/crmds1: Unable to parse 'cursorMark' after totem: value must either be '*' or the 'nextCursorMark' returned by a previous search: AoJ43IS53pACPyBodHRwOi8vZHguZG9pLm9yZy8xMC4xMTMwLzAwMTYtNzYwNigxOTgwKTkxPDI0OTpyc2Fvb3A Mi4wLmNvOzI=",
    "message": "Error from server at http:\/\/mds4:8983\/solr\/crmds1: Unable to parse 'cursorMark' after totem: value must either be '*' or the 'nextCursorMark' returned by a previous search: AoJ43IS53pACPyBodHRwOi8vZHguZG9pLm9yZy8xMC4xMTMwLzAwMTYtNzYwNigxOTgwKTkxPDI0OTpyc2Fvb3A Mi4wLmNvOzI=",
    "cause": null
  }
}
```

@afandian could  you please advise ?

**Comment by unoexperto** [comment]
And it seems like something is wrong with this cursor although I don't see anything special in its bytes after base64 decoding. Interestingly I could bypass broken cursor by doing this

I request only 100 items
http://api.crossref.org/works?rows=100&filter=type:journal-article&order=asc&sort=deposited&cursor=AoJ43IS53pACPx9odHRwOi8vZHguZG9pLm9yZy8xMC4xMTMwLzAwMTYtNzYwNigxOTcxKTgyWzEzNzc6bndjZF0yLjAuY287Mg==

Next cursor points to items after `http://dx.doi.org/10.1130/0016-7606(1971)82[3231:aescwl]2.0.co;2`.

Just for the sake of experiment I request 900 items using this  cursor
http://api.crossref.org/works?rows=900&filter=type:journal-article&order=asc&sort=deposited&cursor=AoJ43IS53pACPyFodHRwOi8vZHguZG9pLm9yZy8xMC4xMTMwLzAwMTYtNzYwNigxOTcxKTgyWzMyMzE6YWVzY3dsXTIuMC5jbzsy

and next-cursor is again broken one. But if I request 1000 instead of 900 thus jumping 100 items over broken one I continue to fetch  data correctly.

What could it be ?

**Comment by ioverka** [comment]
I guess you have to encode the cursor value (the + sign from your example is interpreted as blank), i.e.

http://api.crossref.org/works?rows=1000&filter=type:journal-article&order=asc&sort=deposited&cursor=AoJ43IS53pACPyBodHRwOi8vZHguZG9pLm9yZy8xMC4xMTMwLzAwMTYtNzYwNigxOTgwKTkxPDI0OTpyc2Fvb3A%2BMi4wLmNvOzI=

seems to work.

**Comment by unoexperto** [comment]
Wow. You're right! Thanks!
