### ISSUE TITLE
Filter by publisher internal ID

### ISSUE THREAD

**Issue by afandian** [CrossRef/rest-api-doc#17]
Please add a filter by internal publisher ID on `/works`. Note that these aren't unique.

I believe this is `publisher_item` > `item_number` in the schema.

Example DOI 10.1371/journal.pone.0109035

**Comment by kjw** [comment]
Now available via an `alternative-id` field in work metadata responses. An `alternative-id` filter is also provided for `/works` routes. PIIs and 'other' identifiers collected by CrossRef can be searched for using this filter.
