### ISSUE TITLE
Missing content-type header in some requests

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#172]
e.g., http://api.crossref.org/members/323234343434/works?facet=t 

```
Connection:close
Content-Length:274
Date:Wed, 14 Dec 2016 15:26:16 GMT
Exception-Name:class java.lang.NumberFormatException
Server:http-kit
X-Rate-Limit-Interval:1s
X-Rate-Limit-Limit:50
```

body is

```json
{
  "status": "error",
  "message-type": "exception",
  "message-version": "1.0.0",
  "message": {
    "name": "class java.lang.NumberFormatException",
    "description": "java.lang.NumberFormatException: For input string: \"323234343434\"",
    "message": "For input string: \"323234343434\"",
    "cause": null
  }
}
```

no `Content-Type` header makes it hard for machines to know how to process this  - i'm just seeing errors in my test suites due to this missing content type thing now, which makes me think this is a recently introduced thing (along with `Exception-Name:class` which i hadn't seen before now)

**Comment by kjw** [comment]
Yeah there is new exception handling for uncaught errors. Will improve that code to include content type.

**Comment by sckott** [comment]
thanks

**Comment by sckott** [comment]
any progress on this?
