### ISSUE TITLE
Any request failing then not failing, then failing again

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#173]
Seems like perhaps a problem with too much traffic for capacity?  

e.g., http://api.crossref.org/members/4443/works?filter=has-full-text%3Atrue 

I run that, doesn't work, run again, doesn’t work, run again, now works, run again, doesn't work, and so on

I would think it would be cached anyway, so why would repeated requests to the same URL resource work, then not work 2 seconds later?  Maybe there isn't any caching?

**Comment by jbborre** [comment]
We are seeing the same type of issue as well. Please let us know if there is any update on root cause.

**Comment by gbilder** [comment]
We've been really been struggling to handle increased load. We're in the process of refactoring the code and upgrading network/servers. I hope you start to see major improvements over the coming weeks.

Caching seems like it would be a bad idea for `list` results as part of the idea behind them is that they are always current and our members are *always* updating their metadata. . Having said that, we are looking to more aggressively caching singleton results.

**Comment by sckott** [comment]
> Caching seems like it would be a bad idea for list results as part of the idea behind them is that they are always current and our members are always updating their metadata. . Having said that, we are looking to more aggressively caching singleton results.

right, singletons make sense

though maybe caching list results for ~ 1 min or so would help decrease load for repeated requests to the same resource - but maybe even that risks not getting the most recent data?
