### ISSUE TITLE
Add ISBN as filter

### ISSUE THREAD

**Issue by gutknecht** [CrossRef/rest-api-doc#180]
Hi 

Would be great if you can add a filter for the isbn?

(It's not in alternative_id)

Christian

**Comment by kmeddings** [comment]
Hi - this has been added - filter=isbn:

It's different to ISSN however, in that ISBNs are formatted differently by different publishers, so the API isn't making any attempt to normalise them. You may need to fiddle with the format of your ISBN to get results.
