### ISSUE TITLE
API Specification in Accept Header returns 406

### ISSUE THREAD

**Issue by mtd91429** [CrossRef/rest-api-doc#181]
I submitted the following Hypertext Transfer Protocol:
Hypertext Transfer Protocol
    GET /works?query=S0065310113000066 HTTP/1.1\r\n
        [Expert Info (Chat/Sequence): GET /works?query=S0065310113000066 HTTP/1.1\r\n]
            [GET /works?query=S0065310113000066 HTTP/1.1\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Method: GET
        Request URI: /works?query=S0065310113000066
            Request URI Path: /works
            Request URI Query: query=S0065310113000066
                Request URI Query Parameter: query=S0065310113000066
        Request Version: HTTP/1.1
    Host: api.crossref.org\r\n
    User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0\r\n
    **Accept: application/vnd.crossref-api-message+json; version=1.0\r\n**
    Accept-Language: en-US,en;q=0.5\r\n
    Accept-Encoding: gzip, deflate\r\n
    Connection: keep-alive\r\n
    Pragma: no-cache\r\n
    Cache-Control: no-cache\r\n
    \r\n
    [Full request URI: http://api.crossref.org/works?query=S0065310113000066]
    [HTTP request 1/1]
    [Response in frame: 34]

And received the following response:
Hypertext Transfer Protocol
	HTTP/1.1 406 Not Acceptable\r\n
		[Expert Info (Chat/Sequence): HTTP/1.1 406 Not Acceptable\r\n]
			[HTTP/1.1 406 Not Acceptable\r\n]
			[Severity level: Chat]
			[Group: Sequence]
		Request Version: HTTP/1.1
		Status Code: 406
		Response Phrase: Not Acceptable
	Content-Type: text/plain\r\n
	Access-Control-Allow-Origin: *\r\n
	Access-Control-Allow-Headers: X-Requested-With\r\n
	Content-Length: 33\r\n
		[Content length: 33]
	Server: http-kit\r\n
	Date: Fri, 27 Jan 2017 19:23:50 GMT\r\n
	X-Rate-Limit-Limit: 50\r\n
	X-Rate-Limit-Interval: 1s\r\n
	Connection: close\r\n
	\r\n
	[HTTP response 1/1]
	[Time since request: 0.172224000 seconds]
	[Request in frame: 33]
	File Data: 33 bytes

Perhaps I'm not implementing this correctly? But this looks just like it is specified [here](https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#how-to-manage-api-versions)

**Comment by gbilder** [comment]
Sorry about delay in response . This seems to be working:

http://api.crossref.org/works?query=S0065310113000066

Note you can also use the `alternative-id` filter if you want to be more specific.

http://api.crossref.org/works?filter=alternative-id:S0065310113000066
