### ISSUE TITLE
license facet adds up to only ~26 million

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#182]
http://api.crossref.org/works?facet=license:*&rows=0 

adds up to ~26 million works, but 

http://api.crossref.org/works?rows=0

shows there are about 86 million works 

Does that mean about 60 million don't have licenses? If so, is there any work to get license information on those? 

Or is there some technical maybe Solr reason why only 26 million show up in count for faceting?

**Comment by sckott** [comment]
http://api.crossref.org/works?rows=0&filter=has-license:false shows about 62 million

curious though if those 62 million will get license info at some point

**Comment by kmeddings** [comment]
Hi - yes, we are encouraging all of our members to add license information. Some are not providing licenses at all at the moment, and others have not deposited them for all of their content. 
http://api.crossref.org/works?filter=has-license:false&facet=publisher-name:*&rows=0

It will take a while to get more complete coverage but we're working on it!
