### ISSUE TITLE
Can't seem to query a journal by either Print or Online ISSN

### ISSUE THREAD

**Issue by rossmounce** [CrossRef/rest-api-doc#183]
https://academic.oup.com/pch
Paediatrics & Child Health

Tried to get DOIs by querying the ISSN of the journal

Online ISSN: 1918-1485
Print ISSN: 1205-7088

```
#Online ISSN
wget 'http://api.crossref.org/journals/1918-1485/works?rows=100&sort=published&order=asc'
--2017-01-31 09:21:14--  http://api.crossref.org/journals/1918-1485/works?rows=100&sort=published&order=asc
Resolving api.crossref.org (api.crossref.org)... 208.254.38.72
Connecting to api.crossref.org (api.crossref.org)|208.254.38.72|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-31 09:21:14 ERROR 404: Not Found.

#Print ISSN
wget 'http://api.crossref.org/journals/1205-7088/works?rows=100&sort=published&order=asc'
--2017-01-31 09:21:28--  http://api.crossref.org/journals/1205-7088/works?rows=100&sort=published&order=asc
Resolving api.crossref.org (api.crossref.org)... 208.254.38.72
Connecting to api.crossref.org (api.crossref.org)|208.254.38.72|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-31 09:21:28 ERROR 404: Not Found.
```

Query by ISSN for all other OUP journals that have published content is working. I have checked them _all_

**Comment by kmeddings** [comment]
I can't find any DOIs for this journal that have been registered - looks like it's not in our system.

**Comment by rossmounce** [comment]
@kmeddings thanks.

I think CrossRef might want to take this up with OUP.
They are clearly displaying DOIs on each and every article landing page e.g.
https://academic.oup.com/pch/article/3/1/42/2660387/Tracking-the-emergence-of-a-suspected-new-human -> https://doi.org/10.1093/pch/3.1.42

Yet embarrassingly, not one of ANY of the DOIs visible on _any_ of the many articles of this journal have functional, registered, or resolvable DOIs.

A strange strange case. If OUP don't intend to register these DOIs could CrossRef please encourage them not to display 'fake', unregistered DOIs.

**Comment by gbilder** [comment]
Hi Ross. Sorry about the delay in response. As you have probably heard from us elsewhere, our support  is working with OUP to try to sort out these missing DOIs, etc. A lot of them were only discovered as they changed platforms. It looks like the example above DOI has since been registered.

`http://api.crossref.org/works/10.1093/pch/3.1.42`

However, the ISSN lookup still does not seem to be working for that journal:

`http://api.crossref.org/journals/1918-1485`

Which sounds like our problem, not OUP's.  Will investigate further.

**Comment by rossmounce** [comment]
@gbilder thanks for the comment. 

"A lot of them were only discovered as they changed platforms" ... my oh my. I didn't know that. Some problems were pre-existing (for how long I wonder!) and only came to light because of the platform change? Wow.

**Comment by kjw** [comment]
I'm closing this as it is not an issue with the API, but a member's metadata. I think everyone here knows how to get in contact with each other in the case of continued problems with OUP.
