### ISSUE TITLE
response delay is over 30 seconds

### ISSUE THREAD

**Issue by Slobug** [CrossRef/rest-api-doc#184]
hi,

on local machine the response delay is correct but on server, the response delay is over 30 seconds...
It's very long and I don't understand it.

after some tests, it's the delay of response of the api and not the traitment on the response.

someone has a solution or explication ?

Thanks !

**Comment by gbilder** [comment]
Sorry about this. Our API have been overloaded lately by a sharp increase in traffic. We are refactoring our code + upgrading our network and equipment to better handle the traffic. You should see improvements in the coming weeks.

**Comment by Slobug** [comment]
Thanks !
