### ISSUE TITLE
Update elsevier text mining URLS to https

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#185]
I haven't checked all but I can only assume that this applies to all their URLs: 

on submitting a URL with scheme `http` they give error 

> Request must be submitted via SSL Transport (i.e. https://)

Can Crossref update all elsevier URLs or does publisher have to do that?

All elsevier text mining URLs AFAIK are `http`

**Comment by ckoscher** [comment]
I only spot checked a few Elsevier DOIs.

We can modify our code to put in https for the URLs we copy from the 
text & data mining section (which elsevier deposits as http) to the 
iParadigm as-crawled section as https. We will be careful not to copy 
https  to httpss.

With the above caveat,  Elsevier can redeposit their T&DM URLs with 
https without any harm.

chuck

**Comment by sckott** [comment]
What % of works will that cover - for the _URLs we copy from the
text & data mining section_ ?

**Comment by kjw** [comment]
@ckoscher Did we update these?

**Comment by ckoscher** [comment]
Elsevier  decided to fix the http route (e.g. make it work), thereby eliminating the need to redeposit anything or for us to 'auto-convert' http to https in the metadata

**Comment by kjw** [comment]
OK, Elsevier URLs now working.
