### ISSUE TITLE
links to members/prefixes are broken

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#186]
e.g., <http://id.crossref.org/member/301> redirects to <http://data.crossref.org/member/301> - which doesn't exist, or perhaps only exists with certain authentication?  

perhaps just link to <http://api.crossref.org/members/301> instead?

**Comment by sckott** [comment]
same with prefixes <http://id.crossref.org/prefix/10.1080> / <http://data.crossref.org/prefix/10.1080>

**Comment by gbilder** [comment]
I think these are supposed to be blank nodes.

**Comment by kjw** [comment]
These are supposed to be blank nodes. We're actually removing the HTTP prefix from the values of these fields. This should have been completed for works responses but there may still be some found in other response types.

**Comment by kjw** [comment]
These fields no longer contain links, instead just the IDs themselves.
