### ISSUE TITLE
Book Subtitle appearing in Container Title

### ISSUE THREAD

**Issue by ldodds** [CrossRef/rest-api-doc#19]
I don't know whether this is an API or a metadata issue, but the following book has a title ("Pharmaceuticals and Care Products in the Environment) and a subtitle ("Scientific and Regulatory Issues"):

http://pubs.acs.org/isbn/9780841237391

If we fetch the metadata for a chapter in that book, then the `container-title` key includes both of those titles:

http://api.crossref.org/works/10.1021/bk-2001-0791.ch020

I'd suggest that `container-title` should only include the main title of the containers.

The third title is from the book series of which the book is a part.

**Comment by loupeck** [comment]
@kjw could you possibly give an update here?

**Comment by afandian** [comment]
Looking at this ticket 2 odd years later the metadata appears to have changed. @ldodds or @loupeck could you re-confirm that this is still happening with a current example?

**Comment by loupeck** [comment]
Hi there, you would need to contact Kudos directly as I no longer work for them :)

**Comment by jenniferlin15** [comment]
Looks like this has been resolved during a metadata update. Closing ticket.
