### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by maurei** [CrossRef/rest-api-doc#190]
https://api.crossref.org/works?query.title=superconductors&query.author=Kitaev&filter=from-pub-date:2009,until-pub-date:2009

{
status: "error",
message-type: "exception",
message-version: "1.0.0",
message: {
name: "class java.lang.NullPointerException",
description: "java.lang.NullPointerException",
message: null,
cause: null
}

-edit

Apparently this is not so easy to reproduce, sometimes the API does not throw this error.

**Comment by gbilder** [comment]
We've had a surge in traffic that has been taxing the API. Chances are you have hit us when the machines and/or network have been overloaded. We are in the process of refactoring the API and upgrading equipment. Should clear up these kinds of errors.
