### ISSUE TITLE
Url-requests not working 

### ISSUE THREAD

**Issue by MartinDobisch** [CrossRef/rest-api-doc#192]
The URL-Requests for DOI-Numbers stopped working yesterday around 3pm.

requests like:
https://api.crossref.org/works/10.1103/PhysRevE.75.066701
lead to

{"status":"error","message-type":"exception","message-version":"1.0.0","message":{"name":"class com.mongodb.MongoException$Network","description":"com.mongodb.MongoException$Network: can't call something : cr3\/172.20.1.22:27017\/crossref","message":"can't call something : cr3\/172.20.1.22:27017\/crossref","cause":{"name":"class java.io.IOException","description":"java.io.IOException: couldn't connect to [cr3\/172.20.1.22:27017] bc:java.net.ConnectException: Connection refused (Connection refused)","message":"couldn't connect to [cr3\/172.20.1.22:27017] bc:java.net.ConnectException: Connection refused (Connection refused)"}}}

looks like the connection to your database died.

**Comment by MartinDobisch** [comment]
Nevermind, it just started working again.

**Comment by thomasaarholt** [comment]
@MartinDobisch Please close this, then.
