### ISSUE TITLE
API doesn't return results for PLOS Genetics, ISSN 1553-7390

### ISSUE THREAD

**Issue by daisieh** [CrossRef/rest-api-doc#194]
Even though a search for ISSN 1553-7390 on the crossref.org site returns results for PLOS Genetics, when I try to run the search via the api (`http://api.crossref.org/journals/1755-098X/works`), I get an error:

```
{"status":"error","message-type":"exception","message-version":"1.0.0","message":{"name":"class java.lang.IllegalArgumentException","description":"java.lang.IllegalArgumentException: Vector arg to map conj must be a pair","message":"Vector arg to map conj must be a pair","cause":null}}
```

This doesn't happen with other journals, like `http://api.crossref.org/journals/1755-098X/works`.

**Comment by daisieh** [comment]
It worked fine for 1553-7390 as of April 8.

**Comment by kmeddings** [comment]
Hi - we've been upgrading the API for the last 24 hours. http://api.crossref.org/works/10.1007/s10479-017-2480-9 works for me now. It may be that you hit a glitch while we were moving things around. Can you try again?

**Comment by dhimmel** [comment]
@kmeddings currently getting a similar issue for `10.1515/metgen-2016-0001` as documented in https://github.com/greenelab/deep-review/pull/304#issuecomment-293262346.

The metadata shows up on the [web search](https://search.crossref.org/?q=10.1515%2Fmetgen-2016-0001) but not via its API call: https://api.crossref.org/works/10.1515/metgen-2016-0001 which results in:

```json
{
  "status": "error",
  "message-type": "exception",
  "message-version": "1.0.0",
  "message": {
    "name": "class java.lang.IllegalArgumentException",
    "description": "java.lang.IllegalArgumentException: Vector arg to map conj must be a pair",
    "message": "Vector arg to map conj must be a pair",
    "cause": null
  }
}
```

Furthermore, DOI content negotiation is failing with `No acceptable resource available.`:

```sh
curl --location \
  --header "Accept: application/vnd.citationstycation/rdf+xml" \
  https://doi.org/10.1515/metgen-2016-0001
```

**Comment by danielopitz** [comment]
Seems to be the same problem as in #195

**Comment by dhimmel** [comment]
On the related issue #195, @gbilder commented:

> This was due to an incremental update that broke the query parameter. Has been fixed.
 
@daisieh, I'd check to see if your issue is resolved.

Regarding `10.1515/metgen-2016-0001`: The Crossref API call (https://api.crossref.org/works/10.1515/metgen-2016-0001) now works but the DOI content negotiation still returns `No acceptable resource available.`. @gbilder any ideas? Should I open a new issue?

**Comment by dhimmel** [comment]
Update: turns out the DOI content negotiation that I'm interested in (`application/vnd.citationstyles.csl+json`) now works:

```sh
curl --location \
  --header "Accept: application/vnd.citationstyles.csl+json" \
  https://doi.org/10.1515/metgen-2016-0001
```

So from my end, we're good.

**Comment by daisieh** [comment]
Looks good to me now, thanks!
