### ISSUE TITLE
IllegalArgumentException: Vector arg to map conj must be a pair

### ISSUE THREAD

**Issue by JanneSeppanen** [CrossRef/rest-api-doc#195]
Above error is response to this query:
http://api.crossref.org/works?query.author=Alava&filter=from-created-date:2017-04-01&rows=100

Same query with different author name works.

EDIT: seems to be either fixed or transient; the above query works now OK on April 12th, 22:18 Finnish time

**Comment by danielopitz** [comment]
This happens to a lot of queries, seemingly randomly. Sometimes removing the rows parameter helps, but makes the data unusable.

**Comment by dhimmel** [comment]
Here's the full JSON response:

```json
{
  "status":"error",
  "message-type":"exception",
  "message-version":"1.0.0",
  "message":{
    "name":"class java.lang.IllegalArgumentException",
    "description":"java.lang.IllegalArgumentException: Vector arg to map conj must be a pair",
    "message":"Vector arg to map conj must be a pair",
    "cause":null
  }
}
```

Confirming that I'm getting the error for the above query. Note that the error is temperamental and only happens some of the time. See https://github.com/CrossRef/rest-api-doc/issues/194#issuecomment-293305493 for a more concentrated instance of this pathology.

**Comment by danielopitz** [comment]
I haven't checked yet if the error happens only temporarily, but I get it for roughly 1/6 of all queries.

**Comment by gbilder** [comment]
This was due to an incremental update that broke the query parameter. Has been fixed.
