### ISSUE TITLE
filters need updating perhaps

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#198]
https://api.crossref.org/works?filter=publisher-name%3aElsevier%20BV%2ctype%3ajournal-article&rows=0

gives 

message: "Filter publisher-name specified but there is no such filter for this route. Valid filters for this route are: has-assertion, from-print-pub-date, until-deposit-date, from-accepted-date, has-authenticated-orcid, from-created-date, issn, until-online-pub-date, group-title, full-text.application, until-created-date, license.version, from-deposit-date, has-abstract, has-event, funder, assertion-group, from-online-pub-date, from-issued-date, directory, content-domain, license.url, from-index-date, full-text.version, full-text.type, until-posted-date, has-orcid, has-archive, type, is-update, until-event-start-date, update-type, from-pub-date, has-license, funder-doi-asserted-by, isbn, has-full-text, doi, orcid, has-content-domain, prefix, until-event-end-date, has-funder, award.funder, clinical-trial-number, member, has-domain-restriction, until-accepted-date, container-title, license.delay, from-posted-date, has-affiliation, from-update-date, has-award, until-print-pub-date, from-event-start-date, has-funder-doi, until-index-date, has-update, until-update-date, until-issued-date, until-pub-date, award.number, has-references, type-name, alternative-id, archive, updates, category-name, has-clinical-trial-number, assertion, article-number, has-update-policy, from-event-end-date"

for example, `publisher-name` is listed in the table of filters https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#filter-names but is apparently not available as a filter 

can that table be update please, or is there a api route to get avaialble. filters

**Comment by gbilder** [comment]
Sorry about this. The publisher-name filter got borked in a recent update of the index. We are in the process of reindexing to fix this problem. Should be cleared up in a few days. Will update here.

**Comment by sckott** [comment]
thx

**Comment by kjw** [comment]
Publisher name hasn't been a filter. The way to filter on a member is to use member IDs in the filter. The issue with filtering on publisher name would be the potential fuzziness of the field.

**Comment by sckott** [comment]
thx @kjw
