### ISSUE TITLE
Incorrect Citation Count (is-referenced-by-count)

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#199]
For many articles, the citation count field ("is-referenced-by-count") is returned as 0, while it is actually reported non-zero by the publisher. 

Example: 
Zero citation count reported on CrossRef: 
https://api.crossref.org/v1/works/http://dx.doi.org/10.1002/smj.4250140206

Non-zero citation count reported by the publisher: 
http://onlinelibrary.wiley.com/doi/10.1002/smj.4250140206/full?refreshCitedByCounter=true

I know this is probably due to the fact that some publisher (e.g. Wiley) do not give permission to release this field. Is there anyway to know if the reported citation is really zero or just not reported?

It is messing up with all my analysis. Any workaround idea?

**Comment by kmeddings** [comment]
Hi-

Sorry about this. With the latest API release we have some gaps in the metadata that we need to backfill. If you look at the deposit the count is correct-
https://api.crossref.org/works/http://dx.doi.org/10.1002/smj.4250140206/transform/application/vnd.crossref.unixsd+xml

It's not related to publishers who don't make their references public - the cited-by count still counts these, we just don't display the actual list of refs.

I'll try and get an ETA on a re-index that will pick these up.

**Comment by moqri** [comment]
Awesome, please do let us know here when the re-index is ready.

Meanwhile, is there any way I can get the response that have "citedby-count"  in a json format?

**Comment by gbilder** [comment]
It citedby count is included in the json of an imminent new release of the API. You can test it here:

https://api.crossref.org/works/10.1002/smj.4250140206

See the `is-referenced-by-count` in the returned json.

Note the number is still incorrectly listed as zero- but this should clear up as the data is reindexed over the next week or so.

**Comment by moqri** [comment]
It seem this issue has reappeared and worsen!

Now even xml version the citation count is incorrectly 0:

https://api.crossref.org/works/http://dx.doi.org/10.1002/smj.4250140206/transform/application/vnd.crossref.unixsd+xml

**Comment by ckoscher** [comment]
working it.

**Comment by kmeddings** [comment]
These have been corrected in the XML and will be updated in the JSON over the next few days.

**Comment by moqri** [comment]
Awesome, looking forward to it!

By the way, the same issue exists for some Open Access articles as well: 
https://api.crossref.org/v1/works/http://dx.doi.org/10.1590/s1517-83822011000200034
