### ISSUE TITLE
API calls oftern return 503 or 504 errors

### ISSUE THREAD

**Issue by tobiasdiez** [CrossRef/rest-api-doc#201]
We often get a 503 or 504 response when using the API node http://data.crossref.org and trying to get the information directly as bibtex (header `application/x-bibtex`; I didn't try other formats).

For example,
> HTTP response code: 504 for URL: http://data.crossref.org/10.1021%2Fjo0010835
> HTTP response code: 503 for URL: http://data.crossref.org/10.1007%2Fs10589-016-9858-5

The problem occurs from different systems (different users in different countries and also from travic build server).

The code used to access the API can be found at https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java#L55.

**Comment by kjw** [comment]
504 and 503 are unfortunately response codes that come back from our load balancer when the service is under heavy load. We are working to improve the availability of the service generally.
