### ISSUE TITLE
Query returns incorrect results.

### ISSUE THREAD

**Issue by sujdan** [CrossRef/rest-api-doc#203]
https://api.crossref.org/works?query.container-title=Engineering+Technology&rows=1000&cursor=*
[10908-1.txt](https://github.com/CrossRef/rest-api-doc/files/980159/10908-1.txt)

**Comment by kjw** [comment]
If you're trying to get results that are limited to a particular publication, it is best to use an ISSN filter, or filter on the exact name of the publication. The `query.container-title` parameter will perform a fuzzy match on the journal title. For example:

https://api.crossref.org/works?filter=issn:1234-5678
