### ISSUE TITLE
Filter Name - "publisher-name" not available anymore ?

### ISSUE THREAD

**Issue by vineetdpnd** [CrossRef/rest-api-doc#204]
When i try the following query :- 

http://api.crossref.org/works?query=medicine&filter=publisher-name:elsevier&facet=t&rows=30

I get the following JSON response :- 

{"status":"failed","message-type":"validation-failure","message":[{"type":"filter-not-available","value":"publisher-name","message":"Filter publisher-name specified but there is no such filter for this route. Valid filters for this route are: has-assertion, from-print-pub-date, until-deposit-date, from-accepted-date, has-authenticated-orcid, from-created-date, relation.object, issn, until-online-pub-date, group-title, full-text.application, until-created-date, license.version, from-deposit-date, has-abstract, has-event, funder, assertion-group, from-online-pub-date, from-issued-date, directory, content-domain, license.url, from-index-date, full-text.version, full-text.type, until-posted-date, has-orcid, has-archive, type, is-update, until-event-start-date, update-type, from-pub-date, has-license, funder-doi-asserted-by, isbn, has-full-text, doi, orcid, has-content-domain, prefix, until-event-end-date, has-funder, award.funder, clinical-trial-number, member, has-domain-restriction, until-accepted-date, container-title, license.delay, from-posted-date, has-affiliation, from-update-date, has-award, until-print-pub-date, from-event-start-date, has-funder-doi, until-index-date, has-update, until-update-date, until-issued-date, until-pub-date, award.number, has-references, type-name, has-relation, alternative-id, archive, relation.type, updates, relation.object-type, category-name, has-clinical-trial-number, assertion, article-number, has-update-policy, from-event-end-date"}]}

This query used to work properly earlier. Has the filter **publisher-name** been removed ? 

As per the crossref api documentation , it is still there.

Please help.

Thanks.

**Comment by kmeddings** [comment]
Please use http://api.crossref.org/members/78/works?query=medicine&rows=30, as the publisher-name filter should have been deprecated.
