### ISSUE TITLE
update-to field purpose / content

### ISSUE THREAD

**Issue by danielopitz** [CrossRef/rest-api-doc#205]
I'm wondering what the `update-to` field is for. I've seen it in several datasets and mostly the DOI is listed as corrected part of the dataset.

Is the field in `update-to` the now correct one or is it the corresponding field in the dataset? In following example a DOI was corrected and it is not obvious which one is correct now (apparently, both work with `dx.doi.org`). Please clarify.

```
"update-to": [
  {
    "updated": {
      "date-time": "2015-04-20T00:00:00Z",
      "date-parts": [
        [
          2015,
          4,
          20
        ]
      ],
      "timestamp": 1429488000000
    },
    "type": "correction",
    "label": "Correction",
    "DOI": "10.2514/1.j053033"
  }
], 
"DOI": "10.2514/1.j054256"```

**Comment by afandian** [comment]
This is for Crossmark, which indicates updates such as corrections, retractions etc. 

For example, this (demo) DOI: https://doi.org/10.5555/12345678 was retracted by this DOI: https://doi.org/10.5555/24242424x . If you click on the Crossmark dialog on the former, you will see words to that effect.

If you look in the API for http://api.crossref.org/works/10.5555/24242424x you will see that it a retraction that updates 10.5555/12345678 .

**Comment by danielopitz** [comment]
Thank you for the clarification!
