### ISSUE TITLE
Citation count fields / citations vs. references

### ISSUE THREAD

**Issue by danielopitz** [CrossRef/rest-api-doc#206]
Another question regarding some fields. It is not quite clear which one is which:

- `cited_count` -> how many other articles cited this one?
- `citing_count` -> how many other articles this one cited?
- `cites_count` -> perhaps the sum of the other ones? or is it a typo?
- `is_cited_by_count` -> same as `cited_count`?

What is the difference between citations and references in CrossRef data?

Some clarification would be very welcomed. Are there any plans to bring [api_format.md](https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md) up to date?

Thanks!

**Comment by kmeddings** [comment]
Hi - we've changed this to be clearer in the recent release and now have just two fields:
is-referenced-by-count
reference-count
We will update the documentation asasp.
