### ISSUE TITLE
Documentation is incomplete: no mention of 'reference' element

### ISSUE THREAD

**Issue by GuyYeates** [CrossRef/rest-api-doc#207]
The documentation for the Crossref api at https://github.com/Crossref/rest-api-doc/blob/master/api_format.md  appears incomplete. After running requests (e.g., https://api.crossref.org/works/10.1002/ird.2017) I've got back works records with an element called "reference" but there's no mention of it in the documentation.

**Comment by kmeddings** [comment]
Karl can you update with the new field names?

**Comment by kjw** [comment]
We don't actually document the response format at the moment.

**Comment by kmeddings** [comment]
This is now documented.
