### ISSUE TITLE
How to search of works records using an ISBN

### ISSUE THREAD

**Issue by GuyYeates** [CrossRef/rest-api-doc#210]
I'm trying to search for records with a particular ISBN ("9781780648903"). A search using the DOI  as follows "http://api.crossref.org/works/10.1079/9781780648903.0000"  returns the correct 'works' record. 

So far I've tried the following search variations:

1) http://api.crossref.org/works?query=9781780648903       
    >0 results

2) http://api.crossref.org/types/book/works?query=9781780648903 
    >0 results

3) http://api.crossref.org/types/book/works?query=http://id.crossref.org/isbn/9781780648903  
    >70 results,     highest "score" is 15.86,     target works record is not present

4) http://api.crossref.org/types/book/works?query.bibliographic=http://id.crossref.org/isbn/9781780648903   
   >67 results,    highest "score is 16.70,    target works record is not present

4) http://api.crossref.org/types/book/works?query.title=Climate+change+and+cotton+production+in+modern+farming+systems&query.bibliographic=http://id.crossref.org/isbn/9781780648903   
    >4 results,     highest "score is 17.75,    target works record is not present

Any suggestions? 

thanks]
Guy

p.s.
I note that the description of the "query.bibliographic" field doesn't clearly specify which properties are included - is ISBN present?

**Comment by denizk** [comment]
Hi, this seems to have been added as per #180 

In your example: http://api.crossref.org/types/book/works?filter=isbn:9781780648903

**Comment by GuyYeates** [comment]
Apologies I missed that one.

Guy

Guy Yeates
( x2265 )

**Comment by kmeddings** [comment]
ISBN should be included in "query.bibliographic", however this particular ISBN doesn't seem to be present in the JSON. Assigning to @ckoscher to see if it can be pushed through.

**Comment by ckoscher** [comment]
There is only on DOI with this ISBN, it was pushed to the indexer on May12.  Karl will have to investigate why a search does not work.

see:
http://doi.crossref.org/search/doi?pid=ckoscher@crossref.org&format=unixsd&doi=10.1079/9781780648903.0000

**Comment by gbilder** [comment]
Once the data was pushed through, the following query works: 

http://api.crossref.org/types/book/works?filter=isbn:9781780648903

This does not work, but should:

http://api.crossref.org/works?query=9781780648903

**Comment by kjw** [comment]
We now have an `isbn` filter and the data is available, however, we were not normalizing ISBNs in our index or in queries. We are now normalizing them, however re-indexing is taking place to support this. Should all be good by next week.

**Comment by kjw** [comment]
Same as #250
