### ISSUE TITLE
"http://id.crossref.org/isbn/" as result in ISBN field for doi-requests.

### ISSUE THREAD

**Issue by MartinDobisch** [CrossRef/rest-api-doc#214]
https://api.crossref.org/works/10.1007/978-3-662-48881-2
https://api.crossref.org/works/10.1007/978-981-10-0959-4
and other return for ISBN:
ISBN	
0	"http://id.crossref.org/isbn/"
1	"http://id.crossref.org/isbn/"

Greetings

**Comment by kmeddings** [comment]
@kjw this work has two ISBNs. Why aren't they showing?

**Comment by 5j9** [comment]
For me they both ISBNs are showing, but  from time to time I receive an invalid value of `"ISBN":["http:\/\/id.crossref.org\/isbn\/","http:\/\/id.crossref.org\/isbn\/"]`.

To reproduce the issue, goto https://api.crossref.org/works/10.1007/978-3-662-48881-2 and refresh a few times.

**Comment by MartinDobisch** [comment]
Why would the "http:..." be included in the ISBN-field anyway? 
There is no URL part for ISSN.

**Comment by kjw** [comment]
We're going to remove the URL prefixes for ISSNs and ISBNs.

**Comment by kjw** [comment]
The ISBNs now appear, we no longer display them in URL form.
