### ISSUE TITLE
Error in CSL content negotiation when elements are empty 

### ISSUE THREAD

**Issue by gbilder** [CrossRef/rest-api-doc#215]
(Reported via labs email account)

This error appears for any type of record we try. 

"error while formatting: Cannot read property 'length' of null"

We are trying to troubleshoot how we can correct our records so that we can use the tool and others can gather our citation from it. Is there anything that you can tell is incorrect?

Examples of our DOIs: 
10.1575/1912/441
10.1575/1912/8222
10.1575/1912/bco-dmo.652124

**Comment by kjw** [comment]
Can't reproduce. Requesting styled citations for these DOIs is working. Possible that there is detail missing from the bug report, or perhaps the problem lies with upstream tooling - i.e. whatever is reading the bibtex for this user.
