### ISSUE TITLE
list journals is limited to 1000 and does not support cursor

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#220]
I am trying to get a list of all journals using http://api.crossref.org/journals but it seems the result is limited to 1000 and the cursor is not enabled for this command.

Any suggestions or alternativea?

**Comment by danielopitz** [comment]
You can use offset to get results 1-11.000 (max offset is 10.000 as of now). Using offset larger than 10.000 will set it back to 10.000. 

The problem of offset being max 10.000 and cursors being only available for works was already mentioned in #179 and #208. The fix seems to be implemented in the code already (see recent commits in the CrossRef/cayenne repository, but the code wasn't deployed yet. It will be possible to use offset > 10.000 for endpoints other than works.
