### ISSUE TITLE
HTTPS on Content Negotiation not working.

### ISSUE THREAD

**Issue by gbilder** [CrossRef/rest-api-doc#221]
Content negotiation using` https://doi.org/{DOI}` is redirecting to `http://data.crossref.org/{DOI}` (e.g. HTTPS->HTTP)

See, for example:

`curl -X GET https://doi.org/10.1371/journal.pbio.1002605 -H 'accept: application/vnd.citationstyles.csl+json' -H 'cache-control: no-cache' -v`

**Comment by larsgw** [comment]
This seems to be fixed now, is that correct?

**Comment by kjw** [comment]
Now fixed.
