### ISSUE TITLE
"reference-count":0 for many articles

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#228]
Example: 

API: http://api.crossref.org/works/10.1001/.399
Article: http://jamanetwork.com/journals/jamainternalmedicine/fullarticle/409883

It would be great if you could distinguish between "an article really not having any reference" and "the reference data is not available" . For example, you can remove the reference-count field when the data is not available

**Comment by kmeddings** [comment]
The number actually indicates whether the publisher has deposited any references with us, regardless of whether they are public or not. For publishers who have not made references public but have deposited them, you will see the count but not the refs themselves. 

JAMA does not currently deposit references.
