### ISSUE TITLE
Extracting all is-preprint-of relations in the database

### ISSUE THREAD

**Issue by dhimmel** [CrossRef/rest-api-doc#229]
@cgreene and I chatted with @jenniferlin15 yesterday about the exciting new features Crossref is developing and how they relate to the preprint ecosystem. One question that came up is whether we could find all instances of when preprints had gone on to be published in a journal.

For example, the works API call for https://api.crossref.org/works/10.1101/011569 (a bioRxiv preprint) returns the following under `message`:

```json
"relation": {
    "is-preprint-of": [
        {
            "id-type": "doi",
            "id": "10.1371/journal.pcbi.1004259",
            "asserted-by": "subject"
        }
    ]
}
```

Is there a way to get all works that have an `is-preprint-of` relation? I'm envisioning the use case where we'd like to extract all preprint DOI to journal DOI pairs.

**Comment by jenniferlin15** [comment]
Would be great to see filters for relations, @kmeddings and @kjw. This will be incredibly useful in surfacing out the links to other collections of resources that are of interest to various groups. (for example of recommended relations: https://support.crossref.org/hc/en-us/articles/214357426-Relationships-between-DOIs-and-other-objects

**Comment by kjw** [comment]
Yes there is:

    https://api.crossref.org/works?filter=relation.type:is-preprint-of

Enjoy :-)
