### ISSUE TITLE
until-pub-date filter

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#230]
http://api.crossref.org/types/journal-article/works?filter=from-pub-date:2016,until-pub-date:2016
returns 3,149,319 items
http://api.crossref.org/types/journal-article/works?filter=from-pub-date:2016,until-pub-date:2016-12-30
returns 2,583,015 items

**Comment by jenniferlin15** [comment]
Hi, publishers deposit pub dates with a year designation or any combination of year/month/date. If you specify to the level of month or date in the query, please include all dates belonging to that year. For example, the following query returns the full record list (3.1+ million): http://api.crossref.org/types/journal-article/works?filter=from-pub-date:2016,until-pub-date:2016-12-31 . This query does as well: http://api.crossref.org/types/journal-article/works?filter=from-pub-date:2016,until-pub-date:2016-12 .

**Comment by moqri** [comment]
Thanks @jenniferlin15 
Could you also clarify what happens if, for an article, one of the print or online publish date is after the until-pub-date and the other one is before the until-pub-date? Do you use the earliest of the two published date, or print date, or online date to compare against the filter?

**Comment by jenniferlin15** [comment]
Filter is using either print date or online date, whichever is earliest. Please note you can to further specify the query by using the following: from-print-pub-date, until-print-pub-date, from-online-pub-date, until-online-pub-date. 
Hope this helps!

**Comment by moqri** [comment]
It seems not there is more to the until-pub-date than only filtering based on " either print date or online date, whichever is earliest"

I get some articles that have only a print-online-date and the date is after my filter but they still show up in the results.

Example: 
https://api.crossref.org/journals/2088-5334/works?filter=from-pub-date:2015,until-pub-date:2015&rows=1&offset=68
