### ISSUE TITLE
Content negotiation returning 200 OK, but with no content

### ISSUE THREAD

**Issue by gbilder** [CrossRef/rest-api-doc#231]
(sent via labs)

I have noticed a problem with the DOI content negotiation service that has started happening in the last few days. When attempting to retrieve CrossRef UnixrefXML for a DOI the response contains no content. The response code is 200 OK as if the request was successful but the content length is 0 and response body is empty.
 
The problem can be reproduced with the following command as specified in the DOI Content Negotiation documentation.
curl -vL -H "Accept: application/vnd.crossref.unixref+xml;q=1, application/rdf+xml;q=0.5" https://doi.org/10.1016/j.bbamem.2017.03.024
 
The response specifies the content type as application/vnd.crossref.unixref+xml but has no actual content.
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: X-Requested-With, Accept, Accept-Encoding, Accept-Charset, Accept-Language, Accept-Ranges, Cache-Control
< Access-Control-Expose-Headers: Link
< Link: <http://dx.doi.org/10.1016/j.bbamem.2017.03.024>; rel="canonical", <http://api.elsevier.com/content/article/PII:S0005273617301086?httpAccept=text/plain>; version="vor"; type="text/plain"; rel="item", <http://api.elsevier.com/content/article/PII:S0005273617301086?httpAccept=text/xml>; version="vor"; type="text/xml"; rel="item", <http://www.elsevier.com/tdm/userlicense/1.0/>; version="tdm"; rel="license"
< Content-Type: application/vnd.crossref.unixref+xml
< Content-Length: 0
< Server: http-kit
< Date: Mon, 12 Jun 2017 14:44:20 GMT
< X-Rate-Limit-Limit: 50
< X-Rate-Limit-Interval: 1s
< Connection: close
 
I have tried this with multiple CrossRef DOIs and the behaviour is the same.

**Comment by kjw** [comment]
@ckoscher Looks like the upstream for retrieving unixref is returning a 200 and empty body:

    curl -i "http://doi.crossref.org/search/doi?pid=cnproxy@crossref.org&format=unixref&doi=10.1016/j.bbamem.2017.03.024"

Returns 200, no content. Can you investigate?

@gbilder A workaround for now is to use unixsd instead of unixref:

    curl -vL -H "Accept: application/vnd.crossref.unixsd+xml;q=1, application/rdf+xml;q=0.5" https://doi.org/10.1016/j.bbamem.2017.03.024

**Comment by ckoscher** [comment]
Fix is being deployed now.

**Comment by gbilder** [comment]
Above all seems to be working now.

**Comment by mpaluch** [comment]
Verified working. Thanks.
