### ISSUE TITLE
Get updates for specific DOI

### ISSUE THREAD

**Issue by XavRsl** [CrossRef/rest-api-doc#234]
Hello,
I'm trying to get updates (Retraction, Erratum, ...) on a particular paper. The API gives me the possibility to filter all articles of a given journal that have updates, but I can't figure out how to get updates only for one paper. 

Thanks.

**Comment by afandian** [comment]
This query is "show me things that update 10.5555/12345678":

http://api.crossref.org/works?filter=updates:10.5555/12345678

**Comment by XavRsl** [comment]
That's great, thanks @afandian !
Is there any way I could pass a long list of DOIs to get all their updates ?

**Comment by gbilder** [comment]
Multiples of the same filter performs an `or` query. So...

`http://api.crossref.org/works?filter=updates:10.5555/12345678,updates:10.1016/j.ebiom.2016.09.008`

BTW- Multiples of different filters do an `and` query
