### ISSUE TITLE
Calling /works for ISSN 0021-9258 always returns a 429

### ISSUE THREAD

**Issue by neil-mehta** [CrossRef/rest-api-doc#237]
When calling /works for ISSN 0021-9258 always returns a 429. 
Other ISSN for this publisher return successfully. 
When calling /works without the cursor, the call returns successfully. 

Request:
http://api.crossref.org/journals/0021-9258/works?rows=1000&cursor=%2A&filter=type%3Ajournal-article%2Cfrom-pub-date%3A2010-01-01

Response:
<html><body><h1>429 Too Many Requests</h1>
You have sent too many requests in a given amount of time.
</body></html>

Thanks,
Neil
nmehta@highwire.org

**Comment by jenniferlin15** [comment]
Strange - may be intermittent? I just tried it and successfully received
the results. Can you specify when you made the call(s), Neil? We might be
able to dig into log files.

**Comment by iv-build-acct** [comment]
Thanks for the quick reply Jennifer!

We have been trying for the last hour. 
(10-11 AM PST Jun 29)

Thanks again!

**Comment by jenniferlin15** [comment]
Thanks for the time window. @kjw or @kmeddings may request more info when digging into issue. But this is great to go on for now. Thanks, Neil!

**Comment by kjw** [comment]
@ckoscher This is the rate limit error from haproxy. Are high wire hitting a rate limit or is there an issue with how the rate limit is applied to some URLs?

**Comment by ppolischuk** [comment]
Going to close this given the nature of issues like this. Please let us know if you are still experiencing problems and we can continue to investigate.
