### ISSUE TITLE
Inconsistent character encoding in responses 

### ISSUE THREAD

**Issue by gbilder** [CrossRef/rest-api-doc#238]
(submitted via labs)

we have been receiving some inconsistent responses when sending requests to "http://dx.doi.org/" using the header "Accept: application/vnd.crossref.unixref+xml". It seems that some responses will return the correct Latin-1 accented characters (eg. á, ç, and é), while other responses for the same DOI will return "?" in their place. This has led to us creating entries in our database such as Linguam?tica.

Here is an example request which reveals this issue:
curl -L -H "Accept: application/vnd.crossref.unixref+xml" http://dx.doi.org/10.21814/lm.9.1.241

**Comment by gbilder** [comment]
have verified above example returns different character encodings at different times.

**Comment by kjw** [comment]
@ckoscher These requests are passed on to the DOI look up at `doi.crossref.org` - can you take a look?

**Comment by agilmartin** [comment]
This has been fixed and will be deployed later today (July 5).

**Comment by agilmartin** [comment]
The fix has been deployed.
