### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by Daniel-Mietchen** [CrossRef/rest-api-doc#239]
given that the API is exposing licensing information, I find it odd that
- this repo does not have a license
- the licensing of the metadata is not clarified &mdash; I think I read CC0 somewhere but can't find that right now

**Comment by gbilder** [comment]
Good point that the documentation itself has no license info. Have added CC-BY 4.0 both to API documentation text and in standard LICENSE file.

Metadata licensing has [been documented in the API doc](https://github.com/CrossRef/rest-api-doc#meta
) itself. 


Our code is generally licensed MIT, but each repo should have that stated explicitly.
