### ISSUE TITLE
500 Internal Server Error/NullPointerException in bibtex generation

### ISSUE THREAD

**Issue by shenker** [CrossRef/rest-api-doc#240]
`curl -LH "Accept: application/x-bibtex" http://data.crossref.org/10.1101/037689`
gives
`{"status":"error","message-type":"exception","message-version":"1.0.0","message":{"name":"class java.lang.NullPointerException","description":"java.lang.NullPointerException","message":null,"cause":null}}`
(and a 500 status) while `curl -LH "Accept: application/vnd.citationstyles.csl+json" http://data.crossref.org/10.1101/037689` successfully returns a JSON document.

Requesting other citation styles at `https://search.crossref.org/?q=10.1101%2F037689#` (via the “Actions” menu), e.g., MLA, Chicago, all work... bibtex is the only one that shows up blank.

This is the only DOI I've found with this problem (so far).

**Comment by kjw** [comment]
Fixed by https://github.com/CrossRef/cayenne/commit/68a8f3d055741d9e837269faa5367247c6f568e2
