### ISSUE TITLE
Intermittent "Direct buffer memory" error on /works endpoint

### ISSUE THREAD

**Issue by thatjohnmartin** [CrossRef/rest-api-doc#241]
Hi there,

We're experiencing a strange error response intermittently (4 out of 20 attempts on the most recent test) from a `/works` URL.

Here is an example:

http://api.crossref.org/journals/0012-1797/works?cursor=%2A&rows=1000&filter=type%3Ajournal-article%2Cfrom-pub-date%3A2013-01-01

Let me know if I can provide more info.

Thanks,

John

**Comment by kmeddings** [comment]
I think this may be similar to an issue raised by another user:

In order to replicate the error it is necessary to use the cursor pagination or just refresh the same URL many times. You will see “Direct buffer memory” if you do this in the browser, what it is an error 500 (Internal Server Error) in the response.
 
This URL is what I used to cause the error. It doesn’t seem to happen if the ‘rows’ setting is quite low.
 
http://api.crossref.org/works?filter=from-update-date:2017-06-23,until-update-date:2017-06-23&rows=1000&cursor=*

**Comment by thatjohnmartin** [comment]
That sounds exactly like what we're experiencing.

So are you suggesting that by lowering the rows value and doing more requests that this will stop happening?

**Comment by kjw** [comment]
@ckoscher Can we please increase the heap size for the cursor-handling API instance?

**Comment by ckoscher** [comment]
svc11f has been increased to Xmx 8G (was the default of 512M)

**Comment by ckoscher** [comment]
done

**Comment by unoexperto** [comment]
Guys, I see this error regularly. At least couple times per week.

**Comment by unoexperto** [comment]
@ckoscher @kjw Guys, could you please re-open this ? It happens to me daily.

**Comment by denizk** [comment]
Same here, can't deep paginate through more than 450k of 8M hits when this error pops up.

**Comment by ifarley** [comment]
I have another report of this issue into support (ticket for internal reference: 137334).

**Comment by ifarley** [comment]
Here's another one into support (internal Zendesk ticket: 137364). This one has some samples for us, which I'll share with you via Slack @ppolischuk.

**Comment by ifarley** [comment]
Kirsty's example from 12 July 2017 is getting a "direct buffer memory" error today too: http://api.crossref.org/works?filter=from-update-date:2017-06-23,until-update-date:2017-06-23&rows=1000&cursor=*

**Comment by benjamincrary** [comment]
I'm experiencing similar issues with implementing my query in R (lib httr). I tried to break up my 2010-2019 query by year with rows=500 and had error 500 returned. 

query structure: 
#where year is equal to 2010:2019
httr::GET(paste0("https://api.crossref.org/v1.0/works?query=eDNA+Environmental_DNA&filter=from-pub-date:", year, "-01,until-pub-date:", year, "-12,type:journal-article&rows=500&cursor=*"))
      
#example for 2010 
httr::GET("https://api.crossref.org/v1.0/works?query=eDNA+Environmental_DNA&filter=from-pub-date:2010-01,until-pub-date:2010-12,type:journal-article&rows=5000&cursor=*")
 

Reducing rows to 100 helps, but the error is returning more frequently around 180 of 398 pages for year =2010. 

If the system can support it, I may try to iterate through my time series in 6-month chunks do reduce the number of pages required. Please advise. 

Thanks, 
Ben

**Comment by ifarley** [comment]
Another report from one of our Plus subscribers (Zendesk ticket 137916) that they are receiving 500 errors. Not yet sure the connection between these errors. I have requested example calls.

**Comment by ppolischuk** [comment]
We've adjusted some memory parameters in Cayenne. The REST API seems to be performing better from what we can see, so please let us know if you are still seeing the same types of errors. Thanks.
