### ISSUE TITLE
Bibtex capitalization protection

### ISSUE THREAD

**Issue by mpharrigan** [CrossRef/rest-api-doc#242]
Hi. For bibtex files you need to enclose certain things (acronyms) in curly braces so they stay capitalized:

```
@article{Schwantes_2016,
	doi = {10.1016/j.bpj.2016.03.026},
	url = {https://doi.org/10.1016%2Fj.bpj.2016.03.026},
	year = 2016,
	month = {apr},
	publisher = {Elsevier {BV}},
	volume = {110},
	number = {8},
	pages = {1716--1719},
	author = {Christian~R. Schwantes and Diwakar Shukla and Vijay~S. Pande},
	title = {Markov State Models and {tICA} Reveal a Nonnative Folding Nucleus in Simulations of {NuG}2},
	journal = {Biophysical Journal}
}
```

Crossref has this info somewhere because it can correctly render the bibtex. The JSON just has the title and no information about what needs to be curly-braced in bibtex

https://api.crossref.org/v1/works/http://dx.doi.org/10.1016/j.bpj.2016.03.026

Am I missing something? Is there a way to get this information?

**Comment by kmeddings** [comment]
Hi - I'm not sure I'm understanding the question. The title displays correctly in the JSON, and you can get the bibtex directly. Why would the JSON need to include bibtex markup?

**Comment by mpharrigan** [comment]
It seems there's information missing from the JSON representation insofar as you can't generate the bibtex from the json. The specific information that's missing is which parts of the title should be wrapped in `{}`

**Comment by kjw** [comment]
Hi, we convert from an internal metadata representation to JSON, bibtex and many other formats. How the bibtex appears, including which parts are escaped by `{}`, is defined in that conversion process, not the data itself.

Given that we can generate bibtex and JSON for you, is there anything else that you need?

**Comment by gbilder** [comment]
I see the problem, but I'm not sure we've set any expectation that the different representations we support can be losslessly converted back and forth. So, for example, our RIS, Turtle, etc. representations lose this info as well.

**Comment by mpharrigan** [comment]
> Hi, we convert from an internal metadata representation to JSON

> I see the problem, but I'm not sure we've set any expectation that the different representations we support can be losslessly converted back and forth

I guess I supposed JSON was pretty much the same as your internal representation (and can therefore be losslessly converted to bibtex, RIS, turtle, ... (although not vice-versa)) 

Is there a reason why you don't make the internal representation (or something closely resembling it) available?

**Comment by mpharrigan** [comment]
Why was this closed?

**Comment by ppolischuk** [comment]
Apologies for the lack of explanation @mpharrigan. Expanding on @gbilder's last comment, we don't have any immediate plans to support lossless conversion back and forth between our files. I'll see if I can find an answer to your last question re: our internal representation.
