### ISSUE TITLE
Feature Request: Specify item return fields

### ISSUE THREAD

**Issue by denizk** [CrossRef/rest-api-doc#243]
For some of our search queries (e.g. `query.bibliographic`) we are interested in only in a subset of item fields (for example just `DOI`). Would be great if we could specify a set of fields to return in the results, similar to the `fl` parameter in solr.

**Comment by gbilder** [comment]
Agree. We've contemplated at least providing a "light" (biblio fields only) vs "all" representation. add as a vote to our feature requests.

**Comment by gorbynet** [comment]
I'd like to +1 this. I came to raise this as a feature request, glad to see I'm not the only one with this requirement.

**Comment by kjw** [comment]
There is now a `select` query parameter available for any route ending in `/works`. Currently only one value is supported for this parameter - `DOI`. If `select=DOI` is specified, only work DOIs will be returned.

**Comment by denizk** [comment]
Great, thanks Karl.
For `query.bibliographic` queries it would be useful to also have the `score` value selectable. Sorry, forgot to mention this in my first post.
