### ISSUE TITLE
journals/2472-1972/works returns 404

### ISSUE THREAD

**Issue by iv-build-acct** [CrossRef/rest-api-doc#247]
Hi all -

When trying to retrieve articles for ISSN 2472-1972, a 404 is returned with a message 'Resource not found'.

Note querying specific article DOI for this ISSN return successfully (i.e. http://api.crossref.org/works/10.1210/js.2017-00044)

Thanks in advance for your help on this.

Neil Mehta
nmehta@highwire.org

**Comment by danielopitz** [comment]
This should work: http://api.crossref.org/works?filter=issn:2472-1972

Please mind it returns only first 20 (10?) entries and the `rows` and `cursor` parameters are necessary to get more.

**Comment by gbilder** [comment]
Filter works, but journals route (e.g. http://api.crossref.org/journals/2472-1972) should also work.

**Comment by kjw** [comment]
@ckoscher This ISSN may not appear in the title list CSV. Can you investigate?

**Comment by ckoscher** [comment]
ISSN is in the title CSV file.

OAI listing of the DOIs in the journal:
http://oai.crossref.org/OAIHandler?verb=ListIdentifiers&metadataPrefix=cr_unixml&set=J:10.1210:306338
