### ISSUE TITLE
"ISSN" field for an article - list with no order!

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#248]
Looking at the field "ISSN" in the json response, it seems the list is in no particular order.
Example: 

https://api.crossref.org/v1/works/http://dx.doi.org/10.1093/jee/tou001
"ISSN":["0022-0493","1938-291X"]

https://api.crossref.org/v1/works/http://dx.doi.org/10.1093/jee/tov052
"ISSN":["1938-291X","0022-0493"]

This forces us to use the field "issn-type" which makes it harder to parse and also make the "ISSN" useless. Is it possible to make your ISSN field in a fixed order like this one?

"ISSN":[print ISSN, electronic ISSN]

**Comment by danielopitz** [comment]
This would still be totally unreliable, some journals have only one (either print or electronic) ISSN, some more than two (alternative or previous ISSN, its rare, but sometimes they change).

**Comment by gbilder** [comment]
Agree, relying on list order would be unreliable. There are all sorts of odd ISSN combinations. Which is why we included issn type attribute.

**Comment by moqri** [comment]
Is it possible to add the issn type attribute to the journal as well then?
Right now, there is no way we can figure out which ISSN is the print ISSN for a journal:
Example:
http://api.crossref.org/journals/1047-7047
