### ISSUE TITLE
"subject" property of journal

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#249]
Any way I can get the subject categories of a journal directly from the journal (not from its articles)? Isn't the subject a property of the journal rather than the article?

Example: 
Journal: http://api.crossref.org/journals/1047-7047 (no subject field)
Article: http://api.crossref.org/journals/1047-7047/works?rows=1

**Comment by gbilder** [comment]
Agree this makes sense.

Arguably this subject field should *only* be at the journal level. Since we pick it up by ISSN. It is an attribute of the journal, not necessarily inherited by an individual article in said journal.

**Comment by kjw** [comment]
Yes we can add this easily.

**Comment by kjw** [comment]
Appears under `subjects` key in top level of journal map:

```json
"subjects": [
  {
    "name": "Ecology, Evolution, Behavior and Systematics",
    "ASJC": 1105
  },
  {
    "name": "Plant Science",
    "ASJC": 1110
  }
]
```

**Comment by moqri** [comment]
Thanks for this enhancement @kjw !

Do you know how long it takes until the data gets updated? I do not see the "subjects" key for the example journal yet: http://api.crossref.org/journals/1047-7047

**Comment by kerphi** [comment]
Could someone tell me what "ASJC" does mean?

**Comment by moqri** [comment]
https://github.com/plreyes/Scopus
