### ISSUE TITLE
10.5615/neareastarch.76.4.0246 needs fixing with DOI.org

### ISSUE THREAD

**Issue by loupeck** [CrossRef/rest-api-doc#25]
@kjw I wonder if you were able to help me with the below:

I have a publication that appears in our search but when you click on the search result, there is an error in our system which is generally to do with getting the metadata from CrossRef. Please can you check the listing of this publication with DOI.org?

Kudos - https://www.growkudos.com/articles/10.5615/neareastarch.76.4.0246 
CrossRef - http://search.crossref.org/?q=10.5615%2Fneareastarch.76.4.0246 
DOI - http://dx.doi.org/10.5615/neareastarch.76.4.0246 
Publisher site - http://www.jstor.org/discover/10.5615/neareastarch.76.4.0246?uid=3738032&uid=2&uid=4&sid=21104286693031 
Search - https://www.growkudos.com/articles/search?q=Dr+Shawn+C+Malley

**Comment by gbilder** [comment]
This appear to have been fixed. Try:

`curl -LH "Accept: application/rdf+xml;q=0.5, application/vnd.citationstyles.csl+json;q=1.0" http://dx.doi.org/10.1021/ma990057+`
