### ISSUE TITLE
Normalize ISBN field or index normalized version

### ISSUE THREAD

**Issue by danielopitz** [CrossRef/rest-api-doc#250]
Currently the ISBN field is not normalized, some are in the form:
http://api.crossref.org/types/book/works?filter=isbn:9781780648903
and some in:
http://api.crossref.org/types/book/works?filter=isbn:978-3-319-07515-0
Previous ISBN, without dashes, is not searchable:
http://api.crossref.org/types/book/works?filter=isbn:9783319075150

Would it be possible to do something about this?

**Comment by gbilder** [comment]
I've been caught out by this problem myself. We should make this easier.

**Comment by danielopitz** [comment]
It should be good to do something about it in relevant types too (book-chapter). Thanks!

**Comment by kjw** [comment]
I'd like to normalise, but, to what? Anyone know of a spec for ISBNs that recommends a normalised form?

**Comment by alcole** [comment]
We do all ISBN comparisons against the stripped ISBN as we cannot ensure that customer submissions are correctly formatted
The other alternative could be to add the dashes following the prefix / country / group variable length specs and updated the submitted ISBN (we also do this in some scenarios and but response with the submitted ISBN)

**Comment by ckoscher** [comment]
Hyphens are optional, I suggest removing them (be they a hyphen or a dash)

**Comment by danielopitz** [comment]
I think removing dashes is the only viable option. There is too much variability after the country prefix of the ISBN to do this correctly all the time. People mostly don't care.

**Comment by kjw** [comment]
Indexing normalized ISBNs (removing all characters except 0-9 and a potential X check digit.) Won't take affect until we next re-index our data. Probably some time this week.
