### ISSUE TITLE
"issn-type" attribute for journal

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#252]
Is it possible to add "issn-type" for a journal to the journal query?
Right now, there is only an "ISSN" attribute which is in no specific order (#248). The only way we can identify which ISSN is for the print version is to look at the articles.

Example:
Journal: http://api.crossref.org/journals/1047-7047 (only a list of ISSNs)
Article: http://api.crossref.org/journals/1047-7047/works?rows=1 (includes issn_type) 

Might be added to #249 ?

**Comment by kjw** [comment]
@jonmstark Is it possible to include ISSN types in the title list CSV?

**Comment by kjw** [comment]
@kjw Note to self, issn column of title list is being split into eissn, pissn columns.

**Comment by kjw** [comment]
@kjw Note to self: Jon has added a journal id column to the title list CSV.

**Comment by kjw** [comment]
An `issn-type` field will be available in journal documents after the next deployment (a day or two).
