### ISSUE TITLE
Using query.bibliographic does not return authors or title

### ISSUE THREAD

**Issue by stuchalk** [CrossRef/rest-api-doc#257]
In the API documentation it states that 'Query bibliographic infomration, useful for citation look up. Includes titles, authors, ISSNs and publication years' (note the typo on the page).  However, if I do:
http://api.crossref.org/works?query.bibliographic=Dilling%20WL;%20Environ%20Sci%20Technol%2011:%20405-9%20(1977)

I don't get authors, where as with:
http://api.crossref.org/works?query=Dilling WL; Environ Sci Technol 11: 405-9 (1977)

Working correctly?

**Comment by kjw** [comment]
Unfortunately not all metadata records are complete. Some will contain authors and ISSNs, others may not, it really depends on what the publisher has given us for any particular DOI.

All our available metadata, including titles, authors, ISSNs and publication years will be returned for results of both of your queries. `query.bibliographic` search on a subset of "bibliographic" fields (which is what the documentation refers to) but will return all fields in the results found. `query` searches on all fields and also returns all fields.

**Comment by deryc** [comment]
I am a little confused as to what query.bibliographic actually returns.
If my code is 

`http://api.crossref.org/works?query.bibliographic=10.1128/microbiolspec.ARBA-0009-2017/` 

What am I actually getting in return?  The bibliography from the DOI I queried?

**Comment by ppolischuk** [comment]
query.bibliographic simply queries your search terms against any bibliographic data for records. What gets returned is the metadata we have for the resulting list of records.
