### ISSUE TITLE
Work has null in `publisher`, 'title' and `member` elements

### ISSUE THREAD

**Issue by unoexperto** [CrossRef/rest-api-doc#259]
Found another items with null field

http://api.crossref.org/works?rows=1000&filter=type:journal-article&order=asc&sort=deposited&cursor=AoN4qc7d98cCeITIlrPdAj8MaHR0cDovL2R4LmRvaS5vcmcvMTAuMTAwNy9zMTIyODUtMDA4LTAwNzctNw%3D%3D
```
{
  "subtitle": [],
  "author": [
    {
      "given": "Yishao",
      "family": "Huang",
      "affiliation": []
    },
    {
      "given": "Oequn",
      "family": "Zhou",
      "affiliation": []
    },
    {
      "given": "Xiaoxin",
      "family": "Chen",
      "affiliation": []
    },
    {
      "given": "Xueyun",
      "family": "Chen",
      "affiliation": []
    },
    {
      "given": "Zhengwu",
      "family": "Wang",
      "affiliation": []
    }
  ],
  "deposited": {
    "date-parts": [
      [
        2014,
        8,
        19
      ]
    ],
    "date-time": "2014-08-19T20:13:42Z",
    "timestamp": 1408479222000
  },
  "is-referenced-by-count": 3,
  "original-title": [],
  "source": "Crossref",
  "relation": {},
  "prefix": "10.3969",
  "URL": "http://dx.doi.org/10.3969/j.issn.1004-4132.2010.05.019",
  "page": "842-849",
  "score": 1.0,
  "indexed": {
    "date-parts": [
      [
        2017,
        7,
        23
      ]
    ],
    "date-time": "2017-07-23T15:30:51Z",
    "timestamp": 1500823851050
  },
  "issn-type": [
    {
      "value": "1004-4132",
      "type": "electronic"
    }
  ],
  "references-count": 0,
  "issue": "5",
  "issued": {
    "date-parts": [
      [
        2010,
        10
      ]
    ]
  },
  "content-domain": {
    "domain": [],
    "crossmark-restriction": false
  },
  "member": null,
  "short-title": [],
  "publisher": null,
  "container-title": [
    "Journal of Systems Engineering and Electronics"
  ],
  "title": [
    "Robust decentralized adaptive output feedback fuzzy controller design and application to AHS"
  ],
  "type": "journal-article",
  "published-print": {
    "date-parts": [
      [
        2010,
        10
      ]
    ]
  },
  "short-container-title": [
    "J. of Syst. Eng. Electron."
  ],
  "volume": "21",
  "ISSN": [
    "1004-4132"
  ],
  "created": {
    "date-parts": [
      [
        2014,
        8,
        19
      ]
    ],
    "date-time": "2014-08-19T20:11:02Z",
    "timestamp": 1408479062000
  },
  "DOI": "10.3969/j.issn.1004-4132.2010.05.019",
  "reference-count": 0
}
```

**Comment by kjw** [comment]
@ckoscher some UNIXSD records are missing publisher name and member ID crm-item fields, for example, this DOI:

http://api.crossref.org/works/10.3969/j.issn.1004-4132.2010.05.019/transform/application/vnd.crossref.unixsd+xml

**Comment by unoexperto** [comment]
Sadly more errors. Missing `title` now

```
{"author":[{"family":"Hane","affiliation":[]}],"deposited":{"date-parts":[[2007,2,13]],"date-time":"2007-02-13T20:56:13Z","timestamp":1171400173000},"is-referenced-by-count":4,"source":"Crossref","subject":["Software","General Mathematics"],"prefix":"10.1007","URL":"http://dx.doi.org/10.1016/0025-5610(95)00026-8","page":"211","score":1.0,"indexed":{"date-parts":[[2017,8,7]],"date-time":"2017-08-07T23:43:57Z","timestamp":1502149437083},"issn-type":[{"value":"0025-5610","type":"electronic"}],"references-count":0,"issued":{"date-parts":[[1995]]},"content-domain":{"domain":[],"crossmark-restriction":false},"member":"297","publisher":"Springer Nature","container-title":["Mathematical Programming"],"type":"journal-article","published-print":{"date-parts":[[1995]]},"volume":"70","ISSN":["0025-5610"],"created":{"date-parts":[[2002,11,2]],"date-time":"2002-11-02T00:11:24Z","timestamp":1036195884000},"DOI":"10.1016/0025-5610(95)00026-8","reference-count":0}
```

**Comment by kjw** [comment]
Unfortunately missing `title` is legitimate - once upon a time it was optional to register a DOI with Crossref without depositing a title.

`publisher` and `member` should be present. For the DOIs you've identified with the problem we've found they are in a bit of an odd state - they were transferred from another DOI registration agency, but the owner of the DOI is not a member of Crossref. There's an internal data fix coming up for this.

**Comment by unoexperto** [comment]
I see. I'll take that into account.

While we're on this subject do you guys have dump of works in some format, preferably in json ?

**Comment by qilyn** [comment]
Hi @kjw! We've just started having this occur as well--before about twelve hours ago we never had an issue with empty title fields, and now there's a fairly significant number of them. Has something in the API changed to make these entries more likely?

**Comment by ckoscher** [comment]
For the above I assume you're referring to DOI 10.21236/ada452947 which has an empty value in the field original-title.  This is not a problem with the API, it is the data that the publisher deposited. E.g. in this case the sent:

<titles>
  <title>A Stress-Dependent Hysteresis Model for PZT-Based Transducers</title>
  <original_language_title language="en"/><subtitle/>
</titles>

**Comment by kjw** [comment]
This thread has gotten a little off track but the original problem is still there. @ckoscher there are some records that are missing member ID and publisher name crm items. For example:

http://api.crossref.org/works/10.3969/j.issn.1004-4132.2010.05.019/transform/application/vnd.crossref.unixsd+xml

We found that these are due to metadata records for DOIs not registered by Crossref. Any progress towards a fix?

**Comment by jenniferlin15** [comment]
@pdavis8 please investigate the metadata records not registered.

**Comment by jenniferlin15** [comment]
As of the last thread, the core issue has to do with metadata records not registered in our system. I've since checked the record above http://api.crossref.org/works/10.3969/j.issn.1004-4132.2010.05.019/transform/application/vnd.crossref.unixsd+xml. It shows as registered now and contains the metadata elements requested. If there are other works that do not seem to be fully registered, please let us know. Closing ticket for now.
