### ISSUE TITLE
Empty ISSN

### ISSUE THREAD

**Issue by Shtirlits** [CrossRef/rest-api-doc#262]
There are lot's of (1136 at the time of writing this) journals with empty ISSN - `"ISSN":[]`, 4 of them on the index paje for journals endpoint - `http://api.crossref.org/journals`.
Can you explain what does that mean? All that journals have `counts: null`, any chance the count will change, or is it forever?

**Comment by kjw** [comment]
Journals can and in some cases must be without an ISSN. For example, ISSN itself now has rules for new publications that mean publications can no longer receive an ISSN before they are first published.

Unfortunately we use ISSNs to calculate aggregated values for journals, so at the moment journals without ISSNs will not get aggregated data such as counts, metadata coverage info, so on.

There's a possibility of using an internal identifier at Crossref to do this aggregation for non-ISSN journals but it could be imperfect - we may end up with poorly disambiguated journal data. I need to look into what we have.

**Comment by ckoscher** [comment]
If a journal does not have an ISSN we require the publisher to assign a 
DOI to the title
Chuck

**Comment by ppolischuk** [comment]
Closing per above discussion.
