### ISSUE TITLE
Problems with prefixes route

### ISSUE THREAD

**Issue by pschloss** [CrossRef/rest-api-doc#264]
I'm trying to back track the owner of a number of doi prefixes and am running into a number of 404 errors. Here's one example...

https://api.crossref.org/prefixes/10.3978/

Yet...

https://dx.doi.org/10.3978/j.issn.2072-1439.2013.06.02

... works fine. Am I missing something in how the API or prefixes are supposed to work?

Thanks,
Pat

**Comment by ioverka** [comment]
To me it looks like this prefix has been handed out by another registration agency (see http://dx.doi.org/10.3978) and therefore no information can be retrieved via the Crossref API.

**Comment by kjw** [comment]
Yes, unfortunately not a Crossref prefix or DOI. The API only knows about Crossref data.
