### ISSUE TITLE
/journals/{issn} is not working for many journals

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#265]
example: 
http://api.crossref.org/journals/1689-7404/

While individual papers of these journals are displaying ISSN 
https://api.crossref.org/v1/works/http://dx.doi.org/10.15290/bsp.2014.17.04

**Comment by moqri** [comment]
It seems this issue has been appeared recently. Currently 28,000 journals have non-empty "ISSN" values while last month I think 50,000 journals had non-empty ISSN values.

https://api.crossref.org/journals/

**Comment by moqri** [comment]
This problem exists even for some top Elsevier journals:

http://api.crossref.org/journals/0306-4379

**Comment by ckoscher** [comment]
Not sure what is going on in the API index. Many DOIs exist with that ISSN deposited for the journal metadata

http://oai.crossref.org/OAIHandler?verb=ListIdentifiers&metadataPrefix=cr_unixml&set=J:10.1016:2017

**Comment by moqri** [comment]
Another big journal example: 
Elsevier - Cell (0092-8674) http://www.cell.com/cell/home
http://api.crossref.org/journals/0092-8674

**Comment by kjw** [comment]
On holiday but I'll take a look at this on Monday...

**Comment by moqri** [comment]
It seems the issue is resolved. Thanks!
