### ISSUE TITLE
work abstracts in JSON form are not well-formed XML

### ISSUE THREAD

**Issue by jakegt1** [CrossRef/rest-api-doc#266]
As the XML generated by does not have a root nor a namespace, you need extra effort to reconstruct an XML document for the JATS formatted abstracts, like wrapping it with a random element with a namespace attribute.

So, in python I would have to string format like so:
```python
"<jats:abstract xmlns:jats='http://jats.nlm.nih.gov'>{}</jats:abstract>".format(xml_abstract_data)
```

then cast that string to XML.

**Comment by kjw** [comment]
We can add this wrapper to all abstract fields. Would that be helpful?

**Comment by jakegt1** [comment]
That would be helpful if possible 😃
