### ISSUE TITLE
X-Rate-Limit-Interval has no defined format

### ISSUE THREAD

**Issue by jakegt1** [CrossRef/rest-api-doc#267]
The X-Rate-Limit-Interval header, as I last tried it had a value of "1s" - I'm not sure what to expect when programming -

Is a value like "1m30s" possible? Or "1h1m30s", and should i program accordingly?

I do assume that it'll probably be static at 1s (10 requests per 1 second seems reasonable as of now), but as I don't know what this interval can be I can't really develop accordingly.

**Comment by AndrewBennet** [comment]
Is there any update on this?

**Comment by gbilder** [comment]
Hi. Rate limits were introduced in kind of a rush, so sorry about lack of doc. `X-Rate-Limit-Interval` will always be expressed in seconds, so no need for complicated parsing. I have [updated the documentation](https://github.com/CrossRef/rest-api-doc#rate-limits).

**Comment by AndrewBennet** [comment]
Thanks! Good to know :)

**Comment by ppolischuk** [comment]
Closing per @gbilder's comment.
