### ISSUE TITLE
Selective journal ISSN information with /journals/{issn} for some journals

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#268]
When we use /journals{issn} for some journals, sometimes we only get one ISSN (e.g. print ISSN) for that journal while all the articles published in that journal are using the other ISSN (e.g. Electronic ISSN)
Example:
http://api.crossref.org/journals/1544-9173 (journal reporting only print ISSN)
https://api.crossref.org/v1/works/http://dx.doi.org/10.1371/journal.pbio.0020025 (papers reporting the other issn)

Currently is really hard to connect the journal and all its articles. Is it possible to report both ISSN s in the /journals{issn} ?

**Comment by kjw** [comment]
Should be as you describe, possible bug.

**Comment by moqri** [comment]
Also, for journals with multiple ISSNs, each /journals{issn} reports differently.
Example:
Nature (ISSNs=["0028-0836","1476-4687"])

http://api.crossref.org/journals/1476-4687  reports both ISSN
http://api.crossref.org/journals/0028-0836 only reports one ISSN

**Comment by kjw** [comment]
Now resolved - in your last example both routes return the same record which contains both ISSNs.
