### ISSUE TITLE
Journals with subject categories

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#269]
I can see around 21,000 journals with subject categories using http://api.crossref.org/journals

I remember in one of your updates, it was announced that 45,000 journals have subject categories now. Is there any way I can get all of them?

**Comment by pdavis8** [comment]
Hello,
Sorry for the delay in reply.
When I run that query to the API now I get total-results: 58896.
Please do let me know if you are seeing something different and I will look into this further for you.

**Comment by pdavis8** [comment]
Hello, 
I shall close this ticket for now as no reply and I am unable to replicate the issue. Please do reopen this should you still be seeing issues.
