### ISSUE TITLE
API download works problem

### ISSUE THREAD

**Issue by henridewinter** [CrossRef/rest-api-doc#270]
I try to download works with the follwing url:

http://api.crossref.org/works?filter=from-pub-date:2011-01,until-pub-date:2011-12&rows=1000&cursor=AoJ2sKvt5t0CPxFodHRwOi8vZHguZG9pLm9yZy8xMC4xNTU2L25vdmVueXRlcm0uNjAuMjAxMS4yLjg=

This doesn't work because of the = character in the cursor. Even if I url encode the cursor the query won't give me results. Sometimes I also noticed slashes in the cursor which gave me problems. How do I deal with these cursors?

kind regards,
Henri de Winter

**Comment by moqri** [comment]
URL encoding should work. Are you sure your cursor is correct?

Example: 
Broken= http://api.crossref.org/works?filter=from-pub-date:2011-01,until-pub-date:2011-12&rows=1000&cursor=AoJy+sfu390CPwVodHRwOi8vZHguZG9pLm9yZy8xMC4xMDA3L2JmMDAzNDM1MDM=
Fixed= http://api.crossref.org/works?filter=from-pub-date:2011-01,until-pub-date:2011-12&rows=1000&cursor=AoJy%2Bsfu390CPwVodHRwOi8vZHguZG9pLm9yZy8xMC4xMDA3L2JmMDAzNDM1MDM%3D

**Comment by henridewinter** [comment]
When using this url:

http://api.crossref.org/works?filter=from-pub-date:2011-01,until-pub-date:2011-12&rows=1000&cursor=AoJ6qKft5t0CPwxodHRwOi8vZHguZG9pLm9yZy8xMC4xMTI2L3NjaXNpZ25hbC4yMDAyMDUy

I get this error

The remote server returned an error: (500) Internal Server Error.

The cursor I use is retrieved from the previous API call (previous 1000 works)

Do you know why I get this error?

**Comment by moqri** [comment]
It would be easier to find the issue if you pos the previous api call url.

**Comment by danielopitz** [comment]
You could change the row count to a slightly lower number if a query fails and retry it, this should return a different cursor.

**Comment by henridewinter** [comment]
Thank you for your answer Daniel but I don't think that's the correct way to go. It would make my software needless complex and error prone. I hope that the error at crossref can be solved so that only valid cursors are returned.

**Comment by moqri** [comment]
I don't think this one is the about url-encoding. I think there is a broken record here:
http://api.crossref.org/works?filter=from-pub-date:2011-01,until-pub-date:2011-12&rows=1&cursor=AoJw26zt5t0CPwxodHRwOi8vZHguZG9pLm9yZy8xMC4yNDc4L3YxMDEzNi0wMTEtMDAwMi03

**Comment by kjw** [comment]
Oh no - it is actually a server deployment config issue that we've had time and time again - routing cursor queries to a Solr that is configured in a way that doesn't allow them (it has a `timeAllowed` set, for what it's worth.)

I'll ping the relevant people and then cry myself to sleep.

**Comment by kjw** [comment]
Fixed, waiting on redeployment of service.

**Comment by henridewinter** [comment]
Hi Karl Jonathan,

Thank you very much for your quick response and help. Can you notify me when the redeployment is finished?

Kind regards,
Henri
