### ISSUE TITLE
journals/{ISSN} reports 0000-0000 for ISSN (as well as the correct ISSN)

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#274]
Example: 
http://api.crossref.org/journals/0268-0556
http://api.crossref.org/journals/0167-5427

and some 500 other journals

**Comment by kjw** [comment]
@ckoscher This is present in our title metadata - can we get a fix?

**Comment by kjw** [comment]
@jonmstark @ckoscher I've looked into this further. There are 543 journals listed in our title list CSV with an ISSN of `00000000`. Can we get a fix for this asap?

**Comment by ckoscher** [comment]
with the run tomorrow at 3AM issns of 0000000 will be filtered from the titles CSV file, and ultimately removed from the deposit database

**Comment by kjw** [comment]
@ckoscher Those ISSNs are still in the titles CSV.

**Comment by kjw** [comment]
All good now - we've removed all mention of the `0000-0000` ISSN.
