### ISSUE TITLE
On the availability of reference in answers of API

### ISSUE THREAD

**Issue by sergii-mamedov** [CrossRef/rest-api-doc#275]
I see in API responses to the presence of **reference** for the journals Phys. Rev. B., for example [10.1103/PhysRevB.37.785](http://api.crossref.org/works/10.1103/PhysRevB.37.785). Why, when I register a references for my journal Usp. Fiz. Met, for example [10.15407/ufm.18.01.001](http://api.crossref.org/works/10.15407/ufm.18.01.001)  I do not see **reference**? At the same time, it can be seen at the (request)[https://doi.crossref.org/search/doi?pid=ukrin:pass&format=unixsd&doi=10.15407/ufm.18.01.001]

Thanks for your answer.

**Comment by pdfeeney** [comment]
References are not visible by default, you need to opt-in to have your references made available through Crossref APIs. To opt in, email support@crossref.org and ask to have references enabled.

**Comment by sergii-mamedov** [comment]
Thank you :)
