### ISSUE TITLE
Missing Title in Doi https://api.crossref.org/works/10.1023/A:1010933404324

### ISSUE THREAD

**Issue by MartinDobisch** [CrossRef/rest-api-doc#276]
Hey there, i just found a Doi-entry without a title.
The title field is there, but it has no value.

https://api.crossref.org/works/10.1023/A:1010933404324

Greetings

**Comment by XavRsl** [comment]
Found a few more:
- https://api.crossref.org/works/10.1186/1742-4690-3-95
- https://api.crossref.org/works/10.1038/12469

This seems to have started on the 11th of September. Titles (and subtitle, short-title) used to be here.

thanks.

**Comment by ckoscher** [comment]
DOI 10.1023/A:1010933404324 was never deposited  by the publisher with an article title.

**Comment by MartinDobisch** [comment]
So a publication title is not mandatory?

**Comment by ckoscher** [comment]
Article title was not provided.  The publication title is "Machine Learning" which you find in

"container-title": [

    "Machine Learning"

],

**Comment by MartinDobisch** [comment]
You are mistaken there.
https://link.springer.com/article/10.1023/A:1010933404324
its name is random forest. but thanks anyways

**Comment by ckoscher** [comment]
Bad publisher data deposited to Crossref.

**Comment by kjw** [comment]
@ckoscher Can we alert the publisher and ask them to repdeosit?

**Comment by jenniferlin15** [comment]
@pdavis8 please contact publisher as Crossref Support.

**Comment by pdavis8** [comment]
Hello,
Apologies for the delay in reply. 
These DOIs have been passed onto the publisher to look into and hopefully they will redeposit the metadata to us containing the article titles very soon.
Thanks,
Paul
