### ISSUE TITLE
API outage?

### ISSUE THREAD

**Issue by denizk** [CrossRef/rest-api-doc#277]
I don't seem able to access any api.crossref.org endpoints

**Comment by uqclien** [comment]
same her:
`500 Internal Server Error` response:
{"status":"error","message-type":"exception","message-version":"1.0.0","message":{"name":"class org.apache.solr.client.s (truncated...)

**Comment by uqclien** [comment]
https://support.crossref.org/hc/en-us/articles/115004746006-Service-outage-9-17

**Comment by denizk** [comment]
> Update (2:00 pm UTC): all services were restored as of 7 am UTC. Some of you may have seen timeouts through ~ 1 PM UTC.  Please report any current outages or timeouts to support@crossref.org.
