### ISSUE TITLE
get application/vnd.crossref.unixsd+xml response

### ISSUE THREAD

**Issue by pajooh** [CrossRef/rest-api-doc#28]
i know that for singletons we can append `transform/application/vnd.crossref.unixsd+xml` to url.
can we do this for lists, with other parameters. maybe we should set `Accept` header or something?

**Comment by gbilder** [comment]
Also- we the `transform` trick for converting representations is not documented and is not guaranteed to be kept around. Be aware it may go away. 

 We will still provide some way of doing this same kind of thing, but we think the existing mechanism is both fragile and not in keeping with the rest of the API. We are exploring options.
