### ISSUE TITLE
Using select parameter when querying DOI

### ISSUE THREAD

**Issue by mikegra** [CrossRef/rest-api-doc#281]
I'm trying to make a simple API call for a single DOI which only returns information from a single field, e.g. issue. The select parameter seems to do precisely this but I can't make it work.  All I get is "Resource is not found". Here's an example of an API call I tried:
http://api.crossref.org/works/10.1108/AJIM-01-2017-0019&select=issue

Am I doing something wrong here or is it simply not possible?

**Comment by brandonStell** [comment]
There is no issue in the example you give but I believe this would be the sort of thing you're looking for:
http://api.crossref.org/works?filter=doi:10.1108/AJIM-01-2017-0019&select=DOI,title,issue

**Comment by kjw** [comment]
The `select` parameter only works on "list like" responses, such as `/works` - it won't work when looking up a particular DOI. In that case.
