### ISSUE TITLE
Query title with punctuation?

### ISSUE THREAD

**Issue by brandonStell** [CrossRef/rest-api-doc#283]
Is it possible to `query.title` with punctuation?

for example
http://api.crossref.org/works?query.title=[retracted]

returns results with "retracted" in the title without the brackets; I am only looking for titles that have the word retracted in brackets.

**Comment by kjw** [comment]
It isn't, sorry, all punctuation is stripped out. Is it feasible to filter results once you have them?

**Comment by brandonStell** [comment]
yes, i can filter them after. thanks
