### ISSUE TITLE
Varying API response time

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#286]
It seems recently the API response time fluctuates a lot. Is it possible to check the speed/traffic or know about when the traffic is low, so we can plan our api-heavy activities for that time?

**Comment by kjw** [comment]
@moqri Have you seen the information about using the "polite" pool of API servers for improved response time and uptime?

See the documentation about [specifying a user agent](https://github.com/CrossRef/rest-api-doc#etiquette).
