### ISSUE TITLE
Clarify select parameter: what routes allow it; what values can be passed to it

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#289]
## what routes?

It's clear that e.g. `select` is not allowed on this route `http://api.crossref.org/works/10.1007/s10980-007-9188-1/?select=DOI` but what is the complete list of routes it is allowed on?

## what values?

http://api.crossref.org/works?select=volume gives

```json
{
	"status": "error",
	"message-type": "exception",
	"message-version": "1.0.0",
	"message": {
		"name": "class java.lang.NullPointerException",
		"description": "java.lang.NullPointerException",
		"message": null,
		"stack": [ ],
		"cause": null
	}
}
```

Either this is supposed to work, or `volume` among other values are not allowed to be passed to `select` param. Any clarification?

**Comment by kjw** [comment]
Looks like `volume` is a bug. Select should work on any route that ends with `/works`.

**Comment by jenniferlin15** [comment]
Ticketed - GO-919.

**Comment by markwoodhall** [comment]
Once the commit referenced above is available in production it should be possible to select all of the following fields:

```
abstract, URL, member, posted, score, created, degree, update-policy, short-title, license, ISSN, container-title, issued, update-to, issue, prefix, approved, indexed, article-number, clinical-trial-number, accepted, author, group-title, DOI, is-referenced-by-count, updated-by, event, chair, standards-body, original-title, funder, translator, archive, published-print, alternative-id, subject, subtitle, published-online, publisher-location, content-domain, reference, title, link, type, publisher, volume, references-count, ISBN, issn-type, assertion, deposited, page, content-created, short-container-title, relation, editor
```

**Comment by ckoscher** [comment]
I'm not seeing any commit on Crossref/cayenne for this ....

**Comment by markwoodhall** [comment]
It's in a branch that is waiting to be merged, unfortunately it will come along with all of the high level testing work. 

https://github.com/CrossRef/cayenne/commit/bc174069517f9a8986ec6dd4de0f92069653df07

**Comment by sckott** [comment]
thanks - any estimate for that landing?

**Comment by afandian** [comment]
I'm reviewing the pull request now. I'll make sure this thread is updated when deployed.
