### ISSUE TITLE
filters for /members and /funders routes

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#290]
The newly documented filters for these routes only give `filter-not-available` errors

**Comment by kjw** [comment]
I need fix the docs - someone has documented things that don't exist.

**Comment by sckott** [comment]
thanks @kjw

**Comment by gbilder** [comment]
I think I was the one who documented these. They seem to work.

- `http://api.crossref.org/funders?filter=location:Japan`
- `http://api.crossref.org/members?filter=has-public-references:true`
- `http://api.crossref.org/members?filter=current-doi-count:0,backfile-doi-count:0`

But perhaps I misunderstand. Can you give examples?

**Comment by sckott** [comment]
hugh, i guess they work now. they didn't work for me when issue opened.
