### ISSUE TITLE
Journal counts values inconsistently available

### ISSUE THREAD

**Issue by richardkoks** [CrossRef/rest-api-doc#295]
Hi,

I am running a script to pull the basic information from the `/journals` endpoint (title, publisher, print issn, online issn, total-dois), paging through 1000 results at a time using `rows` and `offset`. So far so good. However over subsequent runs I am often not getting any data back for the `counts` value. For instance I have just now run it twice in a row and got the following:

First run:

| title                                                         | publisher                                             | issn_print | issn_online | total_dois | 
|---------------------------------------------------------------|-------------------------------------------------------|------------|-------------|------------| 
| Entomologiske meddelelser                                     | Smithsonian Institution Biodiversity Heritage Library | 0013-8851  |             | 0          | 
| Entomologisk tidskrift / Entomologiska föreningen i Stockholm | Smithsonian Institution Biodiversity Heritage Library | 0013-886X  |             | 0          | 

Second run:

| title                                                         | publisher                                             | issn_print | issn_online | total_dois | 
|---------------------------------------------------------------|-------------------------------------------------------|------------|-------------|------------| 
| Entomologiske meddelelser                                     | Smithsonian Institution Biodiversity Heritage Library | 0013-8851  |             | 4          | 
| Entomologisk tidskrift / Entomologiska föreningen i Stockholm | Smithsonian Institution Biodiversity Heritage Library | 0013-886X  |             | 31         | 

Note that on the second run the total-dois are different. I compared this data to the results of a run of the same script from about a week ago and see a vast number of differences. The differences are always that total-dois is zero, indication that the `count` field is null in the response.

Any help would be much appreciated!

```python
import json
import time
from csv import DictWriter
from urllib.request import Request, urlopen


MAILTO="r.koks@digital-science.com"


def get_journal_info(res):
    for items in json_res["message"]["items"]:
        issn_print, issn_online = None, None
        for issn_type in items["issn-type"]:
            if issn_type["type"] == "print":
                issn_print = issn_type["value"]
            elif issn_type["type"] == "electronic":
                issn_online = issn_type["value"]

        total_dois = items["counts"]["total-dois"] if items["counts"] else 0

        yield {
          'title': items["title"],
          'publisher': items["publisher"],
          'issn_print': issn_print,
          'issn_online': issn_online,
          'total_dois': total_dois
        }


with open('crossref.csv', 'w') as outfile:
    fieldnames = ['title', 'publisher', 'issn_print', 'issn_online', 'total_dois']
    writer = DictWriter(outfile, fieldnames=fieldnames)
    writer.writeheader()

    total_results = None
    seen_results = 0
    batch_size = 1000
    while total_results is None or seen_results < total_results:
        journal_url = "https://api.crossref.org/journals?rows={0}&offset={1}&mailto={2}".format(batch_size, seen_results, MAILTO)

        req = Request(journal_url)
        res = urlopen(req).read().decode("utf-8")
        json_res = json.loads(res)

        if total_results is None:
            total_results = json_res["message"]["total-results"]

        for row in get_journal_info(json_res):
            writer.writerow(row)
            seen_results += 1

        print("Processed {0} results of {1}".format(seen_results, total_results))

        # Small sleep to not hit the API too hard
        time.sleep(2)
```

**Comment by richardkoks** [comment]
I also took a screenshot of a journal at the https://api.crossref.org/journals/0724-4983 endpoint yesterday and today that show the difference in output:

Yesterday:
![screen shot 2017-11-08 at 16 42 07](https://user-images.githubusercontent.com/310777/32612962-7ffc210c-c561-11e7-8b9a-469831a897fe.png)

Today:
![screen shot 2017-11-09 at 15 19 00](https://user-images.githubusercontent.com/310777/32612974-8644bed4-c561-11e7-89da-d7e20fc044f8.png)

**Comment by jenniferlin15** [comment]
@gbilder: 
I have confirmed (as of 12/22, 11.23am PT) that the DOI counts currently match those pulled back in @richardkoks second run. http://api.crossref.org/works?filter=issn:0013-8851 pulls back 4. http://api.crossref.org/works?filter=issn:0013-886X pulls back 31.

**Comment by gbilder** [comment]
I cannot reproduce this. Am getting consistent results (4,31 respectively). I suspect this was an artefact of a failed reindexing we did in November and subsequently corrected.

**Comment by richardkoks** [comment]
Thanks @gbilder, I'll try it out again and let you know if I see any problems going forward.
