### ISSUE TITLE
Invalid JSON response from XML API when performing multiple queries in a single request

### ISSUE THREAD

**Issue by kwikwag** [CrossRef/rest-api-doc#297]
When requesting multiple items via a XML HTTPS GET request with a JSON result format, the produced JSON is invalid. The final closing curly brace (`}`) for each item seems to be incorrectly placed at the end of the `items` list, rather than at the end of each item in the list, which results in an incorrectly formatted JSON document. 

Following is straightforward sample Python (3) code which reproduces the failure. It uses the example query provided in the [Using HTTPS to Query](https://support.crossref.org/hc/en-us/articles/213566986-Using-HTTP-to-Query) documentation page. I confirmed it occurs with other citations, and also with 3 queries (rather than 2). For debugging convenience, it outputs the result to a file before trying to parse it.

```python
import requests
import json
import re
import time

def send_xml_query(email, queries, doi_batch_id=None, format=None, password=None):
    if doi_batch_id is None:
        doi_batch_id = re.sub(r'[^A-Za-z0-9]', '_', email) + '_' + str(time.clock())
    if format is None:
        format = "json"

    xml_query = '''
        <?xml version="1.0"?>
        <query_batch version="2.0" xsi:schemaLocation="http://www.crossref.org/qschema/2.0 http://www.crossref.org/qschema/crossref_query_input2.0.xsd" xmlns="http://www.crossref.org/qschema/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <head>
            <email_address>''' + email + '''</email_address>
            <doi_batch_id>''' + doi_batch_id + '''</doi_batch_id>
        </head>
        <body>
        ''' + '\n'.join(queries) + \
        '''
        </body>
        </query_batch>
        '''
    response = requests.get('http://doi.crossref.org/servlet/query', dict(
        usr=email, pwd=password, format=format, qdata=xml_query))
    return response.text

if __name__ == "__main__":
    response = send_xml_query("email.omitted@example.org", [
        '<query key="query1" enable-multiple-hits="true" forward-match="false">'
            '<issn match="optional">15360075</issn>'
            '<journal_title match="exact">American Journal of Bioethics</journal_title>'
            '<author match="fuzzy" search-all-authors="false">Agich</author>'
            '<volume match="fuzzy">1</volume><issue>1</issue><first_page>50</first_page><year>2001</year>'
            '<article_title>The Salience of Narrative for Bioethics</article_title>'
        '</query>',
        '<query key="query2" enable-multiple-hits="true">'
            '<unstructured_citation>Hungate, B. A., &amp; Hampton, H. M. (2012). Ecosystem services: Valuing ecosystems for climate. Nature Climate Change, 2(3), 151-152.</unstructured_citation>'
        '</query>'])
    open('crossref_xml_api_sample.txt', 'w', encoding='utf-8').write(response)
    print(json.loads(response))
```

**Comment by afandian** [comment]
Can you help triage this @ckoscher @jenniferlin15 ? This is unconnected to Cayenne.

**Comment by pdavis8** [comment]
Hello,

Many thanks for your message.

Could you please clarify if you are transferring this in JSON at your end? We return the results in XML as the query is made to the system in XML.

If you have further information on this query and the processes you are running I will look into this with some colleagues for you.

Many thanks,
Paul

**Comment by pdavis8** [comment]
As this ticket has been open for a while with no reply, I will close this for now and if you have any further questions then please do re-open this again.
