### ISSUE TITLE
Work contains ISSNs from two unrelated (technically) journals

### ISSUE THREAD

**Issue by Shtirlits** [CrossRef/rest-api-doc#298]
If we look at https://api.crossref.org/works/10.1080/00222937008696154, we'll see, that there are two ISSNs there - `"ISSN":["0374-5481","1464-5262"]`

If we check first one - https://api.crossref.org/journals/0374-5481, it will give us `["0374-5481"]`
If we check the second one - https://api.crossref.org/journals/1464-5262, it will give us `["0374-5481","1464-5262"]`

Which leaves us with one Work linked to two unrelated (technically) journals. They share the publisher and journal name, but aren't linked with any relations. Is this ok, or should this two journals be merged into one?

**Comment by pdavis8** [comment]
Hello,

Thanks for the query.

Having looked at those two ISSNs now I can see that these are now not linked and have the correct ISSNs. When you click on the queries you provided in your original message you can see that [https://api.crossref.org/journals/1464-5262](https://api.crossref.org/journals/1464-5262) is now showing with the correct ISSNs 00222933 and 14645262. 

I hope this helps and if you have any further questions then please do not hesitate to ask.

Thanks,
Paul
