### ISSUE TITLE
JSON formatting issue

### ISSUE THREAD

**Issue by ulli-steiner** [CrossRef/rest-api-doc#299]
Problem with rendering non-ASCII characters in author names.  

Examples:

https://api.crossref.org/v1/works/http://dx.doi.org/10.1140/epjb/e2005-00006-x
https://api.crossref.org/v1/works/http://dx.doi.org/10.1140/epje/e2004-00005-8

**Comment by jenniferlin15** [comment]
Thank you for letting us know. We've created a ticket to address this issue, @ulli-steiner.

**Comment by jenniferlin15** [comment]
Ticketed - GO-956

**Comment by afandian** [comment]
Looks like there could be an issue in the XML deposit: https://api.crossref.org/works/http://dx.doi.org/10.1140/epjb/e2005-00006-x/transform/application/vnd.crossref.unixsd+xml

**Comment by ckoscher** [comment]
That DOi was last touch in 2007.  For a brief period around that time we had a character encoding problem.  We went back and fixed as much of these as we could, and informed publishers of problems that we could not, and for which they had to redeposit.  Certainly not all have done  so,

**Comment by jenniferlin15** [comment]
@pdavis8  so this is a data issue where the publisher needs to redeposit: <person_name sequence="first" contributor_role="author">
<given_name>O. F.</given_name>
<surname>G�bel</surname>
</person_name>
Please let them know. Thanks!

**Comment by pdavis8** [comment]
I have contacted the publisher and asked for them to correct and redeposit the metadata for those two DOIs to resolve this issue.
Thanks,
Paul
