### ISSUE TITLE
Cited by counts in work responses

### ISSUE THREAD

**Issue by kjw** [CrossRef/rest-api-doc#30]
Work responses should contain a 'cited-by-count'. Should possibly also rename 'reference-count' as 'cites-count'.

**Comment by hubgit** [comment]
This would be extremely useful - currently it's available in the fl_count attribute of http://www.crossref.org/openurl/?pid={email}&id=doi:{DOI}&noredirect=true but that's neither JSON nor accessible by cross-domain requests.

It would be also be acceptable (maybe even preferable) to have a separate API endpoint for these counts that returned just a number.

**Comment by kjw** [comment]
I'm looking at how I can get this data and keep it updated. There are a few internal hurdles on this one.

**Comment by hubgit** [comment]
Has there been any progress on this? It would be useful for [analysing citation distributions within a journal](https://twitter.com/lfliz/status/644417356555513856).

**Comment by ckoscher** [comment]
One internal hurdle Karl speaks of is now being worked. Its a mechanism to isolate cited-by counts so they can be retrieved by themselves, for given date intervals. This mechanism will allow the API indexer to keep its data updated much more easily.
 
note: there is a format=json  option on the openurl API. Be careful, there may be differences between openurl json and the Work responses

**Comment by hubgit** [comment]
It would be useful to be able to sort by "cited" count as well, to retrieve the most cited articles matching a query.

**Comment by Singularity9971** [comment]
Any update on this? This functionality would be very useful

**Comment by denizk** [comment]
Seems like there have been some changes on this recently. The `is-referenced-by-count` field has been added and `cites-count` has been renamed to `references-count`.

**Comment by hubgit** [comment]
Excellent! Now it's possible to sort by the `is-referenced-by-count` field :)

https://api.crossref.org/journals/1932-6203/works?filter=type%3Ajournal-article&rows=5&sort=is-referenced-by-count&order=desc
