### ISSUE TITLE
Obtaining metadata for a list of DOI's

### ISSUE THREAD

**Issue by ghost** [CrossRef/rest-api-doc#301]
Hi,

I have a list of about 100 DOI's for which I would like to get metadata from the CrossRef API. I checked the documentation, but haven't found a way to input the 100 DOI's in one query and return the metadata in a list.

Of course, I could get the data by simply querying the API 100 times (once for each individual DOI), but I have the feeling this would unnecessarily burden your servers. Is there any way to achieve the above?

Thanks!

**Comment by gbilder** [comment]
I wouldn't worry about hitting the API 100s of times. But in the interest of completeness- You can do what you are asking by including the DOI filter multiple times like this:

`http://api.crossref.org/works?filter=doi:10.5555/12345678,doi:10.5555/777766665555`

But you may hit some URL size limits.

**Comment by raven44099** [comment]
I tried but couldn't figure out how chaining of DOI's works for the API of metadata:
```py
multi = 'https://opencitations.net/index/coci/api/v1/metadata/10.1186/1475-2840-9-14,10.5555/777766665555'
HTTP_HEADERS = {"authorization": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx"}
response = get(multi, headers=HTTP_HEADERS)
```

**Comment by ppolischuk** [comment]
The above issue thread pertains to the Crossref REST API. It looks like you're trying to retrieve data from the Open Citations API.
