### ISSUE TITLE
Combining queries and select statement results in stack-trace

### ISSUE THREAD

**Issue by gbilder** [CrossRef/rest-api-doc#302]
Seems to only occur with variations of the query parameter

http://api.crossref.org/works?query.container-title:Nature&select=title,doi

**Comment by jenniferlin15** [comment]
Ticketed - GO-960

**Comment by markwoodhall** [comment]
Apologies if I have not completely understood this issue but it looks a little bit like the example url is not formed correctly. 

`http://api.crossref.org/works?query.container-title:Nature&select=title,doi` returns a NullPointerException when I try it but using `http://api.crossref.org/works?query.container-title=Nature&select=title,doi` returns a validation failure:

```javascript
{
  "status": "failed",
  "message-type": "validation-failure",
  "message": [
    {
      "type": "select-not-available",
      "value": "doi",
      "message": "Select doi specified but there is no such select for this route. Valid selects for this route are: abstract, URL, member, posted, score, created, degree, update-policy, short-title, license, ISSN, container-title, issued, update-to, issue, prefix, approved, indexed, article-number, clinical-trial-number, accepted, author, group-title, DOI, is-referenced-by-count, updated-by, event, chair, standards-body, original-title, funder, translator, archive, published-print, alternative-id, subject, subtitle, published-online, publisher-location, content-domain, reference, title, link, type, publisher, volume, references-count, ISBN, issn-type, assertion, deposited, page, content-created, short-container-title, relation, editor"
    }
  ]
}
```

Selecting the `DOI` field by using the following url `http://api.crossref.org/works?query.container-title=Nature&select=title,DOI` works as expected, I think.

**Comment by afandian** [comment]
Agreed, the syntax of the query in the original ticket looks incorrect. I would expect to see an error message to this effect. So maybe the feature does work as expected, but the error message can be improved.

**Comment by jenniferlin15** [comment]
Closing ticket since original issue has been addressed. We need to do overall review of all error messages and will fold this example into that separate effort.
