### ISSUE TITLE
Recommendations for being polite in API wrapping libraries that use CI

### ISSUE THREAD

**Issue by mjy** [CrossRef/rest-api-doc#305]
I have a gem that wraps the API- https://github.com/SpeciesFileGroup/ref2bibtex.  It can configured to provide a "polite" email.  However, it uses CI to test itself against the API. I'd rather not provide my own email in the gem config.  That library is in turn used in other applications, which may use CI to test the API endpoints.  Every time we push we're going to hit the API, it's likely nothing in terms of stressing the API, and we use VCR to cache requests in the applications that use the gem, BUT, maybe there is a recommendation for how to best configure those types of libraries?

One possible approach would be to allow users to provide a github URL pointing to the source library (perhaps the issue tracker?!) of the CI originiating request, rather than just an email?  That would allow you to contact us, albeit indirectly, if we're doing something bad?

**Comment by renanbr** [comment]
I'm also developing a wrapper (in PHP), and I had the same problem.

I know nothing about ruby, all I can share is the strategy currently adopted for the library's tests:

1. use a [library to make request](https://github.com/guzzle/guzzle) instead of a native request maker;
2. [mock the reponses in tests](https://github.com/renanbr/crossref-client/blob/2e0dce51f79dbab79eee7f50eebb25c27ca61832/tests/TestCase.php#L23-L36).

As you can see, the tests of my library [never touch the API server](https://travis-ci.org/renanbr/crossref-client/builds).

The libraries that use you wrapper, they **should** IMO mock your library as well... and so on...

**Comment by mjy** [comment]
Thanks @renanbr.  I'm already more or less using this pattern.  I do use mocks in some cases, but here I prefer to actually touch the API, it's "real", and my code breaks when the target API changes (as it just did), or shortly thereafter (when my VCR cache clears).  With mocks only I don't detect this, and repeating mocks all the way down doesn't seem very DRY (I'm not repeating all tests, just proof of life in downstream use).  Another nice example of why one might want to hit the APl directly just recently occured related to the score being used/returned (https://github.com/CrossRef/rest-api-doc/issues/170). In this case value being returned changed, not the format of the request- this would be *very* confusing to keep upto date with mocks.  

In Ruby the VCR gem records a (real) API interaction on first use and caches the response for subsequent tests, until that cache is cleared at a time frame over your choosing, best of both worlds. 

So, I agree with you, your pattern is excellent, and it works well, I'm just curious to see if anything else coudl be done (in part because I anticipate identical issues with APIs we are building).

**Comment by gbilder** [comment]
The URL pointing to the source library is an interesting option. Only downside is, as you point out, is the indirection. When we face a problem, we'd really like to know we can get in touch quickly and automatically.  Will ponder this.

Understand about not wanting to include your own email in gem config. In Travis (which we use for some projects) you can pass in sensitive credentials via encrypted environment variables which you set using the Travis UI. Do you have equiv?

**Comment by mjy** [comment]
>  In Travis (which we use for some projects) you can pass in sensitive credentials via encrypted environment variables which you set using the Travis UI. Do you have equiv?

Aha!  If I use an encryted environment variable it should address my use of the API.  For others using the library I suppose they'd have to use the configuration options in the gem to do the same in CI.  But, if they don't, then you'll get unpolite hits, which you already have a mechanism for dealing with. This is sounding like the solution. 

Will look into it.

**Comment by gbilder** [comment]
Cool. I'm closing this. Reopen if this continues to be an issue.
