### ISSUE TITLE
Very high response times and timeouts on requests

### ISSUE THREAD

**Issue by MartinDobisch** [CrossRef/rest-api-doc#307]
Good morning,

we are experiencing high response times, when requesting the api.

for example:
https://api.crossref.org/works/10.1023/A:1010933404324
takes around 14 seconds or times out.

I verified, that the problem is not on our end, by requesting via several vpns and checking other pages for their response times.

Greetings

Edit: We did not notice it before this morning

**Comment by andremann** [comment]
Hi,

I had a similar problem and I noticed that following direction mentioned [here](https://github.com/CrossRef/rest-api-doc#good-manners--more-reliable-service) improved a lot the latency of my scripts.

In my case, adding the mail parameter worked like a charm! Hope this helps.

**Comment by jenniferlin15** [comment]
Thanks for alerting us to this performance instability issue, @MartinDobisch. As @andremann suggested, we recommend using the (open) dedicated pool for those who specify a User-Agent header that properly identifies the script or tool and provides a means of contacting you via email using "mailto:". https://github.com/CrossRef/rest-api-doc#good-manners--more-reliable-service

**Comment by jenniferlin15** [comment]
We're keeping an eye on the response times on the public server. We recommend the dedicated polite server for those who specify a user-agent header. Closing this ticket for now.

**Comment by xg1990** [comment]
Hi 
Thanks so much for providing this service!
I have provided my email but still have very long latency. Is the dedicated pool experiencing huge workload?
