### ISSUE TITLE
Leading or trailing and/or in query.bibliographic queries result in invalid solr queries

### ISSUE THREAD

**Issue by denizk** [CrossRef/rest-api-doc#308]
Requests like https://api.crossref.org/v1/works?rows=1&query.bibliographic=23RD+INTERNATIONAL+TECHNICAL+MEETING+OF+THE+SATELLITE+DIVISION+OF+THE+INSTITUTE+OF+NAVIGATION%2C+PORTLAND%2C+OR result in an invalid solr query `(*:*) AND (content_citation:(23RD INTERNATIONAL TECHNICAL MEETING OF THE SATELLITE DIVISION OF THE INSTITUTE OF NAVIGATION  PORTLAND  OR))`.

Seems this is due to trailing `OR`. It also occurs with leading or trailing AND/ORs.  

While most special lucene query characters are removed in the submitted query string, it seems I can submit a quoted query, so the following request works https://api.crossref.org/v1/works?rows=1&query.bibliographic=%2223RD%20%22INTERNATIONAL%20TECHNICAL%20MEETING%20OF%20THE%20SATELLITE%20DIVISION%20OF%20THE%20INSTITUTE%20OF%20NAVIGATION%2C%20PORTLAND%2C%20OR%22 (even when quotes are unbalanced).

Should I submit quoted queries or is it intended that users should be able to submit arbitrary query strings?

**Comment by gbilder** [comment]
Hi. So this is definitely a bug, but a quick workaround is to lowercase your queries. This, for example, works:

https://api.crossref.org/v1/works?rows=1&query.bibliographic=23rd+international+technical+meeting+of+the+satellite+division+of+the+institute+of+navigation%2c+portland%2c+or

**Comment by jenniferlin15** [comment]
Fixed and deployed
