### ISSUE TITLE
Problem with retrieving work language 

### ISSUE THREAD

**Issue by JavaHussar** [CrossRef/rest-api-doc#309]
Hi. I'm have been trying to retrieve work details via Crossref rest api using doi. The problem is that I need to retrieve document language and, as far as I know, it is impossible. Did anyone resolve similar problem, or maybe do you know how could I get work (or journal) language? 
Thank you

**Comment by JavaHussar** [comment]
@kjw

**Comment by JavaHussar** [comment]
@kjw

**Comment by jenniferlin15** [comment]
Language is an element that resides at the journal level and we are working to get that inserted into REST API. (ETA ~January). Thank you for your patience and for your message.

**Comment by ppolischuk** [comment]
@JavaHussar This should be available now, at least for works where we have the data. See the "language" field here: https://api.crossref.org/works/10.1371/journal.pone.0067380

Closing this for now, but let us know if we can be of assistance.
