### ISSUE TITLE
bioRxiv DOIs not recognised (at least by Mendeley Desktop)

### ISSUE THREAD

**Issue by robjohnnoble** [CrossRef/rest-api-doc#313]
Mendeley Desktop (version 1.17.12; Mac OSX Sierra 10.12.6) does not recognise the DOIs of bioRxiv preprints (regardless of when the preprint was posted). Searching by DOI returns the error "Lookup Failed". (After I raised this issue on twitter, @jenniferlin15 requested I submit it here.)

**Comment by jenniferlin15** [comment]
Thanks for creating the ticket so we know about this bug. Preprints are a different content type than Journal articles, so Mendeley may not be extracting the metadata properly from the JSON results. We will attempt to contact their technical support now and help sort out how they're pulling the data, but it would be helpful if you also logged the issue directly with them.

**Comment by jenniferlin15** [comment]
@robjohnnoble: does this also occur when you search by DOI for other preprints such as this one: doi.org/10.20944/preprints201711.0182.v1 (MDPI preprint)

**Comment by robjohnnoble** [comment]
Yes, search by DOI also fails for the preprint in your example. Thanks for following this up!

**Comment by jenniferlin15** [comment]
Confirming that upon investigation it looks like an issue with the Mendeley desktop app. It is also failing for a number of DOIs, including DataCite DOIs. We've relayed it to our contacts there, but we encourage users to also reach out to them directly as well.

**Comment by naarkhoo** [comment]
I have the same problem even with https://doi.org/10.20944/preprints201711.0182.v1

**Comment by cgorgulla** [comment]
Same problem with all bioRxiv papers using Mendeley Desktop.

**Comment by manusmad** [comment]
Problem confirmed

**Comment by katiematho** [comment]
problem still unresolved!

**Comment by amroco** [comment]
Issue appears to still be unresolved for Mendeley Desktop for non-preprint DOIs also (inputting the DOI during manual reference entry)
