### ISSUE TITLE
Member with no prefixes

### ISSUE THREAD

**Issue by gbilder** [CrossRef/rest-api-doc#316]
The `prefix` element for member 144 (Mineralogical Society) is set to `null`

**Comment by ckoscher** [comment]
Mineralogical Society is member ID 7149 and has prefix 10.1180
 (from source data http://doi.crossref.org/getPrefixPublisher , which does not contain member  id 144)

API lists Mineralogical Society correctly under ID 7149

Theory: Mineralogical Society was recreated in Sugar and 10.1180 was assigned. Old Sugar entry (id 144) became deprecated. rest-api is not deleting internal records (Mongo) for source records that get deleted.

**Comment by ppolischuk** [comment]
Closing as dupe to #291
