### ISSUE TITLE
Any way to get number of pages?

### ISSUE THREAD

**Issue by psavery** [CrossRef/rest-api-doc#318]
[Link to Example Article](http://api.crossref.org/works/10.1103/physrevmaterials.1.014602/)

Sometimes, in the bibtex, authors wish to cite the page numbers of an article as the article number and then page numbers in parentheses like: "014602 (1-6)". I've been trying to figure out how to do this with CrossRef.

I'd prefer to use the [bibtex version](http://api.crossref.org/works/10.1103/physrevmaterials.1.014602/transform/application/x-bibtex) of CrossRef, but it does not include the article number as the page number.

So I was thinking about creating my own bibtex entry with the json CrossRef (the link at the top is the json version) so that I can do the page numbers as given above. I see that "014602" is included in the json version of the example as the "article-number" entry. However, the number of pages (1-6) does not appear to be anywhere.

Is there any chance that we can get either the page numbers or the number of pages in entries such as this for the json CrossRef?

**Comment by jenniferlin15** [comment]
Thanks for the note - good idea! This is a feature request for page numbers in Crossref's content negotiation implementation for bibtex ([documentation](https://citation.crosscite.org/docs.html). I've added it to our backlog.

**Comment by psavery** [comment]
Okay! Yeah, it would be nice if we had it for the bibtex. But I'd say it's more important that the page numbers be included in the basic json. Note that the [json link](http://api.crossref.org/works/10.1103/physrevmaterials.1.014602/) I gave does not include the page numbers (1 - 6) in it.

**Comment by jenniferlin15** [comment]
Page numbers are included in the JSON if the publisher has deposited it. Please see this example: http://api.crossref.org/works/10.1084/jem.20151673

**Comment by psavery** [comment]
Okay. Let me clarify. I do know that page numbers are generally available on CrossRef (and they show up in the bibtex). But for journals that use article numbers, the page numbers never show up. 

[Here](https://journals.aps.org/prl/) is an example of one such journal. Note that all of them use an article number instead of a continuous set of page numbers because it is an electronic-only journal.

Some citation styles ([APA - for instance](http://blog.apastyle.org/apastyle/2015/05/how-to-cite-an-article-with-an-article-number-instead-of-a-page-range.html)) recommend that you put down the page numbers anyways - even though it only has an article number (and I frequently work with journals that still want the page numbers even if the journal uses article numbers). [Here](http://api.crossref.org/works/10.1371/journal.pone.0115434) is the first example that they give in that APA article, which would have page numbers (1-8). And for [this](http://api.crossref.org/works/10.1103/physrevmaterials.1.014602/) example that I gave earlier, it would have page numbers (1-6).

Because these citations that only use an article number always start on page number 1, you don't even need to know the first page number. You just need to know the number of pages. So if I knew that [this](http://api.crossref.org/works/10.1103/physrevmaterials.1.014602/) article had 6 pages, I could confidently say page numbers (1-6).

The problem is that the json for these articles that use article numbers never give the number of pages - and they never give the page numbers. So we can't extract them and we have to look them up manually.

[Here](http://api.crossref.org/works/10.1038/srep37694), [here](http://api.crossref.org/works/10.1103/physrevb.92.214106), and [here](http://api.crossref.org/works/10.1103/physrevb.95.054105) are more examples of this being true. Note that they all have something in common: they all have article numbers, but none of them give the number of pages nor the page numbers.

Now I'm not sure if adding page numbers to articles that use article numbers is something you guys can do or not. If you can't, it's alright. It would just be nice to not have to look up the page numbers for all of these types of articles...

**Comment by ckoscher** [comment]
We (Crossref) can not add page numbers. Only the depositing publisher 
can do so.

Chuck
