### ISSUE TITLE
Weird agency

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#319]
hmm, is the agency given back here wrong? it seems like it is:

`curl -v http://api.crossref.org/works/10.5167/UZH-30455/agency | jq .`

```json
{
  "status": "ok",
  "message-type": "work-agency",
  "message-version": "1.0.0",
  "message": {
    "DOI": "10.5167/uzh-30455",
    "agency": {
      "id": "10.SERV/ETH",
      "label": "10.SERV/ETH"
    }
  }
}
```

**Comment by ckoscher** [comment]
This is a weird bug.  api.crossref.org depends on other backend service to provide this data
Run by us: https://doi.crossref.org/doiRA/10.5167/UZH-30455
Run by DOI: http://doi.org/doiRA/10.5167/UZH-30455

Both do the same thing, and both return the expected data.

Other DOIs work fine in the api (this is another DataCite DOI)
http://api.crossref.org/works/10.11578/dc.20171025.1651/agency

This problem appears to afflict the prefix 10.5167

**Comment by ckoscher** [comment]
Correction:  api.crossref.org appears to have (long ago) internally implemented the RA determination using a now outdated approach.  The 2 services I mention above use a different approach that extract the name from handle data directly.

**Comment by jenniferlin15** [comment]
@ckoscher: so this is due to differences in RA and not a Crossref bug?

**Comment by ckoscher** [comment]
No its a Crossref bug (in the api).

**Comment by jenniferlin15** [comment]
Noted. Adding this to bug list.

**Comment by sckott** [comment]
thanks @ckoscher and @jenniferlin15 !
