### ISSUE TITLE
Are publishing dates updated?

### ISSUE THREAD

**Issue by de-code** [CrossRef/rest-api-doc#321]
Hi,

Can I assume that publishing dates never change or do they get updated?
(I am looking for a reasonable way to partition the data and look for updated works only within that partition)

Thank you

**Comment by pdavis8** [comment]
Hello, 

Thanks for your query. 

The publication date shouldn't change on an article, you might find that there are two dates, one being the print publication date and the other being the online publication date but as long as you select the correct one each time then this would be a good way to partition the data. 

You can also sort the data in the partition using the updated value if this would help to see the most recent updates. See here: https://github.com/CrossRef/rest-api-doc#sorting

I hope this helps and please do come back to me should you have any further questions.

Thanks,
Paul

**Comment by de-code** [comment]
Thank you for the response Paul.

You mentioned the different types of publication dates:
Which one is used for the `published` facet and the `from-pub-date` / `until-pub-date` filter? The earliest of the two? (it does mention something about earliest in the docs of the facet)

**Comment by pdavis8** [comment]
Yes it should be the earliest date that is listed.
