### ISSUE TITLE
Query containing composite strings

### ISSUE THREAD

**Issue by ulli-steiner** [CrossRef/rest-api-doc#333]
I am trying to search for all records that contain my institute as affiliation:

https://api.crossref.org/works?query.affiliation=Adolphe+Merkle

Unfortunately, the plus sign signifies an "or" and this command returns also records with on of the above words.  As already explained in issue #311, there is currently no way to search for "Adolphe" and "Merkle". My question:

Is there a way to search for the string"Adolphe Merkle", including he space between the two words?

Thanks,

Ulli

**Comment by gbilder** [comment]
I'm afraid not. We don't support phrase searches.  Instead you need to use a combination of looking at the score and seeing if the phrase exists in any of the the affiliation strings.

This is one of the reasons we are so keen to implement organisation identifiers:

https://www.crossref.org/categories/organization-identifiers/

**Comment by ulli-steiner** [comment]
Geoffrey,

yes, organisation identifiers are much needed.  Is there a timeline for this?

Best wishes,

Ulli
