### ISSUE TITLE
restricting https post to https://search.crossref.org/links using query.bibliographic

### ISSUE THREAD

**Issue by jhpoelen** [CrossRef/rest-api-doc#334]
Related to https://github.com/jhpoelen/eol-globi-data/issues/338 and https://github.com/CrossRef/rest-api-doc/issues/170#issuecomment-296998085 .

I am trying to figure out how to limit https post to https://search.crossref.org/links  to only use query.bibliographic type queries.

What is the way to do this for post requests?

**Comment by gbilder** [comment]
Hi. You don't use POST as you are using an API and not a form. Instead you use GET. So, for example:, for this reference:

```
Neylon, C., Pattinson, D., Bilder, G., & Lin, J. (2016). On the origin of nonequivalent states: how we can talk about preprints.
```

http://api.crossref.org/works?query.bibliographic=Neylon,%20C.,%20Pattinson,%20D.,%20Bilder,%20G.,%20%20Lin,%20J.%20(2016).%20On%20the%20origin%20of%20nonequivalent%20states:%20how%20we%20can%20talk%20about%20preprints.

And remember to escape your query parameters. :-)

**Comment by jhpoelen** [comment]
hey @gbilder - thanks for replying.

Not quite sure what you mean by ```You don't use POST as you are using an API and not a form```. 

As far as I can tell, I am using POST requests to access an api and get some results. 

From https://github.com/jhpoelen/eol-globi-data/blob/1fa7215045efc8a9e256fe2ad5845a41bf77cdf8/eol-globi-neo4j-index/src/main/java/org/eol/globi/service/DOIResolverImpl.java#L53 :

```java
 ObjectMapper mapper = new ObjectMapper();
        HttpPost post = new HttpPost(baseURL);
        post.setHeader("Content-Type", "application/json");
        StringEntity entity = new StringEntity(mapper.writeValueAsString(references), "UTF-8");
        post.setEntity(entity);

        BasicResponseHandler handler = new BasicResponseHandler();
        String response = HttpUtil.getHttpClient().execute(post, handler);
```

where baseUrl is ```https://search.crossref.org/links``` and entity is a list of citations, newline separated, to be resolved.

Our use case is to resolve thousands of (likely) bibliographical citations, so I figured that a batch request is a little more friendlier than issues thousands of http get requests (one per citation). 

Perhaps you can give some advise on how to use your apis in this scenario.

Thanks for your useful service . . .
