### ISSUE TITLE
Getting significantly less rows on crawling than that shown in total results

### ISSUE THREAD

**Issue by pratima-innoplexus** [CrossRef/rest-api-doc#335]
Hi,
I am trying to use the API to get all the publications for a particular date. The output of the [query ](http://api.crossref.org/works?filter=from-pub-date:2018-02-06,until-print-pub-date:2018-02-06&cursor=*) shows the count of the total results as 24588 but when crawled, I am getting only 7100 rows of publications. I have tried both offset and next-cursor method but have only failed to get the total number of counts as shown in total results. How can I get this issue resolved?

**Comment by gbilder** [comment]
Hi. I can't replicate your problem. When I run the script below, the total-results matches the number of records actually retrieved (24571 : 24571)

Each cursor will return multiple records. You are adding up `items` to get your rows, right?

```
import sys
from crossref.restful import Works, Etiquette

works = Works()
## Fill in missing info and uncomment follwing two lines to be 'polite'
# etiquette = Etiquette("Cursor Test","<app-url>","<email>")
# works = Works(etiquette=etiquette)

filter = {'from-pub-date':'2018-02-06' , 'until-print-pub-date':'2018-02-06'}

expected_count = works.filter(**filter).count()

count = 0
for i in works.filter(**filter):
    print(str(count) + " : " + i['DOI'])
    count += 1

print(str(expected_count) + " : " + str(count))
```

**Comment by ppolischuk** [comment]
Since we were unable to reproduce and haven't heard back, I'm closing this ticket for now. Please let us know if there's more we can do to help, @pratima-innoplexus.
