### ISSUE TITLE
Cursor giving inconsistent results

### ISSUE THREAD

**Issue by joker-22** [CrossRef/rest-api-doc#336]
http://api.crossref.org/works?query.affiliation=indian%20institute%20of%20science&cursor=*&rows=1000
is giving results where the works are not affiliated to Indian institute of Science.Please look into this matter as soon as possible.

**Comment by gbilder** [comment]
Hello. Note that affiliation queries will almost always return *something* as they do not do exact phrase matching.  You need to look at the score and set a cutoff threshold. The best score in the result set above is `1.5979666`which would indicate that it is not a match to be confident of (nor are any of the others.

Contrast to this search where the return score is `3.59`.

http://api.crossref.org/works?query.affiliation=Department%20of%20Geology%20and%20Geophysics;%20Yale%20University;%20New%20Haven%20CT%20USA&cursor=*&rows=1

You will probably need to do a bit of experimentation to determine an appropriate cutoff score. But even here, you are likely to get results of varying quality. This is why we are working on developing organisational identifiers for affiliation data as described here:

https://www.crossref.org/categories/organization-identifiers/
