### ISSUE TITLE
Missing metadata in REST API - journal content

### ISSUE THREAD

**Issue by jenniferlin15** [CrossRef/rest-api-doc#338]
We have a number of missing metadata that are not getting included into the REST API output. (They are exposed in other supported APIs including OAI-PMH and XML API.) This ticket is for the journal content type only.

Complete Crossref output schema is located here: http://data.crossref.org/reports/help/schema_doc/unixref1.1/unixref1.1.html

Missing metadata: 
Journal level - language
Volume level - volume number
Issue level - issue number, issue publication date (print and online)
Article level - access indicators > free_to_read (start and end dates)

Sample input XML and sample output JSON in the doc:
https://docs.google.com/document/d/101jZK8We5vNp31alp95hTX1J-cSC_St_ktKr1a2NPs4

**Comment by gbilder** [comment]
Just so there isn't confusion- the JSON output for the API is based on `UNIXSD`, not `UNIXREF`

https://support.crossref.org/hc/en-us/articles/213531266-UNIXSD-query-output-format
http://data.crossref.org/reports/help/schema_doc/crossref_query_output3.0/output.html

**Comment by jenniferlin15** [comment]
fix deployed
