### ISSUE TITLE
\u03b at the beginning of the titles of some journals

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#346]
- https://api.crossref.org/journals/2030-0441
- https://api.crossref.org/journals/2040-0098
- https://api.crossref.org/journals/2040-0101
- https://api.crossref.org/journals/2040-0128
- https://api.crossref.org/journals/2040-0195
- https://api.crossref.org/journals/2050-0122

**Comment by moqri** [comment]
\u03b at the beginning of the title of some of them

**Comment by afandian** [comment]
`\u03b1` is the JSON representation of the "alpha" character. Reference: https://unicode.org/charts/PDF/U0370.pdf

**Comment by pdavis8** [comment]
Hello, 
It can help to have a JSON viewer extension or plugin for your browser, it can make viewing the JSON output much neater and you would see the correct character instead of the encoding.
I shall close this for now but if you have any other questions, feel free to re-open this.
