### ISSUE TITLE
Some ISSNs might be linked to incorrect journals

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#348]
It seems https://api.crossref.org/journals/2325-5161
refers to http://journals.sagepub.com/home/aip (based on title and publisher)

while it should refer to https://www.tandfonline.com/action/journalInformation?journalCode=uare20 (based on ISSN)

**Comment by ckoscher** [comment]
Fixed. Should propagate in a day

**Comment by moqri** [comment]
There are more instances of this issue. For example 

https://api.crossref.org/journals/1234-5678 is referring to https://academic.oup.com/plms but it seems not correct. 

If you let us know the reason why the last one and this one are incorrectly assigned maybe we can find other instances of this issue.

**Comment by ckoscher** [comment]
Most likely caused by a publisher making an incorrect deposit some where in the past. That would place an incorrect ISSN against their title. "Art Education" has only ISSN 0004-3125, in our system, so no error was produced when the mistaken deposit took place.
