### ISSUE TITLE
Inconsistent results by two different queries for same thing

### ISSUE THREAD

**Issue by arf1372** [CrossRef/rest-api-doc#35]
When query this:
    http://api.crossref.org/works?filter=type:journal&rows=0
the total number of results found by system is `16267` but the query of form
    http://api.crossref.org/journals?rows=0
yields in `37086` total results! So as I requested for journals in both queries (is my assume correct?? I'm querying same thing?), why two query for same thing yields in different results??

**Comment by kmeddings** [comment]
Recommend that the /journals route is used for total journals. As this has not been raised since am closing.
