### ISSUE TITLE
Polite service credentials

### ISSUE THREAD

**Issue by Deyter** [CrossRef/rest-api-doc#350]
I have a question about specify mail in the requests.
If I have send in request header one mail and other mail in the query, which of this will be used to inform me about script problems?
What if I will use Plus service and send the token (I think that Plus service account has contact mail in user information) in addition to this two mail addresses?

**Comment by jkcrossref** [comment]
If you use different emails, we will try them both. Just curious, why use more than one email? 
If you use a Plus token, we still encourage polite use and will use those same email(s). We might try the account's technical contact if we couldn't reach the other email(s).

**Comment by Deyter** [comment]
Request header email can be of the service administrator. Query email can be of the service user(optional).
If a user of service has a problem he can need to have information about it.
I'm not sure. Library in developing state only.

**Comment by ppolischuk** [comment]
This looks to have been resolved. Closing, but happy to reopen if any problems or questions persist.
