### ISSUE TITLE
Missing subtitles for Oxford University Press

### ISSUE THREAD

**Issue by danielopitz** [CrossRef/rest-api-doc#352]
Subtitles for Oxford University Press books / monographs seem to be missing from some records. DOIs starting with `10.1093/acprof:oso` seem to be OK.

Example:
http://api.crossref.org/works/10.1093/0198294956.001.0001 vs.
http://www.oxfordscholarship.com/view/10.1093/0198294956.001.0001/acprof-9780198294955

Especially confusing example:
http://api.crossref.org/works/10.1093/019924958X.001.0001 vs.
http://www.oxfordscholarship.com/view/10.1093/019924958X.001.0001/acprof-9780199249589
and
http://api.crossref.org/works/10.1093/0199249598.001.0001 vs.
http://www.oxfordscholarship.com/view/10.1093/0199249598.001.0001/acprof-9780199249596

Example with subtitle included:
http://api.crossref.org/works/10.1093/acprof:oso/9780199682447.001.0001 vs.
http://www.oxfordscholarship.com/view/10.1093/acprof:oso/9780199682447.001.0001/acprof-9780199682447

**Comment by pdavis8** [comment]
Hello,

Crossref metadata is supplied to us by the publishers and in these instances it looks like the subtitles were not for some of them.

I will reach out to the publishers and ask them to update the metadata that we have here.

Thanks,
Paul

**Comment by pdavis8** [comment]
I have chased this up again with the publishers. Closing now and will continue to chase through my open ticket.
