### ISSUE TITLE
Journals with multiple titles

### ISSUE THREAD

**Issue by moqri** [CrossRef/rest-api-doc#353]
e.g. https://api.crossref.org/journals/0095-9774
returns the title="Journal of Oil & Fat Industries"

but also returns the title = "The Chemist’s Section of the Cotton Oil Press" only with https://api.crossref.org/journals/ . It seems currently there is no way to get the second title of the journal directly with https://api.crossref.org/journals/0095-9774

**Comment by pdavis8** [comment]
Hello, sorry for the delay in reply we are just looking into this at the moment and when I have further information I will get back to you.

**Comment by pdavis8** [comment]
So after looking into this further, we have found that there has been a long history of title changes with this journal, not always following the correct ISSN either. It is hard to piece it all together as publishers can redeposit metadata to us that may or may not accurately correspond to the ISSN/title history.
This query https://api.crossref.org/journals/0095-9774 is now not returning the title "Journal of Oil & Fat Industries", it is now showing "The Chemist’s Section of the Cotton Oil Press".
