### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by acmccorm** [CrossRef/rest-api-doc#359]
I am writing code to recursively retrieve DOIs for a given EISSN.

For example:
http://api.crossref.org/journals/2053-1583/works?select=DOI&mailto=acmccorm@ucsc.edu&cursor=*

gives me the following cursor:
AoJ47ePmrt8CPw9odHRwOi8vZHguZG9pLm9yZy8xMC4xMDg4LzIwNTMtMTU4My8zLzMvMDM1MDIz

The next cursor also works: 
AoJzr5ipr98CPwtodHRwOi8vZHguZG9pLm9yZy8xMC4xMDg4LzIwNTMtMTU4My9hYTdhZDg=

But once I get this cursor:
AoJ5+Pjqr98CPw9odHRwOi8vZHguZG9pLm9yZy8xMC4xMDg4LzIwNTMtMTU4My8zLzIvMDI1MDI2

Python returns this error:
urllib2.HTTPError: HTTP Error 500: Internal Server Error 

and the webpage: 
http://api.crossref.org/journals/2053-1583/works?select=DOI&mailto=acmccorm@ucsc.edu&cursor=AoJ5+Pjqr98CPw9odHRwOi8vZHguZG9pLm9yZy8xMC4xMDg4LzIwNTMtMTU4My8zLzIvMDI1MDI2

itself begins with {"status":"error","message-type":"exception"

After trials with a couple different journals I have noticed that this always occurs when there is a "+" character in the cursor. Could this actually be the issue or am I making an error I don't know about?

**Comment by danielopitz** [comment]
You should urlencode the cursor. Assuming Python 3:
```
>>> import urllib.parse
>>> urllib.parse.quote_plus('AoJ5+Pjqr98CPw9odHRwOi8vZHguZG9pLm9yZy8xMC4xMDg4LzIwNTMtMTU4My8zLzIvMDI1MDI2')
'AoJ5%2BPjqr98CPw9odHRwOi8vZHguZG9pLm9yZy8xMC4xMDg4LzIwNTMtMTU4My8zLzIvMDI1MDI2'
```

**Comment by acmccorm** [comment]
@danielopitz,

Thank you for your comment. My issue is now resolved.

**Comment by jenniferlin15** [comment]
Thanks, @danielopitz!
