### ISSUE TITLE
Sample filter doesn't work for journals

### ISSUE THREAD

**Issue by arf1372** [CrossRef/rest-api-doc#36]
When I query like
    http://api.crossref.org/journals?sample=100
three things happen:  
1. The results are deterministically predictable.
    1.5. The results are started from beginning of the journals sorted alphabetically!
    2. There just 20 rows of results! but appending `rows=100` yields in first 100 journals in database!!

**Comment by sckott** [comment]
Is it true that `sample` only works for `/works` requests? AFAICT `sample` doesn't work with any routes except `/works`
