### ISSUE TITLE
No ISSNs provided by journals endpoint?

### ISSUE THREAD

**Issue by dhimmel** [CrossRef/rest-api-doc#361]
I made an API call to https://api.crossref.org/journals, which by default returned 20 journals. Every journal in this set of 20 did not have ISSN information (they had the ISSN key-value pair but the value was an empty list.

See for example:

```json
{
    "last-status-check-time": null,
    "counts": null,
    "breakdowns": null,
    "publisher": "Elsevier ",
    "coverage": null,
    "title": "Advances in Botanical Research",
    "subjects": [],
    "flags": null,
    "ISSN": [],
    "issn-type": []
},
```

I haven't looked exhaustively whether no journals return ISSNs, but I'd expect the ISSN information to be much more prevalent?  @jenniferlin15 any ideas on what could be going on?

CC @jpolka as this relates to her question in https://github.com/transpose-publishing/policies-database/issues/1#issuecomment-385715415.

**Comment by dhimmel** [comment]
The ISSN for "Advances in Botanical Research" is `0065-2296`. Note that https://api.crossref.org/journals/0065-2296 returns `Resource not found.`, so perhaps these ISSNs just don't exist in Crossref's database?

**Comment by pdavis8** [comment]
Hello,
Having just checked on our database here, there are no ISSNs associated with that title for some reason. I will chase up with the publisher to have the ISSNs redeposited with us.
It should be rare that ISSNs are not attached to a title and so I will look into this further and contact the relevant publishers.
There is a full title list that we have which might be of use to you: https://www.crossref.org/titleList/
Here is a call to the API for journals selecting just a few components which might be helpful.
Thanks for bringing this to our attention.

**Comment by dhimmel** [comment]
> Having just checked on our database here, there are no ISSNs associated with that title for some reason

Interesting. The API must have first returned journals without ISSNs.

> Here is a call to the API for journals selecting just a few components which might be helpful.

I think the link is missing from your comment.

> There is a full title list that we have which might be of use to you: https://www.crossref.org/titleList/

That is helpful, especially the CSV at `http://ftp.crossref.org/titlelist/titleFile.csv`.

Nothing outstanding on my end so @pdavis8 feel free to close this issue as you wish.
