### ISSUE TITLE
Correlations between input schemas and JSON output?

### ISSUE THREAD

**Issue by daisieh** [CrossRef/rest-api-doc#363]
I apologize if this is a dumb question, but is there documentation on what all the fields that come out of the REST API's output mean, and how they correlate to elements of the input schema? 

Recently, we were discussing the `elocation-id` input element with eLife, and they were unclear as to how that would map to the output element I often see, which is `article-number`. 

Even more recently, I couldn't find firm documentation telling me which of the possible date results I get in a result, like `created`, `published-online`, `deposited`, `issued`, etc. mean. I can sort of guess based on context, but I would like to know for sure that the values mean what I think they mean, and whether or not the various fields are always present in a result or not.

What am I missing? Can someone help me find this documentation?

**Comment by pdavis8** [comment]
Hello,
I think this is the document that you are looking for: https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md 
With regards to the ```elocation-id``` and ```article-number```, they are the same thing but ```elocation-id``` is what it is referred to in JATS and we have labelled it as ```article-number``` in the API.

**Comment by daisieh** [comment]
Yes, thank you!! I don't know why I couldn't think to look at the contents of the directory instead of just in the readme.
