### ISSUE TITLE
ISSN's that don't exist

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#37]
Whenever an ISSN is not found/doesn't exist, the same result returns. For example: 

http://api.crossref.org/journals/asdfasfaslfjsajaslfasjjksladf

gives a result, where the `ISSN` value is `""`. 

Is this by design?  I would think that `asdfasfaslfjsajaslfasjjksladf` would return a `404` maybe?

**Comment by kjw** [comment]
Now results in 404.

**Comment by sckott** [comment]
:rocket:
