### ISSUE TITLE
Question: Cited-by search

### ISSUE THREAD

**Issue by IAF-ChristianPommer** [CrossRef/rest-api-doc#374]
Is it possible or planned to allow a search for references or documents referencing a specific document?
This would greatly improve the creation of reference maps.

**Comment by marcomarsella** [comment]
This would be very useful for me too! Please advise.

**Comment by pdavis8** [comment]
We do allow searches for the *counts* against a DOI for cited by but at the moment there is no way in the REST API to search for cited by metadata for *works*, as members can only retrieve cited-by metadata for their own content. 
More information can be found here: https://www.crossref.org/services/cited-by/

**Comment by zuphilip** [comment]
Not from Crossref, but from @OpenCitations there is COCI, the OpenCitations Index of Crossref open DOI-to-DOI references, cf. this blogpost https://opencitations.wordpress.com/2018/07/12/coci/ which allows such queries on the open part of the Crossref citation data.

**Comment by ynnig** [comment]
Yes as zuphilip explains... @opencitations is a subscriber of our Metadata Plus service, which also includes 'limited' references in addition to open ones available in the Public REST API (in addition to service-level stuff like more predictable performance of the API. 'Limited' is the default setting for most members. More about that setting here: https://www.crossref.org/reference-distribution/ and about our Plus service here: https://www.crossref.org/services/metadata-delivery/plus-service/
