### ISSUE TITLE
Exact Matching Query / Phrase Query

### ISSUE THREAD

**Issue by keanelyx** [CrossRef/rest-api-doc#377]
Hi, I would like to know if it is possible to perform exact matching query or search using a 'phrase'? For example, I would like to get the results for 'waste water treatment' however, many of the results returned are not related, being included because of the word 'treatment' such as medical journals etc. 

Thanks for the assistance.

**Comment by yadurvt** [comment]
https://search.crossref.org/dois?q=Capacitive-Gap Filters for Millimeter Waves.(Title)
https://search.crossref.org/dois?q=10.1002/9780470294178.ch5(DOI)

Use this url instead. it manage all data with a single URL.

**Comment by pdavis8** [comment]
The REST API doesn't perform exact matching with titles at the moment, it will return all results based on each word being searched against. However the more words returned in a search result will mean a higher score so the results linked closest to the search should appear at the top of the list.
