### ISSUE TITLE
Unixsd format not available for DOIs with plus sign. 

### ISSUE THREAD

**Issue by kuraju** [CrossRef/rest-api-doc#38]
I think access to unixsd format  does not work for DOIs with plus sign at the end:
http://api.crossref.org/works/v1/10.1021/ac010694+ is ok,
 but 
http://api.crossref.org/works/v1/10.1021/ac010694+.xml
(as /works/v1/10.1021/ac010694+/transform/application/vnd.crossref.unixsd+xm) 
  return HTTP 404 resource not found.

**Comment by gbilder** [comment]
Hi. You need to url-encode the DOI. We have updated docs to make this clearer.

http://api.crossref.org/works/10.1021/ac010694+/transform/application/vnd.crossref.unixsd+xml
