### ISSUE TITLE
What do the created, deposited, indexed, issued, and published-print properties refer to?

### ISSUE THREAD

**Issue by GaurangTandon** [CrossRef/rest-api-doc#381]
I have been unable to find information for these in the [official documentation](https://github.com/CrossRef/rest-api-doc). I was hoping for a bit of disambiguation between these properties as they all seem almost the same.

As far as I can guess, `published-print` refers to when the research paper was actually published in the journal, so that may be as old as 1960s or beyond. The `created`, `deposited`, `indexed` refer to dates on which that research paper got a Crossref entry, though I am not sure. Also, I've no clue about `issued`. Could you please clarify?

I need to know this because I am trying to generate citations for research papers given their DOIs (for example, [*J. Am. Chem. Soc.* **1959,** *81* (23), 6338–6339.](https://doi.org/10.1021/ja01532a066)).  Currently, I was using the `published-print` property to get the correct date. However, for some research papers like [this one](http://pubs.rsc.org/en/content/articlelanding/2016/cc/c5cc08252h), the `published-print` is undefined (it instead has the `published-online` property - which is inaccurate (the paper was published on 23/10/2015, but `published-online` states `2016` instead)).

**Comment by pdavis8** [comment]
Further information on these terms and what they mean can be found here: https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md#work

**Comment by pdavis8** [comment]
I am going to close this ticket now but if you have any further questions then please do let us know.
