### ISSUE TITLE
Page numbers missing for Conference Proceedings content

### ISSUE THREAD

**Issue by jenniferlin15** [CrossRef/rest-api-doc#383]
For example, see conference paper 10.7551/ecal_a_001 

In REST API: http://api.crossref.org/works/10.7551/ecal_a_001

In XML API: http://doi.crossref.org/search/doi?pid=support@crossref.org&format=unixsd&doi=10.7551/ecal_a_001

REST API results do not include page numbers, while XML results include:

<pages>
<first_page>1</first_page>
<last_page>1</last_page>
</pages>

Contrasting example for journal content in REST API
http://api.crossref.org/works/10.1080/00295639.2017.1332892

Results includes:

“page”: “102-107",

**Comment by ppolischuk** [comment]
See #343

**Comment by ppolischuk** [comment]
Included this info in #343, closing this one.
