### ISSUE TITLE
Error for some DOI in the Json format returned by the API

### ISSUE THREAD

**Issue by Jusushin** [CrossRef/rest-api-doc#389]
Hi,

I used the API with the url "https://api.crossref.org/works/"+ DOI_ID to retrieve informations about articles, but for some cases, I get an error. Example below :
The Json obtained from this url https://api.crossref.org/works/10.1101/354969 returns an error (that was not the case some hours before) : 

stdClass Object ( [status] => ok [message-type] => work [message-version] => 1.0.0 [message] => stdClass Object ( [institution] => stdClass Object ( [name] => bioRxiv [place] => Array ( [0] => - ) [acronym] => Array ( [0] => - ) ) [indexed] => stdClass Object ( [date-parts] => Array ( [0] => Array ( [0] => 2018 [1] => 6 [2] => 25 ) ) [date-time] => 2018-06-25T09:10:27Z [timestamp] => 1529917827249 ) [posted] => stdClass Object ( [date-parts] => Array ( [0] => Array ( [0] => 2018 [1] => 6 [2] => 25 ) ) ) [group-title] => Bioinformatics [reference-count] => 0 [publisher] => Cold Spring Harbor Laboratory [content-domain] => stdClass Object ( [domain] => Array ( ) [crossmark-restriction] => ) [short-container-title] => Array ( ) [accepted] => stdClass Object ( [date-parts] => Array ( [0] => Array ( [0] => 2018 [1] => 6 [2] => 25 ) ) ) [abstract] => Biological timers synchronize patterning processes during embryonic development. In the Drosophila embryo, neural progenitors (neuroblasts; NBs) produce a sequence of unique neurons whose identities depend on the sequential expression of temporal transcription factors (TTFs). The stereotypy and precision of the NB lineages indicate reproducible temporal progression of the TTF timer. To examine the basis of this robustness, we combine theory and experiments. The TTF timer is commonly described as a relay of activators, but its regulatory circuit is also consistent with a repressor-decay timer, in which expression of each TTF begins once its repressor is sufficiently reduced. We find that repressor-decay timers are more robust to parameter variations compared to activator-relay timers. This suggests that the in-vivo TTF sequence progresses primarily by repressor-decay, a prediction that we support experimentally. Our results emphasize the role of robustness in the evolutionary design of patterning circuits. [DOI] => 10.1101/354969 [type] => posted-content [created] => stdClass Object ( [date-parts] => Array ( [0] => Array ( [0] => 2018 [1] => 6 [2] => 25 ) ) [date-time] => 2018-06-25T08:45:16Z [timestamp] => 1529916316000 ) [source] => Crossref [is-referenced-by-count] => 0 [title] => Array ( [0] => A repressor-decay timer for robust temporal patterning in embryonic Drosophila neuroblast lineages ) [prefix] => 10.1101 [author] => Array ( [0] => stdClass Object ( [ORCID] => http://orcid.org/0000-0003-1863-205X [authenticated-orcid] => [given] => Inna [family] => Averbukh [sequence] => first [affiliation] => Array ( ) ) [1] => stdClass Object ( [ORCID] => http://orcid.org/0000-0002-7531-283X [authenticated-orcid] => [given] => Sen-Lin [family] => Lai [sequence] => additional [affiliation] => Array ( ) ) [2] => stdClass Object ( [ORCID] => http://orcid.org/0000-0001-5980-8029 [authenticated-orcid] => [given] => Chris Q [family] => Doe [sequence] => additional [affiliation] => Array ( ) ) [3] => stdClass Object ( [ORCID] => http://orcid.org/0000-0002-2444-6061 [authenticated-orcid] => [given] => Naama [family] => Barkai [sequence] => additional [affiliation] => Array ( ) ) ) [member] => 246 [container-title] => Array ( ) [original-title] => Array ( ) [link] => Array ( [0] => stdClass Object ( [URL] => https://syndication.highwire.org/content/doi/10.1101/354969 [content-type] => unspecified [content-version] => vor [intended-application] => similarity-checking ) ) [deposited] => stdClass Object ( [date-parts] => Array ( [0] => Array ( [0] => 2018 [1] => 6 [2] => 25 ) ) [date-time] => 2018-06-25T08:45:16Z [timestamp] => 1529916316000 ) [score] => 1 [subtitle] => Array ( ) [short-title] => Array ( ) [issued] => stdClass Object ( [date-parts] => Array ( [0] => Array ( [0] => 2018 [1] => 6 [2] => 25 ) ) ) [references-count

A technical error has occured (code: 0). Sorry for this inconvenience.

I get the same error with others DOI_ID, for example : 10.1101/102681.

**Comment by pdavis8** [comment]
Hello,
Is this error still occurring? I am not able to replicate this here and hopefully this was a temporary bug.
I shall close the ticket for now but if you still have issues then please do reopen.
