### ISSUE TITLE
Kudos LUP DOIs - server error (505)

### ISSUE THREAD

**Issue by loupeck** [CrossRef/rest-api-doc#39]
@kjw I wonder if you can help - I have reprocessed the same DOI file a few times now in Kudos and these DOIs keep coming back as 'Server Error' from the CrossRef API, please can you tell me if there are specific issues with these DOIs and why they won't load?

DOI Server Error for 10.3828/bhs.2014.27	
ERROR	DOI Server Error for 10.3828/eir.2014.21.1.5	
ERROR	DOI Server Error for 10.3828/extr.2014.14	
ERROR	DOI Server Error for 10.3828/extr.2014.14	
ERROR	DOI Server Error for 10.3828/extr.2014.7	
ERROR	DOI Server Error for 10.3828/franc.2014.8	
ERROR	DOI Server Error for 10.3828/idpr.2014.19	
ERROR	DOI Server Error for 10.3828/jlcds.2014.18	
ERROR	DOI Server Error for 10.3828/lhr.2014.12	
ERROR	DOI Server Error for 10.3828/mb.2014.14	
ERROR	DOI Server Error for 10.3828/mb.2014.18	
ERROR	Unregistered DOI for DOI 10.3828/qs.2014.8
ERROR	DOI Server Error for 10.3828/sfftv.2014.12	
ERROR	DOI Server Error for 10.3828/sj.2014.2	
ERROR	DOI Server Error for 10.3828/tpr.2014.22	
ERROR	DOI Server Error for 10.3828/tpr.2014.25	
ERROR	DOI Server Error for 10.3828/tpr.2014.38	
ERROR	DOI Server Error for 10.3828/bfarm.2007.3.1	
ERROR	DOI Server Error for 10.3828/bhs.2014.41	
ERROR	DOI Server Error for 10.3828/bhs.2014.41	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/cfc.2014.4	
ERROR	DOI Server Error for 10.3828/cfc.2014.6	
ERROR	DOI Server Error for 10.3828/cfc.2014.9	
ERROR	DOI Server Error for 10.3828/extr.2014.5	
ERROR	DOI Server Error for 10.3828/mb.2014.19	
ERROR	DOI Server Error for 10.3828/mb.2014.29	
ERROR	DOI Server Error for 10.3828/msmi.2014.1	
ERROR	DOI Server Error for 10.3828/msmi.2014.5	
ERROR	DOI Server Error for 10.3828/rs.2014.2	
ERROR	DOI Server Error for 10.3828/sfftv.2014.12	
ERROR	DOI Server Error for 10.3828/sj.2014.9b	
ERROR	DOI Server Error for 10.3828/tpr.2014.19	
ERROR	DOI Server Error for 10.3828/bj.2014.9	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/extr.2014.10	
ERROR	DOI Server Error for 10.3828/lhr.2014.8	
ERROR	DOI Server Error for 10.3828/mb.2014.15	
ERROR	DOI Server Error for 10.3828/mb.2014.16	
ERROR	DOI Server Error for 10.3828/mb.2014.19	
ERROR	DOI Server Error for 10.3828/mb.2014.19	
ERROR	DOI Server Error for 10.3828/mb.2014.19	
ERROR	DOI Server Error for 10.3828/rs.2014.3	
ERROR	DOI Server Error for 10.3828/sfftv.2014.15	
ERROR	DOI Server Error for 10.3828/sj.2014.9c	
ERROR	DOI Server Error for 10.3828/tpr.2014.15
ERROR	DOI Server Error for 10.3828/tpr.2014.35
ERROR	DOI Server Error for 10.3828/tpr.2014.36
ERROR	DOI Server Error for 10.3828/tpr.2014.40
ERROR	DOI Server Error for 10.3828/bhs.2014.22	
ERROR	DOI Server Error for 10.3828/bhs.2014.41	
ERROR	DOI Server Error for 10.3828/bj.2014.8	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/cfc.2014.1	
ERROR	DOI Server Error for 10.3828/ejlp.2014.8	
ERROR	DOI Server Error for 10.3828/extr.2014.14	
ERROR	DOI Server Error for 10.3828/extr.2014.7	
ERROR	DOI Server Error for 10.3828/franc.2014.1	
ERROR	DOI Server Error for 10.3828/lhr.2014.11	
ERROR	DOI Server Error for 10.3828/lhr.2014.12	
ERROR	DOI Server Error for 10.3828/mb.2014.27	
ERROR	DOI Server Error for 10.3828/mb.2014.29	
ERROR	DOI Server Error for 10.3828/msmi.2014.5	
ERROR	DOI Server Error for 10.3828/msmi.2014.5	
ERROR	Unregistered DOI for DOI 10.3828/qs.2014.12
ERROR	Unregistered DOI for DOI 10.3828/qs.2014.4
ERROR	DOI Server Error for 10.3828/rs.2014.1	
ERROR	DOI Server Error for 10.3828/sfftv.2014.13	
ERROR	DOI Server Error for 10.3828/tpr.2014.39	
ERROR	DOI Server Error for 10.3828/bfarm.2007.2.1	
ERROR	DOI Server Error for 10.3828/bhs.2014.33	
ERROR	DOI Server Error for 10.3828/bhs.2014.35	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/bjcs.2014.8	
ERROR	DOI Server Error for 10.3828/cfc.2014.9	
ERROR	DOI Server Error for 10.3828/cfc.2014.9	
ERROR	DOI Server Error for 10.3828/ejlp.2014.3
ERROR	DOI Server Error for 10.3828/extr.2014.4	
ERROR	DOI Server Error for 10.3828/idpr.2014.16	
ERROR	DOI Server Error for 10.3828/jlcds.2014.15	
ERROR	DOI Server Error for 10.3828/jlcds.2014.17	
ERROR	DOI Server Error for 10.3828/lhr.2014.12	
ERROR	DOI Server Error for 10.3828/lhr.2014.7	
ERROR	DOI Server Error for 10.3828/mb.2014.13	
ERROR	Unregistered DOI for DOI 10.3828/qs.2014.3
ERROR	DOI Server Error for 10.3828/tpr.2014.15	
ERROR	DOI Server Error for 10.3828/bhs.2014.30	
ERROR	DOI Server Error for 10.3828/bj.2014.9	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/ejlp.2014.7	
ERROR	DOI Server Error for 10.3828/extr.2014.7	
ERROR	DOI Server Error for 10.3828/franc.2014.4	
ERROR	DOI Server Error for 10.3828/jlcds.2014.14	
ERROR	DOI Server Error for 10.3828/jlcds.2014.19	
ERROR	DOI Server Error for 10.3828/lhr.2014.1	
ERROR	Unregistered DOI for DOI 10.3828/qs.2014.10
ERROR	DOI Server Error for 10.3828/tpr.2014.13	
ERROR	DOI Server Error for 10.3828/tpr.2014.39	
ERROR	DOI Server Error for 10.3828/bhs.2014.16	
ERROR	DOI Server Error for 10.3828/bhs.2014.17	
ERROR	DOI Server Error for 10.3828/bhs.2014.21	
ERROR	DOI Server Error for 10.3828/bj.2014.5	
ERROR	DOI Server Error for 10.3828/bj.2014.6	
ERROR	DOI Server Error for 10.3828/bjcs.2014.13	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/cfc.2014.3	
ERROR	DOI Server Error for 10.3828/cfc.2014.9	
ERROR	DOI Server Error for 10.3828/cfc.2014.9	
ERROR	DOI Server Error for 10.3828/extr.2014.3	
ERROR	DOI Server Error for 10.3828/extr.2014.7	
ERROR	DOI Server Error for 10.3828/idpr.2014.15	
ERROR	DOI Server Error for 10.3828/lhr.2014.4	
ERROR	DOI Server Error for 10.3828/sfftv.2014.12	
ERROR	DOI Server Error for 10.3828/sfftv.2014.12	
ERROR	DOI Server Error for 10.3828/sj.2014.10	
ERROR	DOI Server Error for 10.3828/sj.2014.8	
ERROR	DOI Server Error for 10.3828/tpr.2014.27	
ERROR	DOI Server Error for 10.3828/bj.2014.9	
ERROR	DOI Server Error for 10.3828/bj.2014.9	
ERROR	DOI Server Error for 10.3828/bjcs.2014.16	
ERROR	DOI Server Error for 10.3828/cfc.2014.1	
ERROR	DOI Server Error for 10.3828/ejlp.2014.6	
ERROR	DOI Server Error for 10.3828/extr.2014.14	
ERROR	DOI Server Error for 10.3828/extr.2014.7	
ERROR	DOI Server Error for 10.3828/idpr.2014.18	
ERROR	DOI Server Error for 10.3828/rs.2014.5	
ERROR	DOI Server Error for 10.3828/sfftv.2014.12

**Comment by kjw** [comment]
Lou,

A 504 error is an error returned when the servers are overloaded. It isn't related to specific DOIs. There was a lot of traffic a few days ago. You can now retrieve these DOIs.

**Comment by loupeck** [comment]
Thanks @kjw but this was a 505 not a 504 - unless they are the same? The thing is that this file has been processed three times now and the same DOIs come up with the same error and these have been done over the past few months so I am little concerned why they continually error

**Comment by kjw** [comment]
Ah. 505 is a very odd error to see. It would still be related to some systemic issue rather than particular DOIs. 

At the moment I can query for all of those DOIs and see they are working:

    http://api.crossref.org/works/10.3828/rs.2014.5

The 505 could be related to the specific way you are querying for the data. Can you give some information - what HTTP client you are using, exactly the request URL and headers you are sending so I can try and replicate this?

**Comment by emanuil-tolev** [comment]
Hey @kjw , sorry for the late reply.

We are doing the equivalent of

```bash
curl -XHEAD -H "Accept: application/json" "http://api.crossref.org/works/10.3828%2Fbhs.2014.27"
curl -H "Accept: application/json" "http://api.crossref.org/works/10.3828%2Fbhs.2014.27"
```

Actually we're using Ruby as such:

```ruby
@client = HTTPClient.new
# ...
@client.head("http://dx.doi.org/#{CGI.escape(doi)}?", header: {"Accept" => "application/json"})
# ...
url = "http://api.crossref.org/works/#{CGI.escape(doi)}"
json = JSON.parse(@client.get_content( url , header: {"Accept" => "application/json"}))
```

All quite simple. It does work right now and we'll let you know if we notice any more 505-s.

505 appears to be a protocol (HTTP in our case) version mismatch error, but that sounds like it would have appeared for all DOIs we tried to query, not just some specific ones. I've used the ruby lib HTTPClient's debugging capabilities to get this dump of requests it makes:

HEAD /10.3828%2Fbhs.2014.27? HTTP/1.1
Accept: application/json
X-NewRelic-ID: XQQDV15QGwYHU1RVAAQ=
X-NewRelic-Transaction: P1hCDQpPXlJcFwROWURbCkhfQ18OOw==
User-Agent: HTTPClient/1.0 (2.6.0.1, ruby 2.1.2 (2014-05-08))
Date: Tue, 16 Feb 2016 12:04:52 GMT
Host: dx.doi.org

GET /works/10.3828%2Fbhs.2014.27 HTTP/1.1
Accept: application/json
X-NewRelic-ID: XQQDV15QGwYHU1RVAAQ=
X-NewRelic-Transaction: P1hCDQpPXlJcFwROWURbCkhfQ18OOw==
User-Agent: HTTPClient/1.0 (2.6.0.1, ruby 2.1.2 (2014-05-08))
Date: Tue, 16 Feb 2016 12:03:16 GMT
Host: api.crossref.org

... which all look reasonable, with HTTP 1.1 as the protocol. The HEAD returns 303 as expected and the GET returns 200 as expected right now.
