### ISSUE TITLE
Retrieving 5 million data from Crossref

### ISSUE THREAD

**Issue by misdigital** [CrossRef/rest-api-doc#390]
Hello,
I want to work with 5 millions data from crossref. How can I use crossref api to pull such huge data ? My specific goal is to get crossref publication data for 25 countries. I dont want to search the api with title or doi .. I need daily updated data from where I can filter to my specific countries.

Please advice me on this.

**Comment by pdavis8** [comment]
Thanks for the question. Could you elaborate further on what you are looking for? Are you looking for specific countries data? Or a daily update of new data?

**Comment by pdavis8** [comment]
As we have not had a reply in a while I will close this ticket. If you want to reopen this ticket please do not hesitate to do so.
