### ISSUE TITLE
Short DOIs

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#392]
a rcrossref user wondered why short DOIs dont work https://github.com/ropensci/rcrossref/issues/167 - I imagine the API doesn't support short DOIs, correct?

**Comment by sckott** [comment]
any thoughts on this?

**Comment by pdavis8** [comment]
Sorry for the delay in reply to this, I have asked the question to a colleague regarding the short DOIs, how they are processed and why they are not directly searchable. I will hopefully get an answer from my colleague soon and pass this onto you.

**Comment by sckott** [comment]
thanks @pdavis8

**Comment by sckott** [comment]
answer in https://github.com/ropensci/rcrossref/issues/167#issuecomment-423129910

**Comment by pdavis8** [comment]
Answer at the link above from Geoffrey as Scott mentioned. Closing ticket.
