### ISSUE TITLE
Incorrect and duplicate data

### ISSUE THREAD

**Issue by pattisahusiwa** [CrossRef/rest-api-doc#394]
These urls actually point to the same article
- https://api.crossref.org/works/10.1016/s0169-2070(99)00016-3
- https://api.crossref.org/works/10.1016/s0169-2070(99)00019-9
- https://api.crossref.org/works/10.1016/S0169-2070(99)00013-8

In this page https://www.sciencedirect.com/science/article/pii/S0169207099000138, the correct DOI is https://doi.org/10.1016/S0169-2070(99)00013-8.

**Comment by pdavis8** [comment]
These duplicate DOIs should now be aliasing to the correct DOI 10.1016/S0169-2070(99)00013-8 now.
Thanks for letting us know about this.

**Comment by pattisahusiwa** [comment]
> These duplicate DOIs should now be aliasing to the correct DOI 10.1016/S0169-2070(99)00013-8 now.

Where can I find alias info? URL and DOI still point to old data.
