### ISSUE TITLE
How to use cursor in Member api call

### ISSUE THREAD

**Issue by umairq** [CrossRef/rest-api-doc#395]
I want to get all possible API calls available in crossref. Is it possible? Which API call can be used to fetch all possible API calls to access crossref data. 

Thanks
Regards

**Comment by pdavis8** [comment]
Hello, there are a huge amount of variables in API calls that can be used, so documenting them all would be very tricky. 

I think the best thing would be to have a look at the documentation on here: https://api.crossref.org

If you have any specific calls you would like to make and need help then please do let us know by commenting here.

**Comment by gbilder** [comment]
We will eventually be supporting Swagger documentation, which should give you a more complete, navigable view of the API. Until then, here are a few hacks/tricks that you can use to see what is supported. Basically, use a query, filter or facet that you *know* doesn't exist. Then you will get an error page that lists the routes, filters or facets that *do* exist. For example:

- `http://api.crossref.org/works?query.xxx=yyy`
- `http://api.crossref.org/works?facet=yyy`
- `http://api.crossref.org/works?ilter=yyy`

**Comment by VladimirAlexiev** [comment]
Actually https://github.com/CrossRef/rest-api-doc is excellent. Eg https://github.com/CrossRef/rest-api-doc#queries describes the `query.xxx` possibilities.
And the built-in documentation in error responses is very excellent and **up to date**, @gbilder thanks for that suggestion!
