### ISSUE TITLE
What abaout the issn types?

### ISSUE THREAD

**Issue by jenswitzel** [CrossRef/rest-api-doc#396]
What about the issn types?

I'll find "....one of eissn, pissn or lissn" (see https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md#issn-with-type), but in real life it's simple "print". How should i deal this for import?

Thanks a lot

**Comment by pdavis8** [comment]
Hello,
Our members will supply anyone of a number of those types of ISSN to us, the online ISSN is used when the publication date for online is different to that of the print publication date. 

What issues are you facing with the import?

**Comment by michael-newsrx** [comment]
In regards to "issn type" documentation at https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md#issn-with-type, the pissn shows as "print" and the "eissn" shows with type "electronic" and not "pissn" nor "eissn", and what is an "lissn"?

**Comment by Zoidmania** [comment]
I'm wondering this myself. I don't see any examples of "eissn", "pissn", or "lissn" in the 2021 bulk dump, only "print" and "electronic". No idea what "lissn" could map to, but I'm guessing that "eissn" maps to "electronic" and "pissn" maps to "print". Either way, API spec at https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md#issn-with-type doesn't match the data.

**Comment by ppolischuk** [comment]
With apologies for the long delay, we recommend you bring this and other questions to our community forum's metadata retrieval section, where more Crossref staff are likely to see and respond to your questions and comments.

https://community.crossref.org/c/metadata-retrieval/27

We're currently conducting a review of how these and other metadata elements are modeled in our internal item tree, and in some cases represented in the citeproc-JSON response. I don't have details on exactly how the issn type will be handled moving forward, but we hope to resolve this kind of discrepancy as part of this work.
