### ISSUE TITLE
Missing affiliation data

### ISSUE THREAD

**Issue by jure** [CrossRef/rest-api-doc#4]
Not sure if this is an actual issue, i.e., is this data available somewhere and is not exposed the API, or does CrossRef not collect it at all?

E.g. affiliations on a PLOS paper (http://api.plos.org/search?wt=json&start=0&rows=10&fl=id,title_display,subject,counter_total_month,affiliate,author_display,abstract,journal,article_type,publication_date&fq=!article_type_facet:%22Issue%20Image%22%20AND%20doc_type:full&sort=counter_total_month%20desc&api_key=7Jne3TIPu6DqFCK&q=title:%22hello%22):

```
"affiliate": [
"School of Psychology, College of Science and Engineering, University of Glasgow, Glasgow, United Kingdom",
"Department of Psychology, Princeton University, Princeton, New Jersey, United States of America",
"Voice Neurocognition Laboratory, Institute of Neuroscience and Psychology, College of Medical, Veterinary and Life Sciences, University of Glasgow, Glasgow, United Kingdom",
"Département de Psychologie, Université de Montréal, Montréal, Quebec, Canada",
"Institut des Neurosciences de La Timone, Université Aix-Marseille, Marseille, France",
"Northwestern University, United States of America"
]
``` 

And CrossRef doesn't have it: http://api.crossref.org/works/10.1371/journal.pone.0090779

**Comment by kjw** [comment]
Contributor affiliations now available. This data is being indexed at the moment. It will be available for DOIs registered from now, but only fully available for all DOIs (where we have the data) in a week or two once re-indexing is complete.

I agree with the plans for affiliation organisational IDs but I'm going to treat this issue as the need for existing affiliation info in the REST API.

**Comment by jure** [comment]
Fantastic! :+1:

**Comment by mfenner** [comment]
+1

**Comment by zjiang4** [comment]
cr_journals(issn = c('1538-4640'),works=TRUE,facet="orcid:*")
When I execute this line, it only gives me 10 orcids...why that discrepancy happens?
