### ISSUE TITLE
Publisher place missing from JSON response

### ISSUE THREAD

**Issue by aurimasv** [CrossRef/rest-api-doc#40]
...even though it is present in the XML format

E.g. http://api.crossref.org/works/10.1017/CCOL0521858429.016 vs http://api.crossref.org/works/10.1017/CCOL0521858429.016.xml `<publisher_place>Cambridge</publisher_place>`

**Comment by kjw** [comment]
This is available by looking up the member. e.g.:

```
http://api.crossref.org/v1/members/56
```
