### ISSUE TITLE
Adding category/ies to /works results

### ISSUE THREAD

**Issue by eluzix** [CrossRef/rest-api-doc#401]
Is it possible to add the category (one or more) in the results of works search?

I'll explain the use case - I'm trying to identify a specific author (solving issue #311 will make it much much more manageable but the issue still relevant). To do so, I'm trying to filter the results by category-name. There is a limit to how many categories I can use (URL size), so I want to filter the results at my side.
 
At the moment it's impossible because the results don't contain the categories.

Is it possible?

**Comment by eluzix** [comment]
Answering myself in case anyone finds this issue.

Results do contain the categories in the facet BUT not in the categories field but as the subject field.

**Comment by pdavis8** [comment]
Thanks for adding the update @eluzix.
