### ISSUE TITLE
work type the same for journal article and news

### ISSUE THREAD

**Issue by wdfsinap** [CrossRef/rest-api-doc#404]
the work http://dx.doi.org/10.1038/nature.2014.15953 actually a news or comment, the API response of the journal-type is "journal-article"
is that possible to really rename such work with "news"?
another suggestion is to add new journal-type with "review", etc.
thanks

**Comment by pdavis8** [comment]
Hello,

At the moment there is not a content type in our schema for 'news'. [Here](https://support.crossref.org/hc/en-us/articles/213123586-Metadata-and-content-type-overview) is a list of the available content types we have at the moment but these are always being looked into so this could change in the future to include something more relevant for this article. In which case the member would be able to make that change in the metadata with us by a redeposit.

Thanks
