### ISSUE TITLE
REST request to get citations using DOI 

### ISSUE THREAD

**Issue by shekharshan** [CrossRef/rest-api-doc#406]
I have a DOI and I am trying to figure out the citation count for that DOI. Does anyone know the REST request to get this information?

I will really appreciate any help!

**Comment by renanbr** [comment]
I don't know what you mean with "REST request", btw you can use filters (https://github.com/CrossRef/rest-api-doc#filter-names)

```bash
curl "https://api.crossref.org/works?filter=doi:10.5555/12345678"
```

**Comment by pdavis8** [comment]
Hello, you can find the citation count against any DOI by replacing the example DOI in this URL: http://api.crossref.org/works/10.5555/12345678/transform/application/vnd.crossref.unixsd+xml
You will see the count in the line
`<crm-item name="citedby-count" type="number">2</crm-item>`
