### ISSUE TITLE
Count in container-title facet != number of records returned by query

### ISSUE THREAD

**Issue by ioverka** [CrossRef/rest-api-doc#409]
Dear Crossref team,

I used the Crossref API to identify publications by one member which haven't been updated since end of 2015 and grouped them by container title:

https://api.crossref.org/members/286/works?filter=until-update-date:2015-12-31&facet=container-title:*&rows=0

```
{"container-title":
    {"value-count":1000,
        "values":{
            [...]
            "Cardiovascular Research":576,
            "European Journal of Cardio-Thoracic Surgery":552,
            "Journal of Experimental Botany":549,
            "Monthly Notices of the Royal Astronomical Society":547
            [...]
```

Shouldn't combining the same filter with a query by "container-title" this or a very similar number of works? That doesnt't seem to be the case:
- https://api.crossref.org/members/286/works?filter=until-update-date:2015-12-31&query.container-title=%22European%20Journal%20of%20Cardio-Thoracic%20Surgery%22 = 121252 instead of 552
- https://api.crossref.org/members/286/works?filter=until-update-date:2015-12-31&query.container-title=%22Journal%20of%20Experimental%20Botany%22 = 120182 records instead of 549
- https://api.crossref.org/members/286/works?filter=until-update-date:2015-12-31&query.container-title=%22Monthly%20Notices%20of%20the%20Royal%20Astronomical%20Society%22 = 151244 records instead of 547

What am I doing wrong?

Thanks
inga

**Comment by ppolischuk** [comment]
In this case, you probably want to be using the `container-title` **filter** rather than `query.container-title`

eg for the European Journal of Cardio-Thoracic Surgery you could use the following query: https://api.crossref.org/members/286/works?filter=until-update-date:2015-12-31,container-title:European%20Journal%20of%20Cardio-Thoracic%20Surgery

**Comment by ioverka** [comment]
Thanks a lot, using the filter returns the wanted subset. But I'm still curios: Why does the combination of filter & query returns something completely different?
