### ISSUE TITLE
Book editors sometimes missing from JSON response

### ISSUE THREAD

**Issue by aurimasv** [CrossRef/rest-api-doc#41]
Editors appear in both JSON and XML for http://api.crossref.org/works/10.1017/CCOL0521858429.016 but only in XML for http://api.crossref.org/works/10.1057/9780230391116.0016

**Comment by kjw** [comment]
Problem here is that the latter attempts to represent a book chapter, while the editors are listed as editors of the book. I will assume that the intention is the editors are editors of the full book, and therefore all chapters, and so this is a bug.

**Comment by andrewgilmartin** [comment]
Karl's assumption seems right, but we have to be careful to distinguish what data the publisher gives to Crossref and what data Crossref establishes itself. In this case, I would not add the editing contributors to the work, but instead encourage API users to walk the containment relationships to gain a fuller understanding of the work in context.

**Comment by kjw** [comment]
This will require parent - child relationships between DOIs to be clearly marked in API JSON.

**Comment by ckoscher** [comment]
The publication level entity does not always have its own DOIs. When deposited the content-item (chapter) will always have its own DOI, may have chapter level authors. The publication may have authors and/or editors but no DOI.
