### ISSUE TITLE
Querying the same ISSN Number results in blank data via one request and for the other it works fine

### ISSUE THREAD

**Issue by vineetdpnd** [CrossRef/rest-api-doc#411]
On querying the ISSN Number :-  0891-0162 via the query below , it returns empty.

http://api.crossref.org/journals/0891-0162/works

While querying the same ISSN number via the query below , returns proper article list for that Journal.

http://api.crossref.org/works?filter=issn:0891-0162

I guess both of them should work fine and the first one should be faster than the second one too.

**Comment by pdavis8** [comment]
This looks to be a bug in the API. I will escalate this to the developers to have a look at.

**Comment by pdavis8** [comment]
This bug has now been fixed so you should hopefully be able to search via ISSN along the journal route.

**Comment by vineetdpnd** [comment]
Thanks a lot. @pdavis8
