### ISSUE TITLE
location in the funder urls

### ISSUE THREAD

**Issue by rappazf** [CrossRef/rest-api-doc#415]
Is there a list or a way to query and extract all the locations used in the funders metatada ?
For example this one works
https://api.crossref.org/funders?filter=location:United%20Kingdom
But location:Great%20Britain, or location:UK ... etc does not return anything
Thanks

François

**Comment by pdavis8** [comment]
Hello,
I'm afraid there is no way of getting that information, it would require a facet which is not currently available on that route.
This should be something that is possible after the migration of the data to a new database that is currently happening but it is not available at the moment.
