### ISSUE TITLE
Problems with cursor

### ISSUE THREAD

**Issue by mayetapia** [CrossRef/rest-api-doc#417]
Hi
I was trying to use the cursor but I get an error.
Help me with this.
https://api.crossref.org/works?query.affiliation=universidad+de+guayaquil&cursor=* (ok)
https://api.crossref.org/works?query.affiliation=universidad+de+guayaquil&cursor=AoJxn8uN1uICPwJodHRwOi8vZHguZG9pLm9yZy8xMC4xMDcxL211MTQwMzA= (ok)
https://api.crossref.org/works?query.affiliation=universidad+de+guayaquil&cursor=AoJ4p+Ow4OICPxJodHRwOi8vZHguZG9pLm9yZy8xMC40MDE4Lzk3OC0xLTQ2NjYtMzY5MS0wLmNoMDA3 (error)

**Comment by pdavis8** [comment]
Hello,
If you replace the + in the cursor with %2B then this should work. 
Thanks

**Comment by JonathanOnorato** [comment]
Bless you pdavis8. I've been angry over having cursor issues like this for literally days. 

As a comment, is it possible to add this to the API markdown description? A small piece of documentation like this could make a world of difference to frustrated users.

**Comment by gbilder** [comment]
Hi. Sorry about the frustration. Will add a note that it is generally best practice to [URL-encode](https://en.wikipedia.org/wiki/Percent-encoding) all parameters (not just cursors) when using the REST API.

**Comment by gbilder** [comment]
Oops. Looks like we already did so:

> You should always url-encode DOIs and parameter values when using the API. DOIs are notorious for including characters that break URLs (e.g. semicolons, hashes, slashes, ampersands, question marks, etc.).

But will add note about cursors as well.
