### ISSUE TITLE
Supply language information

### ISSUE THREAD

**Issue by aurimasv** [CrossRef/rest-api-doc#42]
In UNIXREF language is an attribute on various *_metadata elements. I'm not actually entirely clear on whether that's supposed to refer to the language of the resource or the language of the metadata, but it may be helpful nonetheless (Zotero would like to import it). Citeproc JSON defines a language property, so there shouldn't be much of an issue.

Sample reference http://api.crossref.org/works/10.1057/9780230391116.0016.xml `<book_metadata language="en">`

**Comment by kjw** [comment]
Noted. Will look to add language information to both our default representation and the citeproc JSON compatible representation.

**Comment by kmeddings** [comment]
Noted in list of missing elements.

**Comment by ppolischuk** [comment]
Closing as this has been added.
