### ISSUE TITLE
Resource components vs filtering

### ISSUE THREAD

**Issue by aolney** [CrossRef/rest-api-doc#426]
Is there a reason, like performance, to prefer a query like

`members/23/works`

over

`works?filter=member:23`

If not, choosing the later would probably simplify writing wrappers around the API.

Any thoughts on this topic would be appreciated.

**Comment by pdavis8** [comment]
Wrappers should be in the Libraries here: https://github.com/CrossRef/rest-api-doc#libraries

**Comment by aolney** [comment]
Yes I started an F# wrapper (which could be used with any .NET language) and will open source it. I will post the link to this thread or start a new issue as you prefer.
