### ISSUE TITLE
Escaping commas when filtering REST API

### ISSUE THREAD

**Issue by jakubpawlowicz** [CrossRef/rest-api-doc#44]
We've come across an issue with REST API filter parameter when querying for fields which contain commas. Since multiple filters are also separated by commas there should be a way escape the former to avoid parsing issues, see:

* Book - http://link.springer.com/book/10.1007%2F978-4-431-67035-3
* Rest API query - http://api.crossref.org/works?filter=container-title:Thermotherapy+for+Neoplasia%2C+Inflammation%2C+and+Pain,type=book-chapter&rows=1000

As you can see escaping commas are not handled properly, nor quoting or skipping them.
JSON params neither work for us: https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#example-query-using-json-in-body-of-get-request

See also https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#multiple-filters

**Comment by hubgit** [comment]
The second filter should be `type:book-chapter`, instead of `type=book-chapter`.

**Comment by kjw** [comment]
Ah great, thanks for spotting, @hubgit . Those error messages are relatively new - back in Jan when this issue was originally created the API would silently ignore invalid input.

**Comment by jakubpawlowicz** [comment]
My bad :-/ So nice we have error messages now :+1:
