### ISSUE TITLE
query.biblographic returning crossref.restful.Works object at 0x106153e10

### ISSUE THREAD

**Issue by mutanthumb** [CrossRef/rest-api-doc#440]
Hi-
I'm trying to parse citations from CVs with your API and it doesn't seem to be working. I'm using Python 3

Interestingly, the URL that this generates if I use .url works if I plop it right in an address bar, but I can't seem to get results from a Python command script in terminal.

```
from crossref.restful import Works
works = Works()
works.query(bibliographic = 'Weissman, D.H., Drake, B., Colella, K., & Samuel, D. (2018). Perceptual load is not always a crucial determinant of early versus late selection. Acta Psychologica, 185, 125-135')
```
Returns: <crossref.restful.Works object at 0x106153e10>
I'm expecing a dict.

Any advice would be appreciated.

Thanks,
susan

**Comment by gbilder** [comment]
Hi, `works` is a generator, so you can do this:

```
for work in works:
    print(work['title'])
```

Complete example below:

```
from crossref.restful import Works
works = Works()
works.query(bibliographic = 'Weissman, D.H., Drake, B., Colella, K., & Samuel, D. (2018). Perceptual load is not always a crucial determinant of early versus late selection. Acta Psychologica, 185, 125-135')
# New bit
for work in works:
    print(work['title'])
```

Hope this helps.

**Comment by mutanthumb** [comment]
Thanks for the info, G.
When I use your code I'm getting other entries other than the one I'm looking for. I'm getting great results when I enter this 'Weissman, D.H., Drake, B., Colella, K., & Samuel, D. (2018). Perceptual load is not always a crucial determinant of early versus late selection. Acta Psychologica, 185, 125-135' into the Crossref search field.

FYI, I'm following this: https://www.crossref.org/labs/resolving-citations-we-dont-need-no-stinkin-parser/ and hoping to get a DOI from a bibliographic entry.

I'm also using your crossref-api-demo.ipynb for experimenting.

Thanks,
susan

**Comment by mutanthumb** [comment]
Got it working! Thanks, I think was just being dense.

`from habanero import Crossref`
`import csv`

`cr = Crossref()`
`x = cr.works(query = "S. Kaplan and R. Kaplan (1962) Skin resistance recording in the unrestrained rat. Science, 138, 3548, 1403-1404.", limit = 1)`

`for z in x['message']['items']:`
`     print(z.get('author',None))`
