### ISSUE TITLE
Different results between api.crossref.org and search.crossref.org

### ISSUE THREAD

**Issue by pafonta** [CrossRef/rest-api-doc#444]
Dear team,

I wonder if this is expected that the same query on `api.crossref.org` and `search.crossref.org` gives **different** results?

I am looking for a journal article titled _Electrical Synapses in the Thalamic Reticular Nucleus_. Using `search.crossref.org` I got the result I expect: the first returned CrossRef record is the paper I am looking for.

This **is not the case** using the programmatic access through `api.crossref.org`: the paper I am looking for is only at the 8th position, even with desc sorting on relevance.

From my understanding,**`api.crossref.org` is therefore not corresponding to its specs**.

Expected result:
https://search.crossref.org/?q=Electrical+Synapses+in+the+Thalamic+Reticular+Nucleus

**Unexpected results**:
https://api.crossref.org/works?query.title=Electrical+Synapses+in+the+Thalamic+Reticular+Nucleus&select=title&sort=score&order=desc

**Comment by ppolischuk** [comment]
Hello,

search.crossref.org is presently configured to use the REST API's `query.bibliographic` filter. Plugging that filter into your api.crossref.org query returns _Electrical Synapses in the Thalamic Reticular Nucleus_ as the first result.

https://api.crossref.org/works?query.bibliographic=Electrical+Synapses+in+the+Thalamic+Reticular+Nucleus&select=title&sort=score&order=desc

Hope this helps.

**Comment by pafonta** [comment]
Hello,

Thank you very much for your prompt answer.

Using `bibliographic` instead of `title` gives the behaviour I was expecting.

Is the fact that the paper has the 8th rank with `query.title` related to the fact it searches also on a 'subtitle'? What is a subtitle for a scientific paper?

**Comment by mjy** [comment]
This was an AHA for me. Perhaps this relationship can be spelled out in the documentation?  I have an old wrapper that (partially) stopped working (hitting `search.crossref.org/links`) and it was a little tricky finding out why as that endpoint is undocumented.
