### ISSUE TITLE
Default Email address issue

### ISSUE THREAD

**Issue by antropophob** [CrossRef/rest-api-doc#45]
I've come across an issue with REST API.
Submitter email address alway changes to "crlabs@fastmail.fm"  (in doi_batch->head->depositor->email_address tag)

Disscussion on support board http://support.crossref.org/requests/34468

**Comment by kjw** [comment]
This is intentional. The API intercepts notification e-mails and provides notification instead through the API via calls to the deposit route - /deposits/:id .

See documentation here: 

https://github.com/CrossRef/rest-api-doc/blob/master/deposit_api.md

**Comment by kjw** [comment]
@antropophob - If you'd like to contact me directly to better understand this, please feel free - Skype is karlward .
