### ISSUE TITLE
Inconsistency of "total-results" (e.g. when refreshing the API)

### ISSUE THREAD

**Issue by anmipac** [CrossRef/rest-api-doc#451]
Hello,
your API has been working well for me, but since 3 days I am encountering a new problem I have not had before.

Namely, when I access an API with the filter "filter=from-pub-date:2019-03", I see the "total-results" as a number (e.g. total-results: 5). However, since 3 days it often shows me the wrong (a lower) number, such as total-results: 4. But when I open the API again and refresh it, it then shows me total-results: 5, but when I refresh again, it randomly changes to either 4 or 5.

It only seems to happen with my "mailto:" added in the header (when I open the API manually in the browser), and when my PHP-script aims at fetching the total results. Without the "mailto:", it always shows me the correct number (namely 5).

Four examples with which it happned to me (though there are dozens more examples!):
1.) https://api.crossref.org/journals/1461-7390/works?sort=issued&order=desc&filter=from-pub-date:2019-03&select=author,DOI,title,published-online,published-print,created,indexed,issued,container-title,references-count&cursor=*
2.) https://api.crossref.org/journals/1464-3820/works?sort=issued&order=desc&filter=from-pub-date:2019-03&select=author,DOI,title,published-online,published-print,created,indexed,issued,container-title,references-count&cursor=*
3.) https://api.crossref.org/journals/1465-3427/works?sort=issued&order=desc&filter=from-pub-date:2019-03&select=author,DOI,title,published-online,published-print,created,indexed,issued,container-title,references-count&cursor=*
4.) https://api.crossref.org/journals/1432-0592/works?sort=issued&order=desc&filter=from-pub-date:2019-03&select=author,DOI,title,published-online,published-print,created,indexed,issued,container-title,references-count&cursor=*

(I deleted each "mailto"s)

Could you perhaps take a look at it? I would be grateful!

**Comment by anmipac** [comment]
P.S. I just noticed - it also does not work if my script does NOT use the "mailto". Thus, I simply get a lower number of "total-results" whenever my script accesses your API. However, when I open the API manually, the "total-results"-number seems correct (or sometimes lower, but becomes correct again when I hit F5).

**Comment by afandian** [comment]
Could you please add `&debug=true` to the end of the URL, e.g. 

<https://api.crossref.org/journals/1432-0592/works?sort=issued&order=desc&filter=from-pub-date:2019-03&select=author,DOI,title,published-online,published-print,created,indexed,issued,container-title,references-count&cursor=*&debug=true>

And share the `debug.instance-hostname` values that are returned for the 4 and 5 counts?

**Comment by anmipac** [comment]
Hello, thanks for the guidance.

I used my script and found this problem with this:
https://api.crossref.org/journals/0003-0554/works?sort=issued&order=desc&filter=from-pub-date:2019-03&select=author,DOI,title,published-online,published-print,created,indexed,issued,container-title,references-count&mailto=ap@ooir.org&cursor=*&debug=true

It said "total-results: 5", but when I refresh, it says "total-results: 7".

"debug":{**"instance-hostname":"svc11d.crossref.org**","solr-response-header":"{status=0,QTime=53}"}}

-----

Even more interestingly, here:
https://api.crossref.org/journals/0032-3195/works?sort=issued&order=desc&filter=from-pub-date:2019-03&select=author,DOI,title,published-online,published-print,created,indexed,issued,container-title,references-count&mailto=ap@ooir.org&cursor=*&debug=true

It said "total-results: 0", even though when I refresh, it's "total-results: 32"

"debug":{**"instance-hostname":"svc11d.crossref.org"**,"solr-response-header":"{status=0,QTime=15}"}

------

I have many other examples, but the instance-hostname is always the same.

**Comment by anmipac** [comment]
It seems that the issue (whose root cause was an incorrect syncing of Solr machines, as I was told by e-mail) has been solved by CrossRef's support team. Thank you a lot!
