### ISSUE TITLE
Does the Simple Text Query change affect this API?

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#452]
wrt [the recent Crossref email about the change in Simple Text Query ](http://outreach.crossref.org/acton/rif/16781/s-01c4-1904/-/l-0205:751/l-0205/showPreparedMessage?utm_term=View%20this%20message%20in%20your%20browser&utm_campaign=Simple%20Text%20Query%20for%20matching%20references%20is%20being%20replaced&utm_content=email&utm_source=Act-On+Software&utm_medium=email&cm_mmc=Act-On%20Software-_-email-_-Simple%20Text%20Query%20for%20matching%20references%20is%20being%20replaced-_-View%20this%20message%20in%20your%20browser&sid=TV2:pueq97ip7) - Does that change affect this API? Or not? Want to make sure the client libraries I work on are changed accordingly

**Comment by ppolischuk** [comment]
Stay tuned for further updates re: Simple Text Query. After receiving quite a bit of feedback about how it's used, we're updating our deprecation plans. Simple Text Query will be sticking around for a while longer.

Regardless, this change will not immediately affect this API. We may improve the API's reference matching facilities, but we're still in the planning phase.
