### ISSUE TITLE
Question: Which exact fields does "from_pub_date" filter on?

### ISSUE THREAD

**Issue by Bubblbu** [CrossRef/rest-api-doc#459]
I was wondering which date fields are used for the "from_pub_date" filter?
If multiple ones, could you document the order of used fields?

**Comment by pdavis8** [comment]
The `from-pub-date` filter should work with the earliest publication date that the record has. If you wanted to filter on a specific pub date you can use `from-online-pub-date' or `from-print-pub-date`.
