### ISSUE TITLE
Citation number through time?

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#46]
I have a request from a user of our R client for this API to get citations (to be clear: not references in the article itself, but citations to the article) through time. e.g., basically facet by time, maybe year, or month to get citations for each year or month. 

Any chance this could be on the road map?

Another way this could be done is getting all citations to a paper, and then manually calculating citations per time period, but this faceting approach would be cool to have in this API...

**Comment by ckoscher** [comment]
Unfortunately citations (we call it cited-by) are still protected 
metadata where only the publisher of the article is able to retrieve the 
list of citing articles.

Chuck

**Comment by sckott** [comment]
@ckoscher okay,  thanks for the quick feedback, closing

**Comment by Blahah** [comment]
Is there any plan to open up cited-by?

Note @sckott that while it is unlikely to be as comprehensive as CrossRef cited-by, EuropePMC can give citations and citation counts for articles via their API: https://europepmc.org/RestfulWebService#cites

**Comment by kjw** [comment]
There is a plan to provide some cited by data. We now allow publishers to say that they are happy for Crossref to distribute their citation info. At some point the API will take this into account and report those 'public' citations.

**Comment by Blahah** [comment]
Great! In conversation with people trying to do text and data mining, citations is consistently something people want to be able to access (e.g. to prioritise results).

**Comment by sckott** [comment]
@Blahah Thanks, been working on an integration for europepmc anyway, so good to know
