### ISSUE TITLE
Issued date value when published-print and published-online are empty

### ISSUE THREAD

**Issue by florist-gump** [CrossRef/rest-api-doc#460]
I have a question regarding the value of the issued field in case published-print and published-online are not filled-in. 

In the API docs it states that issued is defined as: "Earliest of published-print and published-online"

However, both published-print and published-online are optional fields and there are some cases when both those fields are empty while issued is still filled in (for example: https://api.crossref.org/works/10.1101/242883 or https://api.crossref.org/works/10.1101/193698)

Where does the issued date come from in those cases?

**Comment by pdavis8** [comment]
Both of those DOIs are for `posted-content` content type and so they do not have publication dates yet. All other content types do require at least one publication date to be added to the metadata.
For these content types the earliest `posted-date' is used in lieu of a publication date as per: http://doi.crossref.org/search/doi?pid=support@crossref.org&format=unixsd&doi=10.1101%2F193698
