### ISSUE TITLE
Count of backfile and current DOIs

### ISSUE THREAD

**Issue by idcraig** [CrossRef/rest-api-doc#47]
Apologies, this is not an issue as such, but more of a request for information. In a query such as http://api.crossref.org/members?query=elsevier, what is the logic behind which DOI's get assigned as current or backfile?

**Comment by ckoscher** [comment]
Current Vs backfile is a distinction we make when a DOI is deposited. 
The deposit fee is different. Current is this year plus previous 2 years.

**Comment by kjw** [comment]
In the case of the API, current records are anything published in the last two years. Back file records have a publication date older than two years ago. We often see a significant difference in the completeness of metadata deposited for more recent content, so we find the split useful when comparing feature coverage of metadata from different publishers.

Don't worry about posting this question here. I'm currently setting up a new documentation site with some sort of discussion group - for now questions will have to go here.
