### ISSUE TITLE
What kind of work are these?

### ISSUE THREAD

**Issue by pajooh** [CrossRef/rest-api-doc#48]
[this](http://api.crossref.org/works/10.1090/s0094-9000-05-00609-5) article has not title and issue date. 
i wonder if this is an API bug or publisher supplied data bug

**Comment by pajooh** [comment]
[this](http://api.crossref.org/works/10.1039/b107124f) one's issue date is more interesting!

**Comment by kjw** [comment]
Unfortunately, this is exactly the metadata we have been provided by the publisher of the work. For example, this is verbatim what they have given us for the publication date:

```xml
<publication_date media_type="print">
    <year>0</year>
</publication_date>
```

I'm passing this on as a support request to ask the publisher in question to redeposit corrected metadata.

**Comment by kjw** [comment]
http://crossref.zendesk.com/agent/tickets/38190
