### ISSUE TITLE
Is the Resolutions data available by any API?

### ISSUE THREAD

**Issue by Mike-Honey** [CrossRef/rest-api-doc#487]
I'm interested in retrieving resolutions data (as shown in the emailed resolutions report) systematically for a range of DOI.  Is there any API available that returns that data?

**Comment by ifarley** [comment]
Hi @Mike-Honey,

Thanks for your message. Unfortunately, the resolution data is only available through the monthly report that is emailed to those contacts on each account that have requested it.  And, we only provide resolution numbers of the top 10 DOIs resolved in the previous month within that report. 

You can learn more about the resolution reports here: https://www.crossref.org/education/metadata-stewardship/reports/resolution-report/

My best,
Isaac

**Comment by Mike-Honey** [comment]
Hi Isaac, 
Obviously that's disappointing, but thanks for the prompt and clear response.
Regards, Mike
