### ISSUE TITLE
Update documentation for filters?

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#50]
It appears as though the `/licenses` route does not support filters now, e.g. http://api.crossref.org/licenses?filter=member:78 gives message

> This route does not support filter

perhaps there are no other routes too that don't support filters? 

Another thing I just found is that only a subset of filters are supported for certain routes, e.g., http://api.crossref.org/members?filter=member:78 gives message

> Filter member specified but there is no such filter for this route. Valid filters for this route are: prefix, backfile-doi-count, currnet-doi-count

These error messages are great! But would be helpful to have in the docs as well.

**Comment by kjw** [comment]
Agreed. The error messages are new, coming out of some new validation code that I'm hoping will feed into some new documentation for the API. So yes, updated docs are on the way.

**Comment by sckott** [comment]
:+1:

**Comment by gbilder** [comment]
I'd just add that this particular example (licenses) looks like it would be a very useful filter to have. I've had a number of users says that they'd like a quick way to see what licenses a member supports. It would also be good if you could do:

http://api.crossref.org/members/78/licenses

**Comment by kjw** [comment]
This one is possible from a different way:

http://api.crossref.org/members/78/works?facet=license:*&rows=0

The `/licenses` route is pretty much a reconstruction of a facet. But yes, could apply many additional filters to `/licenses`. Kind of need to reconcile that with the faceting feature though. Two ways to do the same thing right now. Maybe even the best thing to do is get rid of the `/licenses` route and point everyone to `/works` faceting with the `license` facet.

**Comment by sckott** [comment]
@kjw thanks for the info, helpful

**Comment by gbilder** [comment]
documentation has been updated.
