### ISSUE TITLE
Content negotiation with this API?

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#52]
In the client I work on, for content negotation, I've been using the docs at http://www.crosscite.org/cn/ and the base url of `http://dx.doi.org` with appropriate headers for the content type requested. 

But in https://github.com/CrossRef/rest-api-doc/issues/43#issuecomment-70470554 looks like you can do this same thing with this API. 

Is best practice moving forward to use this API for Crossref minted DOIs? Or continue to use `http://dx.doi.org`

**Comment by mfenner** [comment]
Related to this: the CrossRef content negotiation documentation mentions that you can do content negotiation with the REST API (http://www.crosscite.org/cn/#sec-5). It would be helpful to add this information also to the REST API documentation.

**Comment by sckott** [comment]
:+1:

**Comment by kjw** [comment]
There's a big difference between doing content negotiation with the CrossRef REST API and doing it on dx.doi.org. We've worked with DataCite, mEDRA and China DOI to get their DOIs supporting content negotiation through dx.doi.org. If you go the doi.org route you will be able to get metadata for DOIs from all those registration agencies.

If you use the CrossRef REST API, it will 404 on any non-CrossRef DOI.

**Comment by kjw** [comment]
I don't want to say either way on best practice. Depends what you know about the DOIs. If you know for sure they are CrossRef DOIs, using the REST API directly will be faster. A call to dx.doi.org results in a few quite lengthy redirects and proxy requests.
