### ISSUE TITLE
Include the references with a work if available

### ISSUE THREAD

**Issue by mfenner** [CrossRef/rest-api-doc#53]
For publishers who have agreed to make the reference lists of their papers openly available, it would be great to provide this information in the CrossRef REST API.

**Comment by hubgit** [comment]
It would also be useful to be able to use "shared references" as a filter, to allow retrieval of a list of publishers/journals/articles that have (or haven't) made their reference lists open.

**Comment by gbilder** [comment]
Yay. http://api.crossref.org/members?filter=has-public-references:true
