### ISSUE TITLE
The effect of the corona virus (COVID-19) on Mental Health

### ISSUE THREAD

**Issue by delcea** [CrossRef/rest-api-doc#537]
Mihaela Rus, Mihaela Luminita Sandu, Tasente Tănase, Senouci Boumediene, Cristian Delcea*

`Iuliu Hațieganu` University of Medicine and Pharmacy in Cluj-Napoca, România

*Corresponding author: cristian.delcea.cj@gmail.com

International Journal of Advanced Studies in Sexology
Volume 2, 2020 | Issue 2, Pages 116-120 | ISSN 2668-7194 (print), ISSN 2668-9987 (online)

Citation: Rus M., Sandu L. M., Tănase T., Boumediene S., Delcea C., (2020). The effect of the
corona virus (COVID-19) on Mental Health. Int J Advanced Studies in Sexology. Vol. 2, Issue 2, pp. 116-120. Sexology Institute of Romania.

DOI: 10.46388/ijass.2020.13.30

Full Article | Figures & data| References | Citations |Reprints & Permission

Abstract

The study aimed to determine the Effect of corona virus (COVID-19) on the mental health of Algerian people. The study sample consists of (764) persone who chosen from two countries, and to achieve the objectives of the study the researchers developed the "Effect of Coronavirus on Mental. Health Form, after collecting and processing information statistically using  the Statistical Package for Social Sciences (SPSS, the researchers reached the following results: - there are significant differences between the mental health of the Romanians and the mental health of the Algerians, during the period of the epidemic covid19. There are significant differences in mental health in women and men. There are significant differences in mental health in women and men, according to nationality. There is assumed that there are differences of perception on the danger of coronavirus contamination depending on gender and nationality. There is assumed that there are significant differences between men and women in terms of lifestyle, according to nationality. There are significant differences regarding the feeling of worthlessness, in women and men according to nationality.

Keywords: effect, coronavirus, mental health, quality of life.

**Comment by ppolischuk** [comment]
Hello, we noticed the batch of issues you recently filed to this Github repo, but it's unclear what your intentions are. Can you please clarify?
