### ISSUE TITLE
Question, not about sexology...

### ISSUE THREAD

**Issue by user1718** [CrossRef/rest-api-doc#538]
I've been using CrossRef to match up publications with authors who use our editing services... mostly to say "Hey, congrats, you're published"... I found some problems when I send over a weird author list in the query (e.g., it has orphaned numerals or parentheticals with affiliation footnotes) Long story short, if I use this regex ([\(]*[0-9#*\/,]+\))|([0-9#*]+) it cleans up the author list and makes for much closer matching.

I don't know if that's helpful- but I did have a question about referenced-by-count and if there's a way to get the list of citations to a publication?

Apologies if this isn't entirely on-point as an issue.

**Comment by ppolischuk** [comment]
The list of citations to a publication is only available for members' own registered content if they also include references with their deposits. More details can be found here. https://www.crossref.org/services/cited-by/

**Comment by user1718** [comment]
Thanks!
