### ISSUE TITLE
Question about Cited By

### ISSUE THREAD

**Issue by pvperez1** [CrossRef/rest-api-doc#539]
First of all, thank you for developing the api.

Is there any way to get the DOI of the works that cited a particular DOI? If a work has a "is-referenced-by-count" > 0, can I get the DOIs that referenced that work?

**Comment by bryanvickery** [comment]
Hi @pvperez1, thanks for your patience and please accept my apologies for the slow reply. Currently only the owner of the DOI can access that list through Crossref.

**Comment by pvperez1** [comment]
Hi @bryanvickery, no worries. I appreciate your reply. What we did was to see the references and get their DOIs instead. Not the same of course, but was enough for the project we were doing. I hope that in the future the DOIs of the "is-referenced-by" will be available to the public
