### ISSUE TITLE
Query parameter seems to interpret anything with colon as DISMAX field query.

### ISSUE THREAD

**Issue by gbilder** [CrossRef/rest-api-doc#54]
Following query for the string "CT coronary angiography: new risks for low-risk chest pain", for example, causes stack trace:

http://api.crossref.org/works?query=CT%20coronary%20angiography%3A%20new%20risks%20for%20low-risk%20chest%20pain

Removing offending colon (%3A) works:

http://api.crossref.org/works?query=CT%20coronary%20angiography%20new%20risks%20for%20low-risk%20chest%20pain

**Comment by kjw** [comment]
Fixed in CrossRef/cayenne@e5e9432a0cb6185ea8e67070a2356f15f72f73fa
