### ISSUE TITLE
A typo in the readme

### ISSUE THREAD

**Issue by kencho51** [CrossRef/rest-api-doc#540]
Hi,

There is a typo in the [readme](https://github.com/CrossRef/rest-api-doc/blob/master/README.md), I think there is an extra `are ` in the paragraph as shown below:
![image](https://user-images.githubusercontent.com/64770635/97252302-a5985a00-1844-11eb-90db-376e59aa8b57.png)

**Comment by ppolischuk** [comment]
Thanks. Fixed.
