### ISSUE TITLE
Problems with family names containing spaces

### ISSUE THREAD

**Issue by edent** [CrossRef/rest-api-doc#541]
I'm unsure if these errors are caused by poor metadata from the original source, or something introduced by CrossRef.

10.21105/joss.00265 returns
```
[ORCID] => http://orcid.org/0000-0001-9218-7797
[authenticated-orcid] => 
[given] => Roger
[family] => A Light
[sequence] => first
```
The given name should be "Roger A" - confirmed against ORCID, and speaking to Roger.

10.1109/e-science.2006.261040
```
[given] => Olivier
[family] => Der Aa
[sequence] => additional
```
The correct name is `Olivier Van Der Aa` - as per the original document.

**Comment by bryanvickery** [comment]
You are correct, these are errors in the metadata from the original source. We can let the publisher know and ask them to correct it

**Comment by bryanvickery** [comment]
The first of these has already been updated

**Comment by pdavis8** [comment]
The publisher has been notified about the second author surname update, closing ticket here.

If there are more issues can you log them here please: https://gitlab.com/crossref/issues/-/issues

Thank you
