### ISSUE TITLE
is doi.org/doiRA the same as api.crossref.org/works/{doi}/agency?

### ISSUE THREAD

**Issue by maxheld83** [CrossRef/rest-api-doc#549]
doi.org, aside from their resolution API, has a [which RA](https://www.doi.org/factsheets/DOIProxy.html#whichra) API.

One might assume that this yields the exact same results as `https://api.crossref.org/works/{doi}/agency`.

Is that so?
Or what might be reasons for divergent results?
(Empirically, I haven't found any yet, but that doesn't mean much).

Motivation:
- the overlap is confusing, might be nice to explain the difference between the two API endpoints in the crossref docs.
- the doi.org api appears to be more performant (b/c edge cashed?) and I'd like to avoid hammering the crossref api in production as much as possible, but I want to make sure I have consistent data.

I think this came up tangentially in #319.

**Comment by ppolischuk** [comment]
Thanks for your questions. Unfortunately I haven't been able to come up with any documentation beyond what you found in #319, and none of the folks who worked on this are with Crossref anymore, so we don't presently have any better information for you. 

We also don't have any reason to expect divergent results, unless the timing works out such that you're requesting agency information after it has changed and before new data is indexed by the REST API. I don't have any examples of that but I believe it's technically possible.

I'll let you know if I can find any other information once anybody else has had a chance to respond.
