### ISSUE TITLE
filter funder by location failed

### ISSUE THREAD

**Issue by jujukiller82** [CrossRef/rest-api-doc#556]
I have a problem, I use REST API to list funders by location, for exemple to retrieve all funders of france:

`https://api.crossref.org/funders?filter=location:France`

will return 0 funders and **this query worked before**.

when i asking 

`https://api.crossref.org/funders?rows=800`

I'm noticing that all values of location is null 

thanks for your help

**Comment by bryanvickery** [comment]
Hi there, and sorry for the delay in coming back to you @jujukiller82 

You are correct. We have issues with our current API and aren't fetching the location info. We'll not be fixing that as we expect to roll out our new API in a month and we do not have the same problem with the new API.

You can download the registry as RDF if you like, and the information in that file does include addressCountry. You'll find the latest RDF here https://gitlab.com/crossref/open_funder_registry

thanks, Bryan
