### ISSUE TITLE
 Escaping commas when filtering - API

### ISSUE THREAD

**Issue by AkshayBhanawala** [CrossRef/rest-api-doc#558]
While I was trying to combine multiple filters, I saw that when I was filtering with filters which contains comma and putting two of them together [ex. category-name x 2 in which values contain comma] will give a response with no items in it.

Look at the following values and URL:
```
category-name:Electronic, Optical and Magnetic Materials
category-name:Surfaces, Coatings and Films
```

- Rest API query - https://api.crossref.org/works?rows=10&filter=category-name:Electronic%2C+Optical+and+Magnetic+Materials,category-name:Surfaces%2C+Coatings+and+Films

This will not give any result items.
And combining it with other filters such as *-date or having integer/decimal values and If these numeric filters are put in front of it, then will generate error like
`java.lang.NumberFormatException: For input string: "2010, Coatings and Films"`

Look at the following values and URL:
```
from-pub-date:2010,
until-pub-date:2010,
category-name:Electronic, Optical and Magnetic Materials,
category-name:Surfaces, Coatings and Films
```

- Rest API query - https://api.crossref.org/works?rows=10&filter=from-pub-date:2010,until-pub-date:2010,category-name:Electronic%2C+Optical+and+Magnetic+Materials,category-name:Surfaces%2C+Coatings+and+Films

Else if these numeric filters are put after comma(s) filters then it'll again give response with no items in it.

**Comment by ppolischuk** [comment]
Thanks for writing this up - looks like a bug having to do with the commas, as you identified.

We have a new version of the API coming out in the next few weeks, and unfortunately this bug exists in that version as well. I'll file it into our backlog for after the API migration is complete.

**Comment by ppolischuk** [comment]
https://gitlab.com/crossref/issues/-/issues/1299

**Comment by ppolischuk** [comment]
We use Gitlab for issue tracking now, so please follow along via the link above.
