### ISSUE TITLE
'Label' instead of 'ID' for facet 'type-name' - API

### ISSUE THREAD

**Issue by AkshayBhanawala** [CrossRef/rest-api-doc#559]
A difference I saw in API response in facet.

While the documentation [here](https://github.com/CrossRef/rest-api-doc#facet-counts) says that '**type-name**' facet will be '**ID**', but instead it'll return '**label**' values.

Facet name | Maximum values | Description
-- | -- | --
**`type-name`** | **`*`** | Work type name, such as **`journal-article`** or **`book-chapter`**

The given Facet URL will be enough to show it.
```
https://api.crossref.org/works?rows=0&facet=type-name:*
```

it should be returning IDs like
- **`journal-article`**
- **`book-chapter`** 

but it returns
- **`Journal Article`**
- **`Chapter`** 

---
One more about the same stuff is, type-name 'Labels' in following URL,

```
https://api.crossref.org/types
```

not all match with labels in 
```
https://api.crossref.org/works?rows=0&facet=type-name:*
```

As one example look at **`Book Chapter`** in [types list API endpoint](https://api.crossref.org/types)
and try to look same in [facet list for type-name](https://api.crossref.org/works?rows=0&facet=type-name:*).
in here, it'll be given as **`Chapter`** only.

---

Also in documentation it's written as **`book-chap`** instead of **`book-chapter`**

---
Just some small stuff..

**Comment by ppolischuk** [comment]
Looks like a lot overlap with [this issue](https://gitlab.com/crossref/issues/-/issues/1142). I've pasted your details there as well. We'll try to cover it as part of that issue.
