### ISSUE TITLE
Getting "429 Too Many Requests" error from crossref

### ISSUE THREAD

**Issue by vjainhighwirepress** [CrossRef/rest-api-doc#562]
Hi Crossref Support Team,

Please note that we are getting the "429 Too Many Requests" error from crossref while we are making requests for any ISSN. Below are some sample URLs we are trying to hit but getting the "You have sent too many requests in a given amount of time." response.

https://api.crossref.org/works?filter=issn%3A2470-9468%2Ctype%3Ajournal-article%2Cfrom-pub-date%3A2020-06-01&rows=1000&cursor=%2A
https://api.crossref.org/works?cursor=%2A&filter=issn%3A0008-5472%2Ctype%3Ajournal-article%2Cfrom-pub-date%3A2020-06-01&rows=1000
https://api.crossref.org/works?cursor=%2A&filter=issn%3A0028-3878%2Ctype%3Ajournal-article%2Cfrom-pub-date%3A2020-06-01&rows=1000
https://api.crossref.org/works?cursor=%2A&filter=issn%3A1067-151X%2Ctype%3Ajournal-article%2Cfrom-pub-date%3A2020-06-01&rows=1000
https://api.crossref.org/works?cursor=%2A&filter=issn%3A2154-1663%2Ctype%3Ajournal-article%2Cfrom-pub-date%3A2020-06-01&rows=1000

Is there any ongoing issue?

Thanks
Vineet

**Comment by vjainhighwirepress** [comment]
@ppolischuk can this be looked into urgently?

**Comment by ppolischuk** [comment]
Hi Vineet,

I don't see anything wrong with those requests, and they return a valid response for me. 

It looks like all of the requests with the highwire vizor-developer email address listed for the mailto:, all coming from the same IP, are returning a 429 response, regardless of whether your request is for an ISSN or anything else.

Do you have some kind of script or other process that is exceeding our rate limit? That would explain the 429 http response code.

**Comment by vjainhighwirepress** [comment]
Hi @ppolischuk,

We stopped all the processes running but still, we are observing the same error. Please can you tell by when can start making requests to Crossref?

**Comment by myalter** [comment]
Are you using only the public pool? Have you tried with an email specified? Can you provide the ip address you're using to do the queries? (You can use a service like https://whatismyipaddress.com/ to get your ip). Can do a query with `curl -v` and provide the result?

**Comment by vjainhighwirepress** [comment]
@myalter @ppolischuk Yes, we use public pools only. 

Please find below the output of curl command 

![image](https://user-images.githubusercontent.com/74899490/124173902-4ffa0880-dac9-11eb-82e9-5fd0b7ba5be4.png)

and IP address of the machine is 54.200.35.56

**Comment by vjainhighwirepress** [comment]
@ppolischuk @myalter please can you tell by when can we start submitting the requests?

**Comment by vjainhighwirepress** [comment]
@ppolischuk @myalter please close this case we are able to submit the requests now. Thanks.
