### ISSUE TITLE
Unable to validate credentials

### ISSUE THREAD

**Issue by vjainhighwirepress** [CrossRef/rest-api-doc#563]
Hi Crossref Support Team,

Kindly note that we are unable to validate user credentials from http://doi.crossref.org/servlet/getForwardLinks?usr=<username>&pwd=<password> though the credentials are valid and we are able to log in on the portal. Please find below artefacts for your reference.

![image](https://user-images.githubusercontent.com/74899490/124461056-ce96c480-ddad-11eb-9932-8a2b39e09670.png)

![image](https://user-images.githubusercontent.com/74899490/124461710-9b086a00-ddae-11eb-94a4-8a4d6fe87618.png)

Please check if there is an issue. @ppolischuk @MikeYalter 

Thanks
Vineet

**Comment by pdavis8** [comment]
Hello,

Against the username "cbmed" the service for retrieving forward links has not been activated. You would need to contact us at support@crossref.org for us to check against your account and activate that service for you.
Thanks,
Paul
