### ISSUE TITLE
`/works/{doi}` have started returning 'Resource not found.' for a lot of valid DOIs

### ISSUE THREAD

**Issue by vals** [CrossRef/rest-api-doc#564]
Hi,

Did something change with the API or database recently? I'm increasingly getting 'Resource not found.' when querying DOIs that works with the doi.org redirect.

An example:
- [https://api.crossref.org/works/10.1038/s41467-021-23949-5](https://api.crossref.org/works/10.1038/s41467-021-23949-5) - Gives 'Resource not found'.
- [https://doi.org/10.1038/s41467-021-23949-5](https://doi.org/10.1038/s41467-021-23949-5) - Takes you to the paper correctly

A second example:
- [https://api.crossref.org/works/10.1038/s41593-021-00880-y](https://api.crossref.org/works/10.1038/s41593-021-00880-y) - Gives 'Resource not found.'
- [https://doi.org/10.1038/s41593-021-00880-y](https://doi.org/10.1038/s41593-021-00880-y) - Takes you to the paper correctly

Best,
/Valentine

**Comment by ppolischuk** [comment]
There was a bug in one of the services that populates the new version of the API we're rolling out (see here if you're unfamiliar: https://www.crossref.org/blog/behind-the-scenes-improvements-to-the-rest-api/ )

It's since been fixed and the examples you reported are working now.

Thank you.

**Comment by vals** [comment]
I checked and they indeed do! Thank you very much! I'll have a read of the blog post.
