### ISSUE TITLE
some doi-s return 404 even though the website finds them

### ISSUE THREAD

**Issue by gabor-lbl** [CrossRef/rest-api-doc#565]
The following doi-s all return 404 when queried via api.crossref.org/works but work fine via the crossref website. Am I calling the api incorrectly?

doi-s:
10.1007/JHEP06(2021)177
10.1038/s42005-021-00650-z
10.1039/d1na00307k
10.1103/PhysRevMaterials.5.064007
10.1140/epjc/s10052-021-09317-z
10.1177/10943420211022829
10.1177/10943420211028940
10.3847/1538-4357/abff5d

Specifically calling:
`curl https://api.crossref.org/works/10.3847/1538-4357/abff5d`
returns a 404, but:
`curl https://www.crossref.org/10.3847/1538-4357/abff5d`
works fine.

Thanks!

**Comment by JimHokanson** [comment]
I skimmed through and these all seem to have been published relatively recently. My impression is that the API database is not exactly the same as the "master" database and that the former lags the latter. I don't know if the API has any guarantees as to how long it takes from submission to API availability. That or something with the recent API update is causing issues .... Although this is all speculation. See also #564 which I think is the same issue.

**Comment by ppolischuk** [comment]
Thank you for noting this. We are using Gitlab for all issue tracking moving forward, so please file issues there in the future.

https://gitlab.com/crossref/issues/-/issues/1387

These and other DOIs reported missing are now available via the public pool of the REST API, and we believe the underlying issue has been resolved.
