### ISSUE TITLE
Select with exclusions

### ISSUE THREAD

**Issue by mmcclenn** [CrossRef/rest-api-doc#568]
For efficiency, I would like to fetch results with every field *except* references. There is currently no feasible way to do this with 'select=', because if I specify every field I am interested in and new attributes are subsequently added, they wouldn't appear in my list and thus I wouldn't get them.

I propose that select take an optional ! before the field list, which would cause the listed fields to be excluded while returning everything else. That way, I could issue a query such as "/works?query=xxx&rows=5&select=!references,indexed".

**Comment by ppolischuk** [comment]
Issue tracking now takes place in our Gitlab repositories. I've filed your feature request there and will prioritize it against other new feature development. 

https://gitlab.com/crossref/issues/-/issues/1632
