### ISSUE TITLE
`until-index-date` should be inclusive

### ISSUE THREAD

**Issue by hubgit** [CrossRef/rest-api-doc#57]
According to [the filter documentation](https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#filter-names), `from-index-date` and `to-index-date` are inclusive, but using the same date for both `from-index-date` and `to-index-date` produces an empty list: 
http://api.crossref.org/works?filter=from-index-date:2015-03-06,until-index-date:2015-03-06

Moving `until-index-date` one day forward shows that there are articles indexed on the previous day, so they should have been included in the previous list.
http://api.crossref.org/works?filter=from-index-date:2015-03-06,until-index-date:2015-03-07

**Comment by kjw** [comment]
Issue with comparing dates without times against timestamps. Now fixed.

**Comment by hubgit** [comment]
Thanks :+1:
