### ISSUE TITLE
Journals endpoint has more than 100000 results now

### ISSUE THREAD

**Issue by shariqueabdullah** [CrossRef/rest-api-doc#576]
Hi,

The /journals endpoint now has 108870 total records.

It is now impossible to query all the records using the paging and offset mechanism for the /journals endpoint.

Is there another way possible? Can we work this around somehow?

**Comment by ppolischuk** [comment]
For large results sets, we recommend using cursors for deep paging: https://api.crossref.org/swagger-ui/index.html#/Journals/get_journals

And FYI, issue tracking in Github is deprecated at Crossref. We use Jira for internal issue tracking, and inquiries like yours can either be posted to our community forum at https://community.crossref.org/, or sent to our support staff at support@crossref.org
