### ISSUE TITLE
documentation for `transform/application`

### ISSUE THREAD

**Issue by Koushikphy** [CrossRef/rest-api-doc#579]
I can query this to get indiviual bibtex information from the API 
```bash
https://api.crossref.org/works/10.1021/acs.jpca.2c01209/transform/application/x-bibtex
```
But I don't see the documentation for the `transfomation/application` anywhere. Like what are the options for this? Is there any optional query? Can I get the citation in other format than bibtex?

**Comment by ppolischuk** [comment]
Apologies for the confusion. Documentation for the transform endpoint can be found in the CrossCite documentation. https://citation.crosscite.org/docs.html#sec-4

Please note that issue tracking in Github is now deprecated. Questions like this are best posted in our community forum at https://community.crossref.org/c/metadata-retrieval/27
