### ISSUE TITLE
Consistent article-title between CrossRef APIs

### ISSUE THREAD

**Issue by mfenner** [CrossRef/rest-api-doc#58]
This is not really an issue with the REST API, but rather consistency across the different CrossRef APIs.

http://api.crossref.org/works/10.3902/jnns.14.205 returns an array for the title (an empty string - presumably for the English title - and the title in Japanese). Calling the CitedBy API (for 10.1371/journal.pbio.0020369) returns metadata for 10.3902/jnns.14.205, but is missing the `article-title` field.

**Comment by mfenner** [comment]
Another interesting example is http://api.crossref.org/works/10.3758/s13423-011-0070-4, with the `title` ["Audiotactile interactions in temporal perception"]. The CitedBy API uses "Audiotactile Interactions In Temporal Perception" as `article-title`, i.e. different case.

**Comment by ckoscher** [comment]
Can you be precise "the CitedBy API"? (example please)

**Comment by ckoscher** [comment]
Will investigate.

**Comment by mfenner** [comment]
CitedBy API call with missing `article-title` for `10.3902/jnns.14.205` is http://doi.crossref.org/servlet/getForwardLinks?usr=USR&pwd=PWD&doi=10.1371/journal.pbio.0020369.

CitedBy API call with `article-title` in lowercase for `10.3758/s13423-011-0070-4` (and differences between `first_page` and `page`) is http://doi.crossref.org/servlet/getForwardLinks?usr=USR&pwd=PWD&doi=10.1371/journal.pone.0000001

**Comment by kjw** [comment]
Closing this as not related to the REST API.
