### ISSUE TITLE
Exception when using filter from-pub-date and specifying day

### ISSUE THREAD

**Issue by nmehta** [CrossRef/rest-api-doc#59]
Hi - 

When issuing the following query, an exception is returned:

Query:
http://api.crossref.org/works?rows=3&filter=from-pub-date:2013-01-02&query=Cognitive+and+motivational+deficits+together+with+prefrontal+oxidative+stress+in+a+mouse+model+for+neuropsychiatric+illness

Exception:
org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: org.apache.solr.search.SyntaxError: Cannot parse '((year:[2014 TO *] OR (year:2013 AND month:[0 TO *]) OR (year:2013 AND month:-1 AND day:[2 TO *])))': Encountered " "-" "- "" at line 1, column 77. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <LPARAMS> ... <NUMBER> 

It also seem like the generated solr query is incorrect where the 2nd clause should not be present, (year:2013 AND month:[0 TO *]), as I am trying to find all matches where the pub date is on or after 2013-01-02. 

Thank you very much for your support!  I find the REST API to be very flexible and easy to use. 

Thanks,
Neil

**Comment by kjw** [comment]
That's very nasty. Fixed. Thanks so much for reporting this issue. It was caused by a recent change, glad it was caught quickly.
