### ISSUE TITLE
Return article license by default?

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#6]
Would it be possible to return license by default?  This would be helpful on the client side wrt to filtering out works that may or may not be useable, etc.

**Comment by Blahah** [comment]
I am working on similar functionality but for a command-line tool.

Maybe the solution I've ended up with is useful for you @sckott. First I query with a `facet` by `license`, to get the list of licenses used in the results, and the count of each one. Then once the user has agreed to the ones they want, they can make the full request.

For example, if the user makes the following query: 

```
http://api.crossref.org/works?query=c4+photosynthesis&filter=has-full-text:true,from-pub-date:2005-01-01
```

I first run:
```
http://api.crossref.org/works?facet=license:*&query=c4+photosynthesis&filter=has-full-text:true,from-pub-date:2005-01-01
```

Which gives me:
```
http://www.elsevier.com/tdm/userlicense/1.0/: 736,
http://www.elsevier.com/open-access/userlicense/1.0/: 106,
http://creativecommons.org/licenses/by/3.0/: 26,
http://creativecommons.org/licenses/by-nc-nd/3.0/: 25,
http://creativecommons.org/licenses/by/4.0/: 18,
http://doi.wiley.com/10.1002/tdm_license_1: 16,
http://onlinelibrary.wiley.com/termsAndConditions: 13,
http://link.aps.org/licenses/aps-default-license: 11,
http://creativecommons.org/licenses/by-nc-nd/4.0/: 11,
http://pubs.acs.org/page/policy/authorchoice_termsofuse.html: 5,
http://creativecommons.org/licenses/by-nc/3.0/: 5,
http://creativecommons.org/licenses/by-nc-sa/3.0/: 2,
http://link.aps.org/licenses/aps-default-accepted-manuscript-license: 1,
http://creativecommons.org/licenses/by-nc/4.0/: 1
```

**Comment by sckott** [comment]
@Blahah Nice solution. I assume you give the user a prompt?  

That solution would be something useful to set globally for a user session, that is, say which licenses you accept, so we ignore others - And optionally per request. I like the global option setting

**Comment by Blahah** [comment]
We will save a global YAML config file and then print instructions for editing it. Optional local YAML config to override global settings.

**Comment by sckott** [comment]
@Blahah  :+1:

**Comment by sckott** [comment]
@Blahah can you give an example of how this works with `getpapers`?
