### ISSUE TITLE
http://api.crossref.org/works/10.320l/eid1408.071304

### ISSUE THREAD

**Issue by mfenner** [CrossRef/rest-api-doc#62]
I am confused by this work in the REST API. The prefix contains a letter and the DOI is missing in the metadata. Found this as this article is citing a PLOS paper. Can you clarify?

**Comment by gbilder** [comment]
Could it be that somebody transcribe the number 1 as the letter  I? 

The following seems to work:

http://api.crossref.org/works/10.3201/eid1408.071304

**Comment by mfenner** [comment]
What confuses me is that the CrossRef REST API responds with a 200 status and some (different) metadata, rather than a 404 or 400 (invalid DOI format) status.

**Comment by gbilder** [comment]
Ok, yes. Very odd. Seems to have something to do with mEDRA.

**Comment by kjw** [comment]
API was reporting an erroneous record (itself with a malformed DOI, accidentally normalized into a blank DOI) for malformed DOIs. This is now fixed - the API will report a 404 in these circumstances. I may later change this again to report a 400.

http://api.crossref.org/works/10.320l/eid1408.071304

**Comment by mfenner** [comment]
Thanks!
