### ISSUE TITLE
Assumptions about forward slashes in DOI

### ISSUE THREAD

**Issue by emanuil-tolev** [CrossRef/rest-api-doc#65]
This isn't a bug with the CrossRef API - it is a question about how you are able to do one specific thing with the API.

http://api.crossref.org/works/10.1108/JIC-08-2014-0097/agency

The DOI spec says a DOI can contain pretty much any Unicode char (sorry, can't fish out a reference right now :( ). Obviously in practice this is rarely the case, but when I code up scholarly apps I try to make as few assumptions as possible about a DOI's format.

It struck me in the above URL that you have a "/agency" following the DOI. The most straightforward way to achieve this is to assume that a DOI will only ever have one forward slash in it, the prefix/suffix separator. Is this an assumption you make in your API URL routing? Or is there something more complex going on that allows you to put "/agency" after the DOI?

The reason I ask is because a team I'm part of wants to do something very similar, like /article/{doi}/tab-or-section-related-to-that-article in our own application.

**Comment by ckoscher** [comment]
CrossRef further limits the set of allowed characters to ascii alpha, 
numeric and a few punctuation characters. And of course we allow a "/" 
but we do not prevent a slash from being part of the suffix.

Looking at our data there are 257 DOIs that end in a trailing slash.
A spot check shows that they are likely mistakes (DOIs that never should 
have been created) as they do not point at anything real. We'll take a 
thorough look and if they're all mistakes we'll add a test to prevent 
the creation of DOIs with trailing slash

Chuck

**Comment by emanuil-tolev** [comment]
Thanks for the reply!

> And of course we allow a "/"
> but we do not prevent a slash from being part of the suffix.

Hah, that's interesting! How can you correctly serve a URL like
http://api.crossref.org/works/10.1108/JIC-08-2014-0097/agency
then?

If you don't prevent slashes in the suffix you could have a URL such as
http://api.crossref.org/works/10.1108/JIC-08/2014-0097/agency
- would you serve that correctly? (I guess not quite actually, try clicking that one to see what happens :).)

**Comment by kjw** [comment]
The REST API wouldn't serve that correctly. I am striking a balance between sanity (mine) and correctness.

The error you are finding is actually unrelated to the additional '/' in the DOI. It is the case that the API understands at all that DOI suffixes (including CrossRef's) may contain a '/' character. This is fully expected. The API simply sniffs for a full '/agency' (or '/transform', and others) at the end of the DOI.

The case for having any URL reserved characters at all in a DOI suffix has disappeared (if there ever was one) - I hope in future CrossRef's permitted character set for DOI suffixes will be even more restrictive.

@ckoscher - please can you fix the /doiRA call to stop it producing malformed JSON when a look up attempt is made for a non-existent DOI (been like that for a few weeks now...) :-)

**Comment by kjw** [comment]
> The reason I ask is because a team I'm part of wants to do something very similar, like /article/{doi}/tab-or-section-related-to-that-article in our own application.

You can do this now, and it will work with this API.

**Comment by emanuil-tolev** [comment]
> The error you are finding is actually unrelated to the additional '/' in the DOI. It is the case that the API understands at all that DOI suffixes (including CrossRef's) may contain a '/' character. This is fully expected. The API simply sniffs for a full '/agency' (or '/transform', and others) at the end of the DOI.

Ah, that's golden, thanks a lot. I was hoping suffixes just couldn't contain / but you can't have everything!
