### ISSUE TITLE
How do I use CitedBy API ?

### ISSUE THREAD

**Issue by cppexpert** [CrossRef/rest-api-doc#66]
How do I use CitedBy API ? Where can I register ? I didn't find documentation either but I found following endpoint in other issues here

http://doi.crossref.org/servlet/getForwardLinks?doi=11.1111/AABBz2311430

Thanks!

**Comment by ckoscher** [comment]
Currently Crossref policy restricts the CitedBy API access to only the 
member who owns the given DOI. The public is not allowed to retrieve 
information on CitedBy relations.

Sorry
Chuck

**Comment by ckoscher** [comment]
Current Crossref policy restricts CitedBy API access to the member that 
owns the DOI.  The public is not allowed to retrieve CitedBy information

Sorry
Chuck
