### ISSUE TITLE
Journal query doesn't return jounal

### ISSUE THREAD

**Issue by don01001100** [CrossRef/rest-api-doc#68]
The query `http://api.crossref.org/works?filter=type:journal&query=Urban+Technology&sort=score&order=desc&rows=1000` does not return the journal called `Journal of Urban Technology`, even though there is at least one journal article in that journal, `http://api.crossref.org/works?filter=doi:10.1080/10630739408724477`.

**Comment by kjw** [comment]
Use this type of query to search for journal titles:

`http://api.crossref.org/v1/journals?query=Urban+Technology`

To easily locate works within that journal you can use the ISSN returned in the query above in the query:

`http://api.crossref.org/v1/journals/ISSN/works`

Hope this is helpful.
