### ISSUE TITLE
Filter by date range and partial dates

### ISSUE THREAD

**Issue by mfenner** [CrossRef/rest-api-doc#7]
It appears that there is an issue with date ranges for publication dates (date issued). Compare

    http://api.crossref.org/works?filter=from-pub-date:2014&rows=0&offset=0

With 

    http://api.crossref.org/works?filter=from-pub-date:2014-01-01&rows=0&offset=0

I think the latter query is missing articles with a date-issued year-only and year-month-only. I stumbled upon this when looking for papers by an old friend:

    http://api.crossref.org/works?filter=orcid:0000-0002-1825-0097,from-pub-date:2013-01-01&rows=0&offset=0

**Comment by kjw** [comment]
Dates are now aliased in the way described in my comment above. So if we have a publication date of 2015-12 it will be matched if an 'until-pub-date' filter of 2015, 2015-12 or 2015-12-31 is specified. Before this fix, only the first two would have resulted in a match.
