### ISSUE TITLE
JSON parameters in body of request

### ISSUE THREAD

**Issue by jiacona** [CrossRef/rest-api-doc#70]
In the rest API [documentation](https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#parameters) it mentions that you can pass parameters as URI parameters or as JSON in the body of a request. Is that true? I can't find any other reference of POSTing to the API. I did try and got a 405 Not Allowed.

If posting query parameters as a JSON body is actually a feature, could we perhaps get some further documentation/examples? If it is not, could that section be re-worded to prevent false hope?

Thanks

**Comment by kjw** [comment]
You can, but you must still make a GET request when including the body.
