### ISSUE TITLE
Clarification about what is available from api.crossref versus search.crossref

### ISSUE THREAD

**Issue by mvolz** [CrossRef/rest-api-doc#72]
"The API will only work for CrossRef DOIs. "

Does this mean there is a set of metadata that is not available from api.crossref.org that IS available from search.crossref.org? Or are these working off the same dataset?

**Comment by gbilder** [comment]
Search and api are the same working dataset. 

What this means is that it will not work with DOIs from other DOI registration agencies, such as DataCite, mEDRA, etc.
