### ISSUE TITLE
Examples of rate limit headers

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#74]
can someone point me to examples of API requests for publishers that use the rate limit headers? e.g., `CR-TDM-Rate-Limit`

**Comment by gbilder** [comment]
I'm afraid I don't. Suggest that either you test a sample of FT links form each publisher who provides them to see if they include the headers.

If that doesn't surface anything- then look at the TinyPub sample implementation mentioned here: http://tdmsupport.crossref.org/publishers/

**Comment by sckott** [comment]
Good idea, I'll cycle through a sample of links for each publisher and look at headers
