### ISSUE TITLE
Including online date of publichation for an article

### ISSUE THREAD

**Issue by nmehta** [CrossRef/rest-api-doc#76]
Hi -

In the current API, the the information returned for a given DOI includes the date of issue. 
Would it be possible to also include online publication date? 

This information is available via the dx.doi.org api (content negotiation of application/vnd.crossref.unixsd+xml). 

Thanks so much, 
Neil

**Comment by hubgit** [comment]
I think, ideally, if there are multiple online and print publication dates, the "issued" date in the API response should be the earliest of those dates - unless there's a reason to know both of them (perhaps a later, print date is meant to be used when citing the article?)

**Comment by kjw** [comment]
So Crossref currently has 'formal' recording (after all you can stick anything you like is CrossMark assertions) for:

- online publication date
- print publication date
- unspecified publication date

This is about to be expanded with formal support for:

- received date
- accepted date
- 'available' date (where this differs from any of the publication dates)

All of these are going to be made available via the API, including all current publication dates, as we often get requests to separate them out.

Currently, issued date is the earliest publication date. I'm not sure yet what it is going to become - one option is to leave it as the earliest publication date, another is to make it the earliest of the earliest publication date and availability date.

**Comment by nmehta** [comment]
Thanks for the update Karl.  Do you know when these dates will be made available in the API?

Regarding the issued date, my vote would be to leave it as the earliest publication date.

**Comment by kjw** [comment]
Online and print dates are now provided separately as `published-online` and `published-print`.
