### ISSUE TITLE
Parameter sort on some routes errors

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#79]
e.g., http://api.crossref.org/members?query=united&sort=updated gives 500 status and as content `java.lang.ClassCastException`

I imagine this means that `sort` is not supported, or should be, but isn't working correctly?

**Comment by kjw** [comment]
This is definitely a bug!

**Comment by sckott** [comment]
another eg. ,

http://api.crossref.org/funders?query=NSF&sort=score

<img width="915" alt="screen shot 2016-01-13 at 9 09 21 am" src="https://cloud.githubusercontent.com/assets/577668/12301534/5d9cfaa8-b9d5-11e5-98c8-7d0927150800.png">
