### ISSUE TITLE
Funder: route versus filter

### ISSUE THREAD

**Issue by ioverka** [CrossRef/rest-api-doc#84]
Hi,

shouldn't following two requests return the same result?

http://api.crossref.org/funders/10.13039/501100004963/works -> "total-results":3854
http://api.crossref.org/works?filter=funder:10.13039/501100004963 -> "total-results":0

thanks,
inga

**Comment by sckott** [comment]
Hmm, works with http://api.crossref.org/works?filter=funder:501100004963

**Comment by ioverka** [comment]
ah, haven't thought about dropping the prefix. Thanks!

**Comment by sckott** [comment]
not speaking for crossref, just an observation :)

**Comment by ioverka** [comment]
you are still my hero ;)

**Comment by kjw** [comment]
It should really work with the prefix, too. Will mark to be fixed.

**Comment by kjw** [comment]
Resolved recently. There was an issue with the `funder` filter not correctly normalising DOIs.
