### ISSUE TITLE
multiple license.url filter

### ISSUE THREAD

**Issue by ioverka** [CrossRef/rest-api-doc#87]
the [documentation](https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md) states:

> [...] Multiple filters can be specified in a single query. In such a case, different filters will be applied 
> with AND semantics, while specifying the same filter multiple times will result in OR semantics [...]

I'm not getting the OR to work for license.url:
- http://api.crossref.org/members/78/works?filter=license.url:http://creativecommons.org/licenses/by/4.0/ -> "total-results":7658
- http://api.crossref.org/members/78/works?filter=license.url:http://creativecommons.org/licenses/by-nc-nd/4.0/ -> "total-results":87983
- http://api.crossref.org/members/78/works?filter=license.url:http://creativecommons.org/licenses/by-nc/4.0/ -> "total-results":3
- http://api.crossref.org/members/78/works?filter=license.url:http://creativecommons.org/licenses/by/4.0/,license.url=http://creativecommons.org/licenses/by-nc/4.0/,license.url=http://creativecommons.org/licenses/by-nc-nd/4.0/ -> "total-results":7658

What am I doing wrong?

**Comment by sckott** [comment]
They define dot filters (those with `.` in their name) as somehow different https://github.com/CrossRef/rest-api-doc/blob/master/rest_api.md#dot-filters Maybe that's the reason here?

**Comment by ioverka** [comment]
Yes, that sounds reasonable. I tried to retrieve all works with a CC license, so alternatively: Is it possible to truncate filter values?

**Comment by ioverka** [comment]
Thanks @kjw - Is there anything I can do to get the question answered though?

**Comment by kjw** [comment]
You have `license.url=...` for the second two licenses instead of `license.url:` (as you do correctly for the first.)

Here's how it should be written using the filter parameter syntax:

    http://api.crossref.org/members/78/works?filter=license.url:http://creativecommons.org/licenses/by/4.0/,license.url:http://creativecommons.org/licenses/by-nc/4.0/,license.url:http://creativecommons.org/licenses/by-nc-nd/4.0/
