### ISSUE TITLE
funder_kpi_metadata_best_practice restricted?

### ISSUE THREAD

**Issue by npapastefanakis** [CrossRef/rest-api-doc#88]
Why this document is restricted? 
http://api.crossref.org/docs/funder_kpi_metadata_best_practice.html

Thank you

**Comment by ioverka** [comment]
Maybe a broken link? The start page of this GitHub repository uses following URL for the above doc: https://github.com/CrossRef/rest-api-doc/blob/master/funder_kpi_metadata_best_practice.md
