### ISSUE TITLE
Sage DOIs deposited but still saying unregistered

### ISSUE THREAD

**Issue by loupeck** [CrossRef/rest-api-doc#89]
@kjw continuing on from DOIs that weren't being indexed that we have already done, I have some examples here that we have reprocessed a number of times but still coming back as 'unregistered' - not available in CrossRef. These are for Sage and they have confirmed they were deposited:

- can you check why these aren't being pushed through 
- confirm when they were deposited
- push them through

Unregistered DOI for DOI 10.1177/0042098015612057 
Unregistered DOI for DOI 10.1177/1352458515614093 
Unregistered DOI for DOI 10.1177/0883073815610429 
Unregistered DOI for DOI 10.1177/0883073815610430 
Unregistered DOI for DOI 10.1177/0883073815610431 
Unregistered DOI for DOI 10.1177/1474515115612927 
Unregistered DOI for DOI 10.1177/1474515115613889

**Comment by ckoscher** [comment]
I have a plan for putting in place a back-end monitor service to 
automatically pick up missing DOIs in the rest-api.   Nearly all the 
moving parts are in place, essentially just need a dedicated block of 
time (few days) to pull together. I.m shooting for early Dec.

Chuck

**Comment by loupeck** [comment]
Fab thanks Chuck, would someone be able to pick up on these DOIs for me?

**Comment by loupeck** [comment]
@ckoscher @kjw I wonder if you were able to give us an update on these specific DOIs so I can feed back to Sage? 

FYI @DavidLSommer007

**Comment by loupeck** [comment]
@ckoscher @kjw please can you help me here with the seven DOIs I listed above and why we can't find them in CrossRef when Sage have confirmed they were deposited.

e.g. http://search.crossref.org/?q=10.1177%2F0042098015612057+

**Comment by loupeck** [comment]
I have checked through the API and it says that it is registered with you - http://api.crossref.org/works/10.1177/0042098015612057/agency

{"status":"ok","message-type":"work-agency","message-version":"1.0.0","message":{"DOI":"10.1177\/0042098015612057","agency":{"id":"crossref","label":"CrossRef"}}}

**Comment by ckoscher** [comment]
We're re-running the indexer for the date range 9/23-9/25, hopefully 
that will pick up these DOIs.

**Comment by loupeck** [comment]
Thanks very much, more examples are from ACM 
- http://search.crossref.org/?q=10.1145%2F2833337 - this search produces no results
However when I go to your API, they say they registered them - http://api.crossref.org/works/10.1145/2833337/agency
{"status":"ok","message-type":"work-agency","message-version":"1.0.0","message":{"DOI":"10.1145\/2833337","agency":{"id":"crossref","label":"CrossRef"}}}

ERROR	Unregistered DOI for DOI 10.1145/2833337
ERROR	Unregistered DOI for DOI 10.1145/2831359
ERROR	Unregistered DOI for DOI 10.1145/2820419
ERROR	Unregistered DOI for DOI 10.1145/2820421
ERROR	Unregistered DOI for DOI 10.1145/2820423
ERROR	Unregistered DOI for DOI 10.1145/2820425
ERROR	Unregistered DOI for DOI 10.1145/2822513
ERROR	Unregistered DOI for DOI 10.1145/2822511
ERROR	Unregistered DOI for DOI 10.1145/2822515
ERROR	Unregistered DOI for DOI 10.1145/2822517
ERROR	Unregistered DOI for DOI 10.1145/2822519
ERROR	Unregistered DOI for DOI 10.1145/2746227
ERROR	Unregistered DOI for DOI 10.1145/2814330
ERROR	Unregistered DOI for DOI 10.1145/2814332
ERROR	Unregistered DOI for DOI 10.1145/2814338
ERROR	Unregistered DOI for DOI 10.1145/2735624
ERROR	Unregistered DOI for DOI 10.1145/2739042
ERROR	Unregistered DOI for DOI 10.1145/2735625
ERROR	Unregistered DOI for DOI 10.1145/2736282
ERROR	Unregistered DOI for DOI 10.1145/2823398
ERROR	Unregistered DOI for DOI 10.1145/2823402
ERROR	Unregistered DOI for DOI 10.1145/2823394
ERROR	Unregistered DOI for DOI 10.1145/2823400
ERROR	Unregistered DOI for DOI 10.1145/2825814

**Comment by ckoscher** [comment]
Looks like we had an OAI bug that was causing index failures (OAI 
currently supplies the data feed). This bug was fixed today (Wed Dec 2).
A full reindex is underway.

Chuck

**Comment by loupeck** [comment]
Hi Chuck, I have checked the reprocessing for the files here (when I add the files to the publishers FTP, our daily loader picks these up at around 3am UK time for processing). Your API is still telling us these DOIs are not registered:

ERROR	Unregistered DOI for DOI 10.1177/0042098015612057
ERROR	Unregistered DOI for DOI 10.1177/1352458515614093
ERROR	Unregistered DOI for DOI 10.1177/0883073815610429
ERROR	Unregistered DOI for DOI 10.1177/0883073815610430
ERROR	Unregistered DOI for DOI 10.1177/0883073815610431
ERROR	Unregistered DOI for DOI 10.1177/1474515115612927
ERROR	Unregistered DOI for DOI 10.1177/1474515115613889

**Comment by loupeck** [comment]
@ckoscher apologies just saw your email:

Usually takes about 5 days.... So probably by next Tuesday

I will try reprocessing then

**Comment by MPDLNLTeam** [comment]
Just stumbled about another example (from Springer):

http://api.crossref.org/works/10.1186/s40348-015-0026-2
http://api.crossref.org/works/10.1186/s40348-015-0026-2/agency

**Comment by ckoscher** [comment]
So we discovered an incorrect configuration in our system that may have 
been the cause for lost DOIs in the index. That has been fixed, our 
re-indexing have been partially completed and we're working to complete 
the full reindex. Hopefully it competes over this week end

Chuck
