### ISSUE TITLE
No resource for existing DOIs, api bug?

### ISSUE THREAD

**Issue by mdpi-symfony** [CrossRef/rest-api-doc#90]
I am trying to query the api for an existing doi number:
    http://api.crossref.org/works/10.3390/ma8063101
And am getting no resources.

however, the dx,doi.org works well for that DOI: http://dx.doi.org/10.3390/ma8063101

**Comment by sckott** [comment]
Works fine for me, this is the top of the page that returns. What are you getting?

<img width="363" alt="screen shot 2015-11-23 at 8 28 56 am" src="https://cloud.githubusercontent.com/assets/577668/11342437/47748200-91bc-11e5-98fe-631144edb902.png">

**Comment by kjw** [comment]
There is a delay between DOI registration and metadata indexing (and thus appearance in the API.) The delay used to be up to one day, until about a week ago, when we enabled a new path pushing data into the API with a delay of up to one hour.
