### ISSUE TITLE
items count not correct in some cases

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#91]
e.g., in http://api.crossref.org/funders/10.13039/100000001/works?sample=2

we get `items-per-page: 20` 

whereas JSON shows that we did indeed get 2 items back as requested

<img width="275" alt="screen shot 2015-11-24 at 11 51 31 am" src="https://cloud.githubusercontent.com/assets/577668/11378778/c58e13aa-92a1-11e5-81a4-541d11731654.png">

whereas if we use `/works` alone (http://api.crossref.org/works?rows=2)  with the `rows` param we get the expected items count

<img width="288" alt="screen shot 2015-11-24 at 11 52 44 am" src="https://cloud.githubusercontent.com/assets/577668/11378820/fa10a462-92a1-11e5-895b-46aaa9e65edc.png">

**Comment by kjw** [comment]
items-per-page reflects the number of rows requested. It doesn't indicate how many records are returned in the response (total-results does that for the result set.)

items-per-page comes from some of the terminology in the open search spec.

**Comment by sckott** [comment]
Okay, thanks

**Comment by sckott** [comment]
@kjw  hmm, I'm not sure this is sorted yet. yes, i understand that `items-per-page` is number of rows requested.  __BUT__, the `sample` param gives different results for `items-per-page` than when the `rows` param is used.  Is that intended? Seems those two parameter should behave the same. e.g. the request http://api.crossref.org/works?sample=2&rows=2 gives the error message `Sample cannot be combined with rows or offset` - which suggests to me that `sample` is setting the number to be returned, just as `rows` does
