### ISSUE TITLE
How is organisational authorship expressed?

### ISSUE THREAD

**Issue by darobin** [CrossRef/rest-api-doc#92]
In the case in which a document is authored not by a person but by an organisation, how is that captured? I can't seem to find an example. From what few instances I could find it looks like the idea is that in such cases there are no authors and `publisher` is used. But that can be wrong: my organisation could produce a white paper published by someone else.

Are there any plans to document the JSON format?

**Comment by gbilder** [comment]
I think we've add this, but am looking for confirmation/examples from @kjw

**Comment by kjw** [comment]
Organisational contributors appear where person contributors would, except that they have a `name` field instead of `given` and `family` fields.
