### ISSUE TITLE
Annual Reviews DOIs

### ISSUE THREAD

**Issue by loupeck** [CrossRef/rest-api-doc#94]
Please see the list below - please can you tell me when these were deposited, when they were indexed and when, if they have been, were these available on the CrossRef REST API?

Unregistered DOI for DOI 10.1146/annurev-bioeng-071114-040601
Unregistered DOI for DOI 10.1146/annurev-bioeng-071114-040609
Unregistered DOI for DOI 10.1146/annurev-bioeng-071114-040632
Unregistered DOI for DOI 10.1146/annurev-bioeng-071114-040640
Unregistered DOI for DOI 10.1146/annurev-bioeng-071114-040723
Unregistered DOI for DOI 10.1146/annurev-bioeng-071114-040808
Unregistered DOI for DOI 10.1146/annurev-bioeng-071114-040829
Unregistered DOI for DOI 10.1146/annurev-bioeng-071813-104938
Unregistered DOI for DOI 10.1146/annurev-financial-030215-035912
Unregistered DOI for DOI 10.1146/annurev-financial-091115-014822
Unregistered DOI for DOI 10.1146/annurev-financial-092214-043752
Unregistered DOI for DOI 10.1146/annurev-financial-110311-101741
Unregistered DOI for DOI 10.1146/annurev-financial-110613-034357
Unregistered DOI for DOI 10.1146/annurev-financial-110613-034406
Unregistered DOI for DOI 10.1146/annurev-financial-111414-125820
Unregistered DOI for DOI 10.1146/annurev-financial-111914-041751
Unregistered DOI for DOI 10.1146/annurev-financial-111914-041800
Unregistered DOI for DOI 10.1146/annurev-financial-111914-041807
Unregistered DOI for DOI 10.1146/annurev-financial-111914-041815
Unregistered DOI for DOI 10.1146/annurev-financial-111914-041825
Unregistered DOI for DOI 10.1146/annurev-financial-111914-041834
Unregistered DOI for DOI 10.1146/annurev-financial-111914-041850
Unregistered DOI for DOI 10.1146/annurev-financial-111914-041858
Unregistered DOI for DOI 10.1146/annurev-financial-111914-041906
Unregistered DOI for DOI 10.1146/annurev-financial-111914-041939
Unregistered DOI for DOI 10.1146/annurev-financial-111914-042008
Unregistered DOI for DOI 10.1146/annurev-financial-111914-042024
Unregistered DOI for DOI 10.1146/annurev-financial-111914-042031
Unregistered DOI for DOI 10.1146/annurev-financial-111914-042040
Unregistered DOI for DOI 10.1146/annurev-financial-111914-042056
Unregistered DOI for DOI 10.1146/annurev-linguist-030514-124812
Unregistered DOI for DOI 10.1146/annurev-linguist-030514-124923
Unregistered DOI for DOI 10.1146/annurev-linguist-030514-125100
Unregistered DOI for DOI 10.1146/annurev-linguist-030514-125150
Unregistered DOI for DOI 10.1146/annurev-linguist-030514-125220
Unregistered DOI for DOI 10.1146/annurev-linguist-030514-125312
Unregistered DOI for DOI 10.1146/annurev-med-042513-015127
Unregistered DOI for DOI 10.1146/annurev-med-042513-125551
Unregistered DOI for DOI 10.1146/annurev-med-050913-021703
Unregistered DOI for DOI 10.1146/annurev-med-050913-022228
Unregistered DOI for DOI 10.1146/annurev-med-051113-024537
Unregistered DOI for DOI 10.1146/annurev-med-051113-024633
Unregistered DOI for DOI 10.1146/annurev-med-060513-093205
Unregistered DOI for DOI 10.1146/annurev-med-061813-013241
Unregistered DOI for DOI 10.1146/annurev-med-070213-054849
Unregistered DOI for DOI 10.1146/annurev-med-070813-114317
Unregistered DOI for DOI 10.1146/annurev-med-091113-024550
Unregistered DOI for DOI 10.1146/annurev-med-092112-152941
Unregistered DOI for DOI 10.1146/annurev-med-122313-085916

Please can these be fixed and made available through the CrossRed API

**Comment by ckoscher** [comment]
Spot check shows, created on Dec 8th  and indexed on Dec 11th (which is 
when they became available via rest api)

**Comment by loupeck** [comment]
Great thanks so much for confirming @ckoscher - our expectation is that once deposited, it takes up to 48 hours max for the DOIs to appear in the REST API - is that not the case anymore? This may be why we are seeing an increase in errors. The Annual Reviews file was reprocessed in our loader on 11th but was at 3am UK time so maybe they missed each other by a matter of hours? 

Also I know there is planned work for the API to be indexed without up to 24 hours delay from the main system - I wonder if you can give us an update here as to where you are with the plans here?

**Comment by kjw** [comment]
The components to perform 'index on deposit' - i.e. indexing metadata as soon as it is deposited with Crossref, are now ready, and we're preparing for a test of these soon...

**Comment by loupeck** [comment]
Thanks Karl.

Just checked the loading and we are still getting unregistered DOI as well as CrossRef server error

Type	Message
ERROR	DOI Server Error for 10.1146/annurev-bioeng-071114-040601
ERROR	no implicit conversion of String into Integer
ERROR	DOI Server Error for 10.1146/annurev-bioeng-071114-040632 (504)
ERROR	DOI Server Error for 10.1146/annurev-bioeng-071114-040723 (504)
ERROR	DOI Server Error for 10.1146/annurev-bioeng-071114-040808 (504)
ERROR	DOI Server Error for 10.1146/annurev-financial-092214-043752 (504)
ERROR	Unregistered DOI for DOI 10.1146/annurev-linguist-030514-124812
ERROR	Unregistered DOI for DOI 10.1146/annurev-linguist-030514-124923
ERROR	Unregistered DOI for DOI 10.1146/annurev-linguist-030514-125100
ERROR	Unregistered DOI for DOI 10.1146/annurev-linguist-030514-125150
ERROR	Unregistered DOI for DOI 10.1146/annurev-linguist-030514-125220
ERROR	Unregistered DOI for DOI 10.1146/annurev-linguist-030514-125312
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-042513-015127
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-042513-125551
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-050913-021703
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-050913-022228
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-051113-024537
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-051113-024633
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-060513-093205
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-061813-013241
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-070213-054849
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-070813-114317
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-091113-024550
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-092112-152941
ERROR	Unregistered DOI for DOI 10.1146/annurev-med-122313-085916

**Comment by hubgit** [comment]
> The components to perform 'index on deposit' - i.e. indexing metadata as soon as it is deposited with Crossref, are now ready, and we're preparing for a test of these soon...

Given that quite a few journals deposit their DOI metadata before the articles are published so that the DOIs are active when the articles go live, this could cause article metadata to be available through the API before the articles are published. Are there any plans to reduce Crossref's processing queue so that DOI metadata doesn't need to be deposited in advance?

**Comment by ckoscher** [comment]
Expecting publishers to deposit just-in-time ahead of publication is not reasonable. Some might be able to do it a few minutes ahead, others might do it hours ahead. Regardless of the Crossref deposit processing latency this activity is more driven by publisher work flow and publishing system capabilities. Thus, even if Crossref processing were instantaneous, this problem would still exist, probably to a large degree. 
Creating a fully synchronized release of Crossref DOI metadata and the moment of article availability on-line on the many publisher platforms is not currently being discussed.

**Comment by hubgit** [comment]
The expectation was that publishers would deposit the DOI at the point of publication, rather in advance.

**Comment by ckoscher** [comment]
I looked through our publisher rules and the help documentation and can't find any explicit mention of timing requirements related to DOI registration and publication availability. The only rule is that DOIs must be registered for on-line content.  From my experience most expectations have been simply that the DOI be active before the content becomes available. If there is a requirement to know, based on Crossref data, the moment availability occurs then we should discuss that.

**Comment by kjw** [comment]
I believe there is now a request for comment regarding DOI registration before publication that seems a more appropriate place for this discussion.

**Comment by FlaviusArdelean** [comment]
Hi, I am reopening this case as the DOIs below have still not been processed:

DOI 10.1146/annurev-linguist-030514-124812
DOI 10.1146/annurev-linguist-030514-124923
DOI 10.1146/annurev-linguist-030514-125100
DOI 10.1146/annurev-linguist-030514-125150
DOI 10.1146/annurev-linguist-030514-125220
DOI 10.1146/annurev-linguist-030514-125312

Thank you! @kjw FYI

**Comment by ckoscher** [comment]
Done.

**Comment by FlaviusArdelean** [comment]
Thank you @ckoscher 

@loupeck FYI

**Comment by loupeck** [comment]
Thanks @FlaviusArdelean can you add them back in for processing and then confirm in here if they have processed ok? Thanks very much

**Comment by FlaviusArdelean** [comment]
@loupeck I can confirm that the DOI have resolved successfully.
