### ISSUE TITLE
cursor param use gives 504

### ISSUE THREAD

**Issue by sckott** [CrossRef/rest-api-doc#97]
e.g., http://api.crossref.org/works?query=cell%20biology&cursor=*

```
504 Gateway Time-out

The server didn't respond in time.
```

**Comment by sckott** [comment]
Any thoughts on this?  still having problems using the cursor - trying to get incorporated into the ruby and python libraries...

@kjw

**Comment by ckoscher** [comment]
Scott, for my benefit, can you explain the scenario you trying to address using the cursor feature?  (might be best to respond off line, email me directly ckoscher@crossref.org to keep it off this list)

**Comment by sckott** [comment]
I'm simply trying to use the cursor at all, and it often gives a 504. It's not really a specific use case. I'm trying to incorporate support for the cursor in the Ruby, Python, and R clients I maintain for Crossref - and i'm just reporting this problem I often run into

**Comment by kjw** [comment]
Scott I think we have timeouts set far too low at our load balancer. Looking into this.

**Comment by sckott** [comment]
Thanks, that problem would explain what I see

**Comment by kjw** [comment]
Now set higher, for what its worth (I'm not happy that cursor requests are taking so long.) Is this looking better to you now?

**Comment by sckott** [comment]
I'll have a look

**Comment by sckott** [comment]
Seems to be performing well so far, I'll do some more testing

**Comment by zsimaiof** [comment]
The same problem reoccured. When using the cursor parameter it gives a  504 time-out....

**Comment by kjw** [comment]
Can you pass me details of the cursor and query you made?

**Comment by zsimaiof** [comment]
Sure : 
http://api.crossref.org/journals/1079-7114/works?filter=type:journal-article,from-pub-date:2010-01,until-pub-date:2010-12&cursor=*&rows=1000

But even if i reduce the number of rows requested the same error occurs.
Only when i remove the cursor parameter i am able to retrieve results.

**Comment by zsimaiof** [comment]
Has the problem been solved ? 
I just retested and it seems to be working fairly well : )

**Comment by ckoscher** [comment]
We have an idea, not sure if its a positive fix ... time will tell

**Comment by zsimaiof** [comment]
It worked for some days, but the problem reoccurred since yesterday.

**Comment by zsimaiof** [comment]
Now it's working, but yesterday it didn't.

**Comment by alimoradi** [comment]
Having the same problem here.

**Comment by ckoscher** [comment]
Backend Solr server had problems. Cursor requests can be problematic, we believe (hope) a Solr upgrade will resolve the problem, but doing an upgrade is contingent on some other stuff. In the meantime we need to watch it carefully (note: txt msgs to admin was broken this past weekend, thats fixed)
