### ISSUE TITLE
Given DOI, is there any way to retrieve an abstract e.g. short summary of an article?

### ISSUE THREAD

**Issue by dmitrynovik** [CrossRef/rest-api-doc#98]
Given DOI, is there any way to retrieve an abstract e.g. short summary of an article?

Regards,
D.

**Comment by kjw** [comment]
One way that is not ideal is to simply follow the DOI to its landing page. Most of the time the landing page will contain an abstract. I can imagine it would be possible to get reasonable extraction rates automatically. I can't say anything about whether systematic collection of abstracts directly from publisher's article landing pages would be within T&Cs and yada yada and what not.

**Comment by jenniferlin15** [comment]
Abstracts are part of the deposited metadata set. Let's discuss adding this to REST API, @kjw and @kmeddings.

**Comment by carbureted** [comment]
Abstracts would be very useful! Is there any timeline for inclusion?

**Comment by ckoscher** [comment]
If you have a DOI use the API but append ".xml" to the end. This will return the full deposited XML which 'may' include an abstract.
example:
http://api.crossref.org/works/10.1109/TASC.2010.2088091.xml

Discovering which DOIs have abstracts needs to be on some to-do list.

**Comment by carbureted** [comment]
Awesome, thanks!

**Comment by mikethicke** [comment]
Would be very nice to have this added to the API

**Comment by gbilder** [comment]
Done. See, for example: 

`https://api.crossref.org/works?filter=has-abstract:true`

Note however that abstracts are not commonly deposited yet.

**Comment by zedomel** [comment]
And what about keywords?

**Comment by TheMrugraj** [comment]
Crossref has added this to APIs but in many cases we are not getting abstract.

**Comment by ofou** [comment]
> Crossref has added this to APIs but in many cases we are not getting abstract.

Same here

**Comment by ppolischuk** [comment]
FYI, Crossref uses Jira for issue tracking now. And and our community forum is best-suited for inquiries like this: https://community.crossref.org/c/metadata-retrieval/27

Please join us there, and provide example DOIs for any issues you might be having so that we may properly investigate. Thank you.
