### ISSUE TITLE
Request rate-limiting?

### ISSUE THREAD

**Issue by eddotman** [CrossRef/rest-api-doc#99]
I've been trying to query for a large number of DOIs (100k range) using the cursor parameter to retrieve the max amount of rows (1000?) at a time. However, after some number of DOIs retrieved (50k or so), the responses all seem to fail. 

I didn't see a rate limit or 'requests remaining' field in any of the returned JSON responses, so I'm wondering if there is some behind-the-scenes limit that I'm hitting. Is there some set amount of time that I should set my script to sleep for before querying for more DOIs?

**Comment by kjw** [comment]
There is no limit, however the cursor feature is currently hitting timeouts at a load balancer. I hope to resolve this in the next few days.

**Comment by eddotman** [comment]
Great, thanks so much!

**Comment by kjw** [comment]
Looks like the timeout is now set high enough. But I wonder if you could confirm this is now working for you?

**Comment by eddotman** [comment]
Yup -- it looks like it worked for me. Thanks again!

**Comment by unoexperto** [comment]
Am I hitting the same issue ?
https://github.com/CrossRef/rest-api-doc/issues/196
